### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lzrobots** [facebookresearch/maskrcnn-benchmark#1]
Hi, Any idea about this?
everything in here are installed. https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md

Traceback (most recent call last):
  File "./tools/train_net.py", line 18, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/home/lz/Workspace/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 20, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/home/lz/Workspace/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/home/lz/Workspace/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/home/lz/Workspace/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /home/lz/Workspace/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEl

**Comment by soumith** [comment]
You are compiling the extensions with gcc <= 4.8, while PyTorch requires you to compile the C++ extensions with gcc >= 4.9 I believe.
While the compilation was going on, a huge warning must've popped up on screen warning about this, if I'm not wrong.

**Comment by fmassa** [comment]
Also, make sure that the environment that you used to compile the extension is the same as the one you use to run it.

**Comment by fabienbaradel** [comment]
I get an error similar to @lzrobots (no problem during installation - gcc version = 5.4.0).
I have create a new enviroonement `pytorch-1.0` at the before running your [INSATLL.md](https://github.com/fabienbaradel/maskrcnn-benchmark/blob/master/INSTALL.md)
```
~/github/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py in <module>()
      6 from .misc import ConvTranspose2d
      7 from .misc import interpolate
----> 8 from .nms import nms
      9 from .roi_align import ROIAlign
     10 from .roi_align import roi_align

~/github/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py in <module>()
      1 # Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
      2 # from ._utils import _C
----> 3 from maskrcnn_benchmark import _C
      4
      5 nms = _C.nms

ImportError: /home/fbaradel/github/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEl
```

@fmassa @soumith Any idea where this problem could come from?

There is no problem when installing and running `demo.py`on macOS (cpu).

**Comment by fmassa** [comment]
I have the impression that at runtime the script might be loading the wrong pytorch binary. Could you check that `torch.__file__` points to the right torch?

**Comment by fabienbaradel** [comment]
Indeed I am pointing to the wring pytorch version:
```
In [1]: import torch

In [2]: torch.__file__
Out[2]: '/home/fbaradel/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/torch/__init__.py'
# it should be '/home/fbaradel/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/torch/__init__.py'
```
That's weird because I am running this script from the good env (`pytorch-1.0` and not `open-mmlab`). Is there a way to enforce running the good version of pytorch?

**Comment by fmassa** [comment]
so, here is what I would do:
- create a fresh new conda env and switch to it
- install ipython via `conda install ipython`. This will install several dependencies, like `pip`, so that we are sure that we don't pick something else
- follow the installation instructions as before.

While installing each one of the libs (with conda or pip), check that they are indeed pointing to the right installation path, and also check that `which conda` and `which pip` are the right one

**Comment by fabienbaradel** [comment]
Thanks @fmassa and @lzrobots it solved my problem as well.

**Comment by fmassa** [comment]
Great!
I'll add a line in the README explaining that you need to first install `ipython` with conda.

**Comment by sergeywong** [comment]
It's caused by _GLIBCXX_USE_CXX11_ABI=1 when compile pytorch from source or install with conda with defaults channel.  For more infos, refer to this link [https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627](https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627 )

**Comment by TheLostIn** [comment]
Maybe you entered the wrong directory.
For me,I've created a project directory and I've cloned the maskrcnn repository in it.And then I installed the maskrcnn environment following the commands in README.md,and also I'created another maskrcnn directory.And as I entered the previous directory to run the train command,I got the error'cannot import _C'.By accident ,I came back to the later directory,it worked well.Amazing!
