### ISSUE TITLE
How many iterations is a epoch

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#1012]

**Comment by fmassa** [comment]
Depends on the dataset and the number of GPUs used.

For COCO 2017 train, on 8 GPUs, the 90k iterations correspond to roughly 12-13 epochs

**Comment by SkeletonOne** [comment]
@fmassa Thanks for your reply!
So assume I train on only on one GPU, could I calculate the epoch by:
12/8(GPUs)?
Or if I change bs from 8 to 2, should I divide it by 4?

**Comment by fmassa** [comment]
@SkeletonOne you can find more information in the scheduling rules in https://github.com/facebookresearch/maskrcnn-benchmark#single-gpu-training, which are the same from Detectron

**Comment by SkeletonOne** [comment]
@fmassa I sincerely appreciate your reply! That really helps me a lot!
BTW, less epoch will definitely constrain the results, right?

**Comment by mseyfi** [comment]
CoCo 2017 trainsplit has 118287 images. In detectron2 the default value for images_per_batch is 16. That is across all GPU machines. Therefore if you have 8 GPUs then each GPU gets only 2 images. 
118287/16 is the number of iterations per epoch. 1 schedule training or what it is called x1 schedule is 90k iterations. 
90/118287/16 ![image](https://user-images.githubusercontent.com/38817131/122187806-3e1b3300-ce44-11eb-8904-158ff6150620.png)12 epochs.
