### ISSUE TITLE
is it also available for pytorch0.4

### ISSUE THREAD

**Issue by kaixin-bai** [facebookresearch/maskrcnn-benchmark#1014]
## ❓ Questions and Help
for some reason i must use pytorch 0.4, is it also available for pytorch0.4? 
Thanks a lot!

**Comment by Dorozhko-Anton** [comment]
The info from the[ installation guide](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md)  proposes to use PyTorch 1.0 nightly + . I suppose it is not available for `0.4`
```
Requirements:
PyTorch 1.0 from a nightly release. It will not work with 1.0 nor 1.0.1. Installation instructions can be found in https://pytorch.org/get-started/locally/
```
