### ISSUE TITLE
Make DatasetCatalog non-static and config overridable

### ISSUE THREAD

**Issue by rwightman** [facebookresearch/maskrcnn-benchmark#1017]
## 🚀 Feature
Make DatasetCatalog (and perhaps ModelCatalog for consistency) an non-static class and pass config into it on creation. Allow config keys to override or change aspects of the Catalog, especially DATA_DIR.

Related to #106 

## Motivation

To train from a different folder I currently need to cut and paste the whole paths_catalog.py file and change the config to point to that. I have to remember to keep both up to date and not push my 'working' paths_catalog because I don't want to leak details about my filesystem or stomp over a team members config, etc.

Symlinks within my workspace are not ideal for me. I like to work out of the code folder and linking a massive dataset there requires additional IDE config to avoid a scanning mess and makes recursive greps a pain. I also change mounts/mappings and would rather do that via command line for a given run rather than change links.

## Pitch

Make DatasetCatalog a non-singleton(ish)/non-static class, pass the global config into `__init__` and allow it to override values like DATA_DIR so that we can:

1. add a DATA_DIR key to the config.yml
2. specify on command line `python tools/train_net.py --config-file retinanet_R-50-FPN_1x.yaml OUTPUT_DIR ./output DATA_DIR /blah/blah`

Usage in `build.py` would go from something like:
```
    paths_catalog = import_file(
        "maskrcnn_benchmark.config.paths_catalog", cfg.PATHS_CATALOG, True
    )
    DatasetCatalog = paths_catalog.DatasetCatalog
    dataset_list = cfg.DATASETS.TRAIN if is_train else cfg.DATASETS.TEST

    # If bbox aug is enabled in testing, simply set transforms to None and we will apply transforms later
    transforms = None if not is_train and cfg.TEST.BBOX_AUG.ENABLED else build_transforms(cfg, is_train)
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
```
to
```
    dataset_catalog = paths_catalog.DatasetCatalog(cfg)
    dataset_list = cfg.DATASETS.TRAIN if is_train else cfg.DATASETS.TEST

    # If bbox aug is enabled in testing, simply set transforms to None and we will apply transforms later
    transforms = None if not is_train and cfg.TEST.BBOX_AUG.ENABLED else build_transforms(cfg, is_train)
    datasets = build_dataset(dataset_list, transforms, dataset_catalog, is_train)
```

## Alternatives

Could leave DatasetCatalog to be used in a static manner but optionally pass config into get and allow overrides there. Doesn't seem any cleaner given how small the usage surface is currently.

**Comment by sarahmass** [comment]
This would be awesome!

**Comment by sarahmass** [comment]
ok, I got something to work.  It isn't pretty but it works.  
1. Add _C.DATA_DIR = " to maskrcnn-benchmark/maskrcnn_benchmark/config/defaults.py
2. add to top of paths_catalog.py file: from maskrcnn_benchmark.config import cfg 
3.  in paths_catalog.py change
```
data_dir = DatasetCatalog.DATA_DIR
```
to

```
    if cfg.DATA_DIR == ""
            data_dir = DatasetCatalog.DATA_DIR
     else:
            data_dir = cfg.DATA_DIR`
```

Then I just added the path at the comand line DATA_DIR D:  (I had mine in my D drive)

**Comment by rwightman** [comment]
@sarahmass  FYI I've implemented and tested both approaches mentioned, the 'alternative' is on a public branch, it ended up being fewer changes:
https://github.com/rwightman/maskrcnn-benchmark/commit/c923361d082c55d3e8aa6aa20e0178b0ef50f647
