### ISSUE TITLE
Can I use maskrcnn-benchmark train my dataset  without mask annotation for object detection? 

### ISSUE THREAD

**Issue by tianlanli** [facebookresearch/maskrcnn-benchmark#1027]
My dataset have  classes and boudingboxxes annotation . I don't have mask annotation.
 I want to know can i train my dataset use this benchmark even i don't have mask annotation ?

**Comment by Dorozhko-Anton** [comment]
Yes, you can use maskrcnn-benchmark in only object detection configuration without mask annotations. Check out the config files that start with `e2e_faster_rcnn` 

For example, as in this config:
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/e2e_faster_rcnn_fbnet.yaml
And you can compare with `MODEL.MASK_ON True` configuration here 
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/e2e_mask_rcnn_fbnet.yaml

**Comment by liz2020** [comment]
Yes, you can. As mentioned by Dorozhko-Anton, you can turn off the mask in the config file. Besides, you can use the area of the bbox as the segmentation(although it doesn't take the benefit of having a segmentation), or use another semantic segmentation code (deeplabv3+, for example) to first predict the segmentation and then use that for your training on maskRcnn.

**Comment by tianlanli** [comment]
I know, thank you very much

**Comment by Dorozhko-Anton** [comment]
@tianlanli  Did you succeed in using `faster_rcnn` mode of maskrcnn_benchmark?

**Comment by tianlanli** [comment]
> @tianlanli Did you succeed in using `faster_rcnn` mode of maskrcnn_benchmark?

yes

**Comment by LeviViana** [comment]
Thanks @Dorozhko-Anton ! I'm closing this issue now.
