### ISSUE TITLE
How should I set the DATASETS in config file? I‘m using VOC datasts...

### ISSUE THREAD

**Issue by a954217436** [facebookresearch/maskrcnn-benchmark#1031]
## ❓ Questions and Help
I made 4 txt in “Imagesets" folder,  they are : train.txt, val.txt, trainval.txt, test.txt.  What's their exact use and how should I set it in the config file ?

I set it like this, but I'm not sure......

DATASETS:
  TRAIN: ("voc_JY_train","voc_JY_val",)
  TEST: ("voc_JY_test",)

I wish someone could explain it to me. Thanks for reading this. Enjoy your day!!

**Comment by rnsandeep** [comment]
You need to create your own .txt files by partitioning your dataset into train, val, test.

Use this code https://github.com/rnsandeep/utils/blob/master/createsplit.py
give your xmls folder as argument to this code. It will generate all the .txt files.
