### ISSUE TITLE
Parameters for Multi_GPU Training?

### ISSUE THREAD

**Issue by lixingyi8947** [facebookresearch/maskrcnn-benchmark#1033]
## ❓ Questions and Help
Hi, if I have a 8-GPU server, but GPU-0 and GPU-1 are being used by others, how to set up parameters for 6-GPU training to avoid GPU-0 and GPU-1? I tried export NGPUS=6 and CUDA_VISIBLE_DEVICES = [2,3,4,5,6,7] python XXXXX but it does not work

**Comment by Dorozhko-Anton** [comment]
Try something like this
```
export NGPUS=6
CUDA_VISIBLE_DEVICES = '2,3,4,5,6,7' python -m torch.distributed.launch --nproc_per_node=$NGPUS /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "path/to/config/file.yaml" MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN images_per_gpu x 1000 
```

**Comment by lixingyi8947** [comment]
@Dorozhko-Anton Thanks! It works now!

**Comment by jersonal** [comment]
> hi！when i use :
> CUDA_VISIBLE_DEVICES="3,4" python -m torch.distributed.launch --nproc_per_node 2 train_net.py
> i meet some trouble, like this:
> RuntimeError: CUDA error: an illegal memory access was encountered
> terminate called without an active exception
> How can I solve it，thanks a lot!

> i have same Error.did you solve it?
