### ISSUE TITLE
How to set the FBNet config?

### ISSUE THREAD

**Issue by zhaoxuyan** [facebookresearch/maskrcnn-benchmark#1035]
## ❓ Questions and Help

Thanks for your contribution @newstzpz 
But I have a question when configuring FBNet 's .yaml file.
```
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 200
```

Are these numbers related to the `number of GPUs` or `batch_size per img`？

Thank you in advance for your reply！

**Comment by zhaoxuyan** [comment]
And I noticed that you set `BASE_LR` to 0.045. (for 8 GPU)
Is it related to the `number of GPUs`? As mentioned in [scheduling rules from Detectron](https://github.com/facebookresearch/Detectron/blob/master/configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14-L30)

If I training with 4 GPUs, how could I adjust the `BASE_LR`?
Thank you in advance for your reply！

**Comment by Dorozhko-Anton** [comment]
1. You're right `BASE_LR` is related to the number of GPUs. Normally, you can use the same linear scaling as in Detectron.   
Make sure to adjust `MAX_ITER` and `STEPS`
```
  # Equivalent schedules with...
  # 1 GPU:
  #   BASE_LR: 0.0025
  #   MAX_ITER: 60000
  #   STEPS: [0, 30000, 40000]
  # 2 GPUs:
  #   BASE_LR: 0.005
  #   MAX_ITER: 30000
  #   STEPS: [0, 15000, 20000]
```
Following this scaling, for 4 GPUs `BASE_LR` can be 2 times smaller than for 8. `0.0225`

2. `cfg.SOLVER.IMS_PER_BATCH` is related to the number of GPUs
https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/data/build.py#L116
3. The parameters of `RPN` that you mentioned are not related to the number of GPUs and works per image per inference
```
# Total number of RPN examples per image
_C.MODEL.RPN.BATCH_SIZE_PER_IMAGE = 256
```

**Comment by zhaoxuyan** [comment]
@Dorozhko-Anton Thank you very much!
