### ISSUE TITLE
The training of Mask R-CNN gets slower and slower.

### ISSUE THREAD

**Issue by RogerChern** [facebookresearch/maskrcnn-benchmark#1038]
## ❓ Questions and Help
I have tried different torch versions(1.1 and 1.2) and different platforms(1080Ti and 2080Ti) and the gradual slowdown is consistent. 
I guess this may be due to there are more and more positive RoIs during training and the mask branch may take longer to process these increased RoIs.

So could you please give some details about how the training iteration time is measured in MODEL_ZOO for Mask R-CNN?

![image](https://user-images.githubusercontent.com/5038495/62922835-f908be80-bdde-11e9-8f81-149447b66506.png)

**Comment by LeviViana** [comment]
Your guess is right. You just made too few iterations for the ETA to be accurately estimated. [This](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/engine/trainer.py#L91) is how the ETA is calculated, which is very unstable if `max_iter >> iteration`.
