### ISSUE TITLE
Convert mask rcnn to onnx failed. RuntimeError: ONNX export failed

### ISSUE THREAD

**Issue by WonderAndMaps** [facebookresearch/maskrcnn-benchmark#1039]
Hi, I was trying to convert a mask rcnn model (maskrcnn-benchmark) to onnx model. I encountered this error
```
RuntimeError: ONNX export failed: Couldn't export Python operator _NewEmptyTensorOp
```
I think that is some class defined here
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/layers/misc.py#L18
Anyone has any solutions?

**Comment by jinfagang** [comment]
You can try export fastercnn to onnx first, I would be much more easy.

**Comment by WonderAndMaps** [comment]
@jinfagang Thanks for replying. I've successfully export faster rcnn to onnx. But when I try mask, I can only manage to get the pretrained one in model zoo exported successfully. It failed on my own model although it is finetuned on the pretrained one.

**Comment by jinfagang** [comment]
@WonderAndMaps What do u mean can only export official model, does not they are same? If you can export maskrcnn model from official, then rest thing is only change some class_num to fit your dataset.

**Comment by WonderAndMaps** [comment]
@jinfagang They should be the same except for the weights and num of classes. However, I am getting the error so I am quite confused.

**Comment by jinfagang** [comment]
what's the error then

**Comment by WonderAndMaps** [comment]
```
RuntimeError: ONNX export failed: Couldn't export Python operator _NewEmptyTensorOp
```

**Comment by WonderAndMaps** [comment]
The reason for this error is because the example image I used, my maskrcnn could not detect any masks so for some layers the input is of size 0. Using another image from the training set solves the problem. Now I can export to onnx.

**Comment by jinfagang** [comment]
@WonderAndMaps  would u like share a onnx model to test speed?

**Comment by WonderAndMaps** [comment]
@jinfagang Here it is [https://drive.google.com/file/d/1fyoAMj084941xUbKbROgXYRU_QBZ2QNj/view?usp=sharing](https://drive.google.com/file/d/1fyoAMj084941xUbKbROgXYRU_QBZ2QNj/view?usp=sharing)

**Comment by WonderAndMaps** [comment]
It would be great if you can share some results of your speed test.

**Comment by jinfagang** [comment]
@WonderAndMaps Besides the model, how did u defined your output and input preprocess?

**Comment by WonderAndMaps** [comment]
For preprocessing
```
"""
    Preprocessing image.
    """
    # convert to BGR format
    image = torch.from_numpy(numpy.array(pil_image)[:, :, [2, 1, 0]])
    original_image = image
    image = torch.nn.functional.upsample(image.permute(2, 0, 1).unsqueeze(0).to(torch.float), size=(960, 1280)).to(torch.uint8).squeeze(0).permute(1, 2, 0).to('cuda')

    image = image.permute(2, 0, 1)

    if not cfg.INPUT.TO_BGR255:
        image = image.float() / 255.0
        image = image[[2, 1, 0]]
    else:
        image = image.float()
```

For outputs:
```
def single_image_to_top_predictions(image):
    image_list = ImageList(image.unsqueeze(0), [(int(image.size(-2)), int(image.size(-1)))])

    for param in coco_demo.model.parameters():
        param.requires_grad = False

    result, = coco_demo.model(image_list)
    scores = result.get_field("scores")
    masks = result.get_field("mask")
    result = (result.bbox, result.get_field('labels'), scores, masks)
    return result
```

And `coco_demo` is just
```
    coco_demo = COCODemo(
        cfg,
        confidence_threshold=0.7,
        show_mask_heatmaps=False,
        masks_per_dim=2,
        min_image_size=480,
    )

    # prepare for onnx export
    coco_demo.model.prepare_onnx_export()
```

**Comment by WonderAndMaps** [comment]
My intention of exporting it to onnx was to serve the model with TensorRT Inference Server but I got some errors there.

**Comment by WonderAndMaps** [comment]
I did try the traced model but I couldn't get the installation right. @jinfagang Do you have any experience with [https://github.com/t-vi/maskrcnn-benchmark/blob/scripting/demo/trace_model.py](https://github.com/t-vi/maskrcnn-benchmark/blob/scripting/demo/trace_model.py)?

**Comment by jinfagang** [comment]
Trace model is used for libtorch? If wanna speed up inference benefit from TensorRT, using ONNXRuntime is also an option since you do not need implement all ops in TensorRT, I believe ONNXRuntime can using TensorRT as backend by default.

**Comment by clw5180** [comment]
> I did try the traced model but I couldn't get the installation right. @jinfagang Do you have any experience with https://github.com/t-vi/maskrcnn-benchmark/blob/scripting/demo/trace_model.py?

Have you meet this problem:  RuntimeError: 'ONNX symbolic expected a constant value in the trace' ? Thanks a lot !

**Comment by jinfagang** [comment]
Haven't meet that problem. But for onnx to TensorRT, there need some surgeon to do..

**Comment by Chanbluky** [comment]
@WonderAndMaps which pytorch version did you use to convert onnx model? i also followed the recommended steps to convert onnx model, but it always failed at the end. 
the log: [https://github.com/t-vi/maskrcnn-benchmark/pull/3]

thanks!

**Comment by birdflies** [comment]
> My intention of exporting it to onnx was to serve the model with TensorRT Inference Server but I got some errors there.

Did you solve it?

**Comment by AidenFather** [comment]
> The reason for this error is because the example image I used, my maskrcnn could not detect any masks so for some layers the input is of size 0. Using another image from the training set solves the problem. Now I can export to onnx.

@WonderAndMaps Can you please share your work in convert maskrcnn to onnx? Thanks in advance!
