### ISSUE TITLE
Does the 'matched_idxs' in balanced_positive_negative_sampler refers to 'labels' in loss.py?

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#1040]
## ❓ Questions and Help
In balanced_positive_negative_sampler.py: 

    def __call__(self, matched_idxs):
        """
        Arguments:
            matched idxs: list of tensors containing -1, 0 or positive values.
                Each tensor corresponds to a specific image.
                -1 values are ignored, 0 are considered as negatives and > 0 as
                positives.

while in loss.py:

sampled_pos_inds, sampled_neg_inds = self.fg_bg_sampler(labels)

which may lead to a mis-understanding? Cus in matched_idxs, -1 is negative.
Or am I making a mistake?

**Comment by Dorozhko-Anton** [comment]
In `matched_idxs`:  -1 values are ignored,  0 are negatives,  >=1 are positives

https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/modeling/balanced_positive_negative_sampler.py#L37-L39

**Comment by SkeletonOne** [comment]
[https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/modeling/rpn/loss.py#L69](url)

**Comment by SkeletonOne** [comment]
> https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/modeling/rpn/loss.py#L69
