### ISSUE TITLE
New project using maskrcnn-benchmark: Multitask Universal Lesion Analysis Network (MULAN)

### ISSUE THREAD

**Issue by viggin** [facebookresearch/maskrcnn-benchmark#1046]
##  Intro to a new project using maskrcnn-benchmark
Hello! Please allow me to introduce our new project: Multitask Universal Lesion Analysis Network (MULAN). It can detect a variety of lesions in CT images, predict multiple tags (body part, type, attributes) for each lesion, and segment it as well. It will be very useful for clinicians and researchers of computer-aided diagnosis to analyze their medical images.
The code is here: [MULAN](https://github.com/rsummers11/CADLab/tree/master/MULAN_universal_lesion_analysis)
We adapted and improved maskrcnn-benchmark. Thank you maskrcnn-benchmark developers for this excellent project!
Can you add our project to the readme file of maskrcnn-benchmark, in the section "Projects using maskrcnn-benchmark"? I believe many researchers will be interested in it. Thank you!

**Comment by fmassa** [comment]
Hi,

Sorry for the delay in replying.

Can you send a PR to maskrcnn-benchmark adding your project in the "Projects using maskrcnn-benchmark" section?

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/1160
