### ISSUE TITLE
How to use without anaconda

### ISSUE THREAD

**Issue by Aditya715** [facebookresearch/maskrcnn-benchmark#1063]
## ❓ Questions and Help
I want to use this project for further use by using Linux python using virtualenv but unable to do the same. Kindly, help.

**Comment by Darshan2701** [comment]
@Aditya715 But is that a hard and fast rule to use to Virtualenv? I have not tried with that environment, but with Anaconda it is simple and easy.

**Comment by Aditya715** [comment]
It's not that hard but I want to use it without anaconda environment, I just want to use the basic system virtualenv. I,e the venv we make using python -m venv venv

**Comment by Darshan2701** [comment]
@Aditya715 Interesting, sorry with that. But request you to post such information in case you made it work.

**Comment by Aditya715** [comment]
Made it possible. I'll post the bash script ASAP.
