### ISSUE TITLE
How to run demo on cpu? Is gpu compulsory to run demo?

### ISSUE THREAD

**Issue by Aditya715** [facebookresearch/maskrcnn-benchmark#1069]
I'm getting AttributeError while importing predictor, I found this is an error of Cuda.... I don't want to run it on cuda. On cuda it's working fine but without cuda it's pushed me the Attribute Error

**Comment by Darshan2701** [comment]
@Aditya715 I think you need to run it on the CPU device than the GPU device. So can you please try changing cfg.MODEL.DEVICE to CPU instead of GPU.
