### ISSUE TITLE
subprocess.CalledProcessError: Command  XXX  returned non-zero exit status 1.

### ISSUE THREAD

**Issue by xuwuheng123** [facebookresearch/maskrcnn-benchmark#1075]
When I run the multi-gpu training code:

"python -m torch.distributed.launch --nproc_per_node=$NGPUS /workspace/xwh/maskrcnn-benchmark-master/tools/train_net.py MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN images_per_gpu x 1000"

 ,there is an error:

 "Command '['/home/xuwuheng/anaconda3/envs/maskrcnn_benchmark/bin/python', '-u', '/workspace/xwh/maskrcnn-benchmark-master/tools/train_net.py', '--local_rank=0', 'MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN', 'images_per_gpu', 'x', '1000']' returned non-zero exit status 1."

help me help me!

**Comment by RhettGee** [comment]
have you solved the problem? The problem also blocked me recently.

**Comment by xuwuheng123** [comment]
> have you solved the problem? The problem also blocked me recently.

I have solved it
Remove the end and input:
python -m torch.distributed.launch --nproc_per_node=2 /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "path/to/config/file.yaml"
The end is to explain the previous operation, you can remove it.

**Comment by joe660** [comment]
> > have you solved the problem? The problem also blocked me recently.
> 
> I have solved it
> Remove the end and input:
> python -m torch.distributed.launch --nproc_per_node=2 /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "path/to/config/file.yaml"
> The end is to explain the previous operation, you can remove it.

这是什么意思  我也遇到了同样的问题  不知道如何解决？
