### ISSUE TITLE
Admins for the repo

### ISSUE THREAD

**Issue by botcs** [facebookresearch/maskrcnn-benchmark#1079]
Hi,

The lib is growing and it has quite a lot of new active users. That's great!

Probably the small fixes and patches would be easy to review however there are greater features proposed that would be quite handy but definitely it can be overwhelming to maintain a stable version with all these awesome PRs.

As far as I know @fmassa is responsible for the integrity of this repo, however he is also managing the torchvision lib itself, that has probably a wider user-base and importance from fb's perspective.

What I would suggest is to appoint some of the experienced contributors to review PRs on the behalf of Francisco, so the active user base could be kept growing and new features could be added dynamically. I guess permission to modify a feature/bleeding-edge branch would be enough for us to integrate and collect all the new features, and periodically - when @fmassa  has time - these features could be merged into the stable master branch.

CCing a few fellas, what would be your opinion?
@wangg12 @qizhuli @AdanMora @bernhardschaefer

**Comment by fmassa** [comment]
Hi @botcs 

Thanks for the issue, this is indeed very true that is hard to maintain both.

I've nominated two people in the past to help address issues, but they do not have merge rights to the repo.

I'd be happy to extend the scope of rights of a few experienced contributors.

cc @soumith for thoughts
