### ISSUE TITLE
Any plans for "Mesh R-CNN" CVPR 2019

### ISSUE THREAD

**Issue by thangvubk** [facebookresearch/maskrcnn-benchmark#1099]
It would be very helpful if [Mesh R-CNN](https://arxiv.org/pdf/1906.02739.pdfhttps://arxiv.org/pdf/1906.02739.pdf) is supported.

**Comment by ColaerSugar** [comment]
so do I

**Comment by ppwwyyxx** [comment]
official code released in https://github.com/facebookresearch/meshrcnn
