### ISSUE TITLE
AP = 0 when test, but it's working in train and the loss convergence normally

### ISSUE THREAD

**Issue by JimLee4530** [facebookresearch/maskrcnn-benchmark#1113]
## ❓ Questions and Help
When I use the evaluation command
`python -m torch.distributed.launch --nproc_per_node=1 tools/test_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" TEST.IMS_PER_BATCH 1`

I get follows result:
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] =0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

I take sample output compares with targets when test_net

![image](https://user-images.githubusercontent.com/4339314/65816229-ad459380-e22b-11e9-93fc-f9deddb1db48.png)

The num_boxes is very different，but I am sure I have loaded the parameters of the model.

Has anyone encountered the same problem?

**Comment by nalbwa** [comment]
Have you figured out the solution? Seems like I am having the same problem.

**Comment by ChongjianGE** [comment]
Hi @JimLee4530 
I also have the problem recently. Have you solved it?

**Comment by JimLee4530** [comment]
Yes, I solved it. I found it can not get the true ckpt file, so I input it in commond, like 
python -m torch.distributed.launch --nproc_per_node=1 tools/test_net.py --ckpt ~/.torch/models/_detectron_35858933_12_201cnn_model_final.pkl --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" TEST.IMS_PER_BATCH 16

**Comment by JayZhu0104** [comment]
@JimLee4530 Hi, i also meet this problem now.But i haven't solve it.
I did't have this file "_detectron_35858933_12_201cnn_model_final.pkl"
And under "~/.torch/models", i only have one file "R-50.pkl"
How can i get this file "_detectron_35858933_12_201cnn_model_final.pkl"?
Thank u very much:)
