### ISSUE TITLE
COCODemo object: pickle data was truncated

### ISSUE THREAD

**Issue by BelhalK** [facebookresearch/maskrcnn-benchmark#113]
## 🐛 Bug

The creation of the COCODemo object is interrupted with the following error message

> pickle data was truncated

The progression bar stops at around 70%
## To Reproduce

The following code reproduces the error
```
from maskrcnn_benchmark.config import cfg
from predictor import COCODemo
config_file = "../configs/caffe2/e2e_mask_rcnn_R_50_FPN_1x_caffe2.yaml"

# update the config options with the config file
cfg.merge_from_file(config_file)
# manual override some options
cfg.merge_from_list(["MODEL.DEVICE", "cpu"])
coco_demo = COCODemo(
    cfg,
    min_image_size=800,
    confidence_threshold=0.7,
)
```
## Expected behavior

The CocoDemo Object is supposed to load and be created.

## Environment

PyTorch version: 1.0.0.dev20181029
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14
GCC version: Could not collect
CMake version: version 3.10.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[conda] pytorch-nightly           1.0.0.dev20181029         py3.7_0    pytorch

**Comment by fmassa** [comment]
Looks like the model downloading didn't work as expected (network problem maybe?).
Can you delete the file that starts with a `_` in `~/.torch/models/` and try running it again?
It should work if the download is not interrupted.

As this seems to be a network issue, I'm closing this issue, but let me know if you still have issues.

**Comment by BelhalK** [comment]
Indeed it works.
Sorry about that.
Have a good day

**Comment by fmassa** [comment]
Great, glad to know that it works now!

**Comment by murufeng** [comment]
> Looks like the model downloading didn't work as expected (network problem maybe?).
> Can you delete the file that starts with a `_` in `~/.torch/models/` and try running it again?
> It should work if the download is not interrupted.
> 
> As this seems to be a network issue, I'm closing this issue, but let me know if you still have issues.

can you tell me where is the file?
