### ISSUE TITLE
A error report when building apex and maskrcnn-benchmark

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#1131]
## ❓ Questions and Help
After the command python setup.py install --cuda_ext --cpp_ext

Raises error: /usr/local/cuda/lib64/libcudnn.so.7/include: Not a directory
however, I do not understand what kind of file libcudnn.so.7 is, which seems like not a folder

I found out that the CUDNN_PATH in .bashrc is  /usr/local/cuda/lib64/libcudnn.so.7
Then, I did the operation of modifying it, just change libcudnn.so.7 to some random characters which has no meaning, and the building procedure successfully finished.

I was wondering what is the problem? Could anybody help me?

**Comment by anl13** [comment]
I think, you should set `CUDNN_PATH` as `/usr/local/cuda/` instead of `/usr/local/cuda/lib64/libcudnn.so.7`

**Comment by SkeletonOne** [comment]
@anl13 yeah thanks!
