### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by ChongjianGE** [facebookresearch/maskrcnn-benchmark#1138]
## ❓ Questions and Help
I have met the problem of libgcc, which is quiet hard to solve.

This problem occurs after each training session or at the end of the inference session.  But I was quiet sure that I have installed and linked the libgcc correctly. Does anyone have any thoughts of the problem?

libgcc_s.so.1 => /dockerdata/chongjiange/software/anaconda3/envs/maskrcnn/lib/libgcc_s.so.1 (0x00007fb60472d000)

Here is my env.
Python = 3.7
Pytorch = 1.0-nightly
CUDA = 10.0
gcc = 7.3.0

**Comment by botcs** [comment]
could you try it out with 1.0.0 (despite it is not in the INSTALL.md)?

**Comment by ChongjianGE** [comment]
Hi @botcs 

I have tried that before. But, it did not help. 
Did you solve the problem by change the version of pytorch?

**Comment by botcs** [comment]
I didn't have this issue before

**Comment by ChongjianGE** [comment]
@botcs 
Thank you for your help. 
By the way, have you ever tried pytorch-1.0.0 (not 1.0-nightly) to run the code successfully?

**Comment by botcs** [comment]
yeah, it mostly runs well with 1.2 (and possibly 1.3 as well) after a few syntax changes.

**Comment by ChongjianGE** [comment]
@botcs 
Than you for the info~
