### ISSUE TITLE
How to do evaluation on CityscapesDataset?

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#1139]
Well, I was reimplementing maskrcnn-benchmark on Cityscapes based on #1090 by @botcs 
And currently I'm facing a problem of evaluating the result in ../runs/cityscapes_poly/model_final.pth
I tried to evaluate the results, but I could not able to do it based on the instructions in #1090 and #1096 , it raises

    raise NotImplementedError("Unsupported dataset type {}.".format(dataset_name))
NotImplementedError: Unsupported dataset type CityScapesDataset.

Besides, when I try to visualize the results in Mask R-CNN demo.ipynb, it also raises another error:

/maskrcnn-benchmark/demo/predictor.py in <listcomp>(.0)
    405         scores = predictions.get_field("scores").tolist()
    406         labels = predictions.get_field("labels").tolist()
--> 407         labels = [self.CATEGORIES[i] for i in labels]

IndexError: list index out of range

So could anyone produce a detailed instruction of how to evaluate the results? 

P.S.
 what's more, I can only do training on poly...When I train with binaymask it raises

/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py", line 151, in __call__
    sampled_pos_inds_subset = torch.nonzero(labels > 0).squeeze(1)
RuntimeError: copy_if failed to synchronize: device-side assert triggered

**Comment by botcs** [comment]
Hi @SkeletonOne 

Thanks for checking out these two PRs. I would suggest looking at #1104 as well, which may get you more relevant scores with the dataset.

So what you've mentioned are the following two issues:
- the `NotImplementedError`
- `demo.ipynb` not handling your new dataset

## Not Implemented Error
These two functionalities that you've checked out are independent, which means your code-base wouldn't automatically recognize that A) you have a new evaluation tool (either abstract-coco or the abstract-cityscapes) B) you have a new dataset

To link together the evaluation with the new dataset you have to explicitly link them together in the `maskrcnn_benchmark/data/datasets/evaluation/__init__.py`, by adding a new line like in [here](https://github.com/facebookresearch/maskrcnn-benchmark/pull/1104/files#diff-1cc21c25c102c4bbe573540bf167e1f3R25-R26)

## Demo issue
Currently the `demo.ipynb` is not updated to work with abstract datasets, rather they work with COCODatasets and their subclasses.

The main issue here, is that in the abstract dataset the way you store labels are `list(str)` format, while the COCO CATEGORIES are more like `dict(int, str)`. putting an extra line where you reuse the AbstractDataset's `id_to_class` field as `CATEGORIES` could actually resolve this problem.
Contributions are welcome :)

**Comment by SkeletonOne** [comment]
@botcs Sincerely appreciate for your detailed reply! Through #1104 I successfully finished the evaluation and get the final results!
However, I'm still confused of the differences between the two evaluation approaches in #1090

**Comment by botcs** [comment]
> However, I'm still confused of the differences between the two evaluation approaches in #1090
There are subtle differences between the [COCO metric](http://cocodataset.org/#detection-eval) and the [CityScapes metric](https://www.cityscapes-dataset.com/benchmarks/#instance-level-scene-labeling-task) by definition.

I would be interested in seeing a common/diff list of these two, however if you are not reporting scores in a paper both scores would probably do well for pair-wise performance comparison between trainings.

**Comment by SkeletonOne** [comment]
@botcs Got it, THX!
