### ISSUE TITLE
How can I run test_net.py using the official trained model?

### ISSUE THREAD

**Issue by JayZhu0104** [facebookresearch/maskrcnn-benchmark#1147]
## ❓ Questions and Help
When I use the evaluation command:
python tools/test_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" TEST.IMS_PER_BATCH 2

I get follows result:
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] =0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

I see someone add “--ckpt” in command, like this:
python tools/test_net.py **--ckpt ~/.torch/models/_detectron_35858933_12_201cnn_model_final.pkl** --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" TEST.IMS_PER_BATCH 2

But I can't find this file "_detectron_35858933_12_201cnn_model_final.pkl". And  Under ~/.torch/models directory, I only have one file: R-50.pkl

And I use the command:
python tools/test_net.py **--ckpt ~/.torch/models/R-50.pkl** --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" TEST.IMS_PER_BATCH 2
The AP is still 0

Could you help me with this problem?
Thanks~

**Comment by Darshan2701** [comment]
@JayZhu0104 You need to make sure that the path to the trained model is correct in the config file.

**Comment by JayZhu0104** [comment]
> @JayZhu0104 You need to make sure that the path to the trained model is correct in the config file.
Yes, I am sure the path of the config file is correct. And finally, I solved the isuue by manually downloading the official trained model. Thanks for your reply!
