### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:

### ISSUE THREAD

**Issue by lingbo666** [facebookresearch/maskrcnn-benchmark#1153]
## ❓ Questions and Help
I run with python tools/train_net.py --config-file configs/e2e_ms_rcnn_R_50_FPN_1x.yaml,and get the error:
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 53, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/dspuser/maskscoring_rcnn/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 62, in load
    self._load_model(checkpoint)
  File "/home/dspuser/maskscoring_rcnn/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 97, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"))
  File "/home/dspuser/maskscoring_rcnn/maskscoring_rcnn/maskrcnn_benchmark/utils/model_serialization.py", line 79, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/dspuser/anaconda3/envs/msrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for roi_heads.maskiou.predictor.maskiou.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([3, 1024]).
	size mismatch for roi_heads.maskiou.predictor.maskiou.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([3]).

--------------------
I have learned some issues ,just like 430 , 15 and so on, and I try the first method in 430 , and 
https://github.com/facebookresearch/maskrcnn-benchmark#finetuning-from-detectron-weights-on-custom-datasets. but still exist this error.  I know the problem may be in last layer, because it's for coco 81classes, however I have just 2class. But I really can not deal with it by using method above.  Another idea in 430 is to make  model surgery, but I do not know which files I should modify.  I am looking forward to  method to solve it . Thanks in advance .

**Comment by Darshan2701** [comment]
@lingbo666 Did you do the model surgery and saved your model?

**Comment by lingbo666** [comment]
@Darshan2701 I just have tried to download a model and delete as #430 ,but it did not work for me. Another method is model surgery, but I can not find witch files I can do it .

**Comment by lingbo666** [comment]
I have solved this problem, and run maskscoring-rcnn successfully. this problem is that I do not delete last layer which for coco81. Then I try #430 some methods,  but bug still exist. Finally, I find methods in #430 may not delete all, so I need delete all the weight ,bis.
months:
newdict['model'] = removekey(_d['model'],
                             ['cls_score.bias', 'cls_score.weight', 'bbox_pred.bias', 'bbox_pred.weight','mask_fcn_logits.bias','mask_fcn_logits.weight'])

when remove, like this, remove these and it run successfully for me. 
I hope this can help who encounter this problem.If any question, please point out. Thanks!!
