### ISSUE TITLE
where did this sentence import _C 'from maskrcnn_benchmark import _C'?

### ISSUE THREAD

**Issue by FanShuixing** [facebookresearch/maskrcnn-benchmark#1161]
## ❓ Questions and Help
Hi.I have seen this line 'from maskrcnn_benchmark import _C' many times in maskrcnn_benchmark/layers.For example, in maskrcnn_benchmark/layers/roi_pool.py,there is also importing  _C,and in Line18,` output, argmax = _C.roi_pool_forward(
            input, roi, spatial_scale, output_size[0], output_size[1]
        )`,I can't understand _C's usage.Could you help to tell me how to understand this usage?
Looking forward you reply.

**Comment by simaiden** [comment]
It's used to open the config files in .yaml format

**Comment by FanShuixing** [comment]
@simaiden Hi,Thanks for your attention. I have figured out this question after many days, and _C is not used to open the config files.The _C is from the file _C.cpython-36m-x86_64-linux-gnu.so in maskrcnn-benchmark which is produced by the lines "python setup.py build develop".
