### ISSUE TITLE
Adding ResNet152 or ResNeXt152?

### ISSUE THREAD

**Issue by yaoliUoA** [facebookresearch/maskrcnn-benchmark#117]
## ❓ Questions and Help
Hi, 

Detectron supports more models than this package, such as very deep models like ResNet152 and ResNeXt152. It will be much helpful if this package also supports ResNet152 and ResNeXt152. Any plans of adding ResNet152 or ResNeXt152 to this package?

**Comment by fmassa** [comment]
Pre-trained Caffe2 ResNeXt152 support has been added in https://github.com/facebookresearch/maskrcnn-benchmark/pull/405  by @LeviViana
