### ISSUE TITLE
My dataset only have two classess, what should i tune?

### ISSUE THREAD

**Issue by guanbin1994** [facebookresearch/maskrcnn-benchmark#118]
## ❓ Questions and Help
My dataset only have two classess, what should i tune?
which .py should i change.
I am a rookie, thank you very much!

(My dataset is already in COCO format.)

**Comment by fmassa** [comment]
Hi,

This question is similar to https://github.com/facebookresearch/maskrcnn-benchmark/issues/15, and I propose a number of solutions there.

I'm closing this issue as a duplicate, but let me know if you have further questions.
