### ISSUE TITLE
from maskrcnn_benchmark import _C ImportError: /home/chenjie/github/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by ChenjieXu** [facebookresearch/maskrcnn-benchmark#119]
I met an ImporError when I ran WebCam demo.

from maskrcnn_benchmark import _C
ImportError: /home/user/github/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

I built pytorch from source.

**Comment by fmassa** [comment]
Hi,

This seems like a duplicate of https://github.com/facebookresearch/maskrcnn-benchmark/issues/1

What is probably happening is that the PyTorch version that you used to compile `maskrcnn-benchmark` is not the same as the one you use to run python.

Also, can you do
```python
import torch
print(torch.__version__)
```
and paste the results?

**Comment by ChenjieXu** [comment]
Thank you. I follow the reply in #1 . I installed ipython first, then pytorch, and installed ninja at last. 
Here is my result. 1.0.0a0+02d3787

**Comment by fmassa** [comment]
So it's working now?

**Comment by ChenjieXu** [comment]
Yes. It is working！But there are some problems while I ran the demo. If I ran maskrcnn demo in jupyter notebook, 'No module named maskrcnn_benchmark' occurred. So I ran it in terminal again. After installing requests module manually, everything works fine in terminal.

**Comment by fmassa** [comment]
I think your jupyter notebook is not using the environment that you installed `maskrcnn-benchmark`. You might want to install `jupyter notebook` in your newly created environment.

**Comment by elevenjiang1** [comment]
> Thank you. I follow the reply in #1 . I installed ipython first, then pytorch, and installed ninja at last.
> Here is my result. 1.0.0a0+02d3787

hello,I also need to use MaskRCNN ,but the result of (print(torch.__version__)is 1.01,and it cant be used in terminal,how can i do?

**Comment by elevenjiang1** [comment]
now the main thing is that  " cannot import name '_C' from 'maskrcnn_benchmark " I cant run the demo

**Comment by Luther1994** [comment]
> cannot

have you solved this? i have the same problem.

**Comment by sunguanxiong** [comment]
I also encountered this problem.
However, I think it's not Pytorch's problem.
Try to update python from 3.6 to 3.7 and follow the INSTALL.md to install again.
It works for me.

**Comment by ggaemo** [comment]
ImportError: /home/jinwon/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

this error occurred to me... Is there any solution to this one? I can't seem to find an exact match of this error

**Comment by haochange** [comment]
> 
> 
> ImportError: /home/jinwon/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
> 
> this error occurred to me... Is there any solution to this one? I can't seem to find an exact match of this error

same error

**Comment by Vickeyhw** [comment]
@haochange  same error ,have you solved this?

**Comment by tyh1151** [comment]
> > ImportError: /home/jinwon/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
> > this error occurred to me... Is there any solution to this one? I can't seem to find an exact match of this error
> 
> same error

the same error . then i remove build directory and rebuild.it works
