### ISSUE TITLE
ModuleNotFoundError: No module named 'cityscapesscripts'

### ISSUE THREAD

**Issue by leizhu1989** [facebookresearch/maskrcnn-benchmark#1196]
## ❓ Questions and Help
When I trained my own data,there is a problem is that ModuleNotFoundError: No module named 'cityscapesscripts' .Why dose it? could you give me some ideas?

**Comment by hasayake007** [comment]
Have you solved this problem?
I met the same problem.

**Comment by forgive0604** [comment]
> Have you solved this problem?
> I met the same problem.

I also met the problem ,how did you solve it?

**Comment by Aurora-Rong** [comment]
so how to solve？I met this too

**Comment by Yuejingkun** [comment]
so how to solve？
