### ISSUE TITLE
INSTALL error

### ISSUE THREAD

**Issue by mrsempress** [facebookresearch/maskrcnn-benchmark#1199]
## ❓ Questions and Help
I follow the `INSTALL.md` to install the cityscapesScripts, like that:
`git clone https://github.com/mcordts/cityscapesScripts.git`
`cd cityscapesScripts/`
`python setup.py build_ext install`
Then I get error 

> Traceback (most recent call last):
> File "setup.py", line 27, in 
> readme = f.read()
> File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
> return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 302: ordinal not in range(128)
So, how can solve it?

**Comment by HAWLYQ** [comment]
hello, @mrsempress  I meet the same problem as you. Could you tell me how do you solve it?

**Comment by aimuch** [comment]
> hello, @mrsempress I meet the same problem as you. Could you tell me how do you solve it?

I install pytorch1.1 using CUDA9.0.
