### ISSUE TITLE
can I install maskrcnn_benchmark on win7 without gpu?

### ISSUE THREAD

**Issue by nanyoullm** [facebookresearch/maskrcnn-benchmark#125]
## ❓ Questions and Help
I try to install maskrcnn_benchmark on win7 without gpu?
I followed this step:
1. `conda create --name maskrcnn_benchmark; source activate maskrcnn_benchmark`
2. `conda install ipython`
3. `pip install ninja yacs cython matplotlib`
4. `conda install pytorch-cpu -c pytorch; pip3 install torchvision`
5. install pycocotools follow: https://github.com/philferriere/cocoapi
6. when I install maskrcnn_benchmark, I set the `CUDA_HOME = None`, and then run `python setup.py build develop`

but failed, the error is about **abi-incompatible**, my `gcc --version` is 7.1.0.
so does maskrcnn_benchmark support windows now?

**Comment by fmassa** [comment]
Hi,

There are currently no nightly (1.0 preview) versions of PyTorch pre-compiled for Windows, so you'd need to compile PyTorch from source.

Apart from that, I'd expect that `maskrcnn-benchmark` should work on Windows, but I haven't tried myself and I don't currently have a Windows machine to try.

Let me know if once you compile PyTorch from source (and recompile `maskrcnn-benchmark`) you still have problems.
