### ISSUE TITLE
can I install torchvision using conda?

### ISSUE THREAD

**Issue by ted8201** [facebookresearch/maskrcnn-benchmark#126]
## ❓ Questions and Help
Following the installation manual: 
```
# install torchvision
cd ~/github
git clone https://github.com/pytorch/vision.git
cd vision
python setup.py install
```
my question is why not install torchvision using conda directly like ?
```
conda install pytorch-nightly torchvision cuda80
```
what problem would this cause?

**Comment by fmassa** [comment]
The problem is that currently installing `torchvision` via conda downgrades `pytorch` to 0.4.1, that's why we propose to install from source while this issue isn't fixed.

**Comment by fmassa** [comment]
Yes, it might lead to conflicts. Try running the demo and see if it works, but I would be cautious.
