### ISSUE TITLE
build error g++

### ISSUE THREAD

**Issue by carlsummer** [facebookresearch/maskrcnn-benchmark#1269]
## ❓ Questions and Help
![image](https://user-images.githubusercontent.com/16281965/93434258-7c59e500-f8fa-11ea-92c3-172880d1612a.png)
Emitting ninja build file /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.7.2
g++ -pthread -shared -L/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib -Wl,-rpath=/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib,--no-as-needed /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_kernel_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.o -L/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda/lib64 -L/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -lpython3.6m -o build/lib.linux-x86_64-3.6/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_kernel_cuda.o：没有那个文件或目录
g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.o：没有那个文件或目录
error: command 'g++' failed with exit status 1

**Comment by carlsummer** [comment]
conda create -n maskrcnn_py36_cu100_conda python=3.6

conda activate maskrcnn_py36_cu100_conda

# conda remove -n maskrcnn_py36_cu100_conda --all


pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

pip install scikit-build -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

pip install ninja yacs cython matplotlib tqdm ipython requests -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

pip install opencv-python -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

pip install torch-1.4.0+cu100-cp36-cp36m-linux_x86_64.whl

pip install torchvision-0.5.0+cu100-cp36-cp36m-linux_x86_64.whl

**Comment by FL77N** [comment]
> conda create -n maskrcnn_py36_cu100_conda python=3.6
> 
> conda activate maskrcnn_py36_cu100_conda
> 
> # conda remove -n maskrcnn_py36_cu100_conda --all
> pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
> 
> pip install scikit-build -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
> 
> pip install ninja yacs cython matplotlib tqdm ipython requests -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
> 
> pip install opencv-python -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
> 
> pip install torch-1.4.0+cu100-cp36-cp36m-linux_x86_64.whl
> 
> pip install torchvision-0.5.0+cu100-cp36-cp36m-linux_x86_64.whl



> ##  Questions and Help
> ![image](https://user-images.githubusercontent.com/16281965/93434258-7c59e500-f8fa-11ea-92c3-172880d1612a.png)
> Emitting ninja build file /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/build.ninja...
> Compiling objects...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> 1.7.2
> g++ -pthread -shared -L/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib -Wl,-rpath=/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib,--no-as-needed /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_kernel_cuda.o /home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.o -L/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda/lib64 -L/home/admin/anaconda3/envs/maskrcnn_py36_cu102_conda/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -lpython3.6m -o build/lib.linux-x86_64-3.6/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/deform_pool_kernel_cuda.o：没有那个文件或目录
> g++: 错误：/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/build/temp.linux-x86_64-3.6/home/admin/PVDefect/maskrcnn_box/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.o：没有那个文件或目录
> error: command 'g++' failed with exit status 1

可以请教一下你是怎么解决这个问题的吗？我也出现了同样的问题。

**Comment by pzy441** [comment]
May I ask how to solve this problem？
