### ISSUE TITLE
Can mAP be calculated per class for multiple classes on COCO or custom dataset?

### ISSUE THREAD

**Issue by Eldad27** [facebookresearch/maskrcnn-benchmark#1283]
Inference result (mAP) for COCO dataset is typically reported for all classes. I stand to be corrected if I'm wrong. Can you please guide me on the procedure to produce the mAP per class on either COCO or custom dataset for Mask RCNN?

I successfully trained Mask RCNN (R-50 FPN) on a custom dataset of 2 classes. During the evaluation, inference results display one AP for detection (Bbox) results and another for segmentation results (Segm), which I assume represents mAP for my two classes combined. How can I display mAP for each specific class (class specific mAP)? Is this possible? Please help.

**Comment by jpainam** [comment]
@sotte any comment on this issue? I'm also confronted with the problem. Is there any command for producing mAP for each class?

**Comment by SkeletonOne** [comment]
#524
