### ISSUE TITLE
'ImageList' object is not iterable

### ISSUE THREAD

**Issue by linpeisensh** [facebookresearch/maskrcnn-benchmark#1289]
## ❓ Questions and Help
Thank you for your excellent work!
When I try to run your shapes_dataset_demo.ipynb, there is an error. The training process is fine.
![image](https://user-images.githubusercontent.com/52672986/100802183-54721c00-3429-11eb-8a87-59e18cabbfb1.png)
Could someone tell me why and how to fix it.
Thank you in advance!

**Comment by CaySue** [comment]
I have the same problem as you, had you fixed it yet? please help me !
