### ISSUE TITLE
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu:297

### ISSUE THREAD

**Issue by liqiangniu** [facebookresearch/maskrcnn-benchmark#1314]
PyTorch version: 1.4.0+cu100
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 450.80.02
cuDNN version: Could not collect

**Comment by liqiangniu** [comment]
GPU version
NVIDIA-SMI 430.46       Driver Version: 440.64.00    CUDA Version: 10.2

**Comment by Zhuobear** [comment]
> PyTorch 版本：1.4.0+cu100
> 是否調試構建：沒有
> 用於構建 PyTorch 的 CUDA：10.0
> 
> 操作系統：Ubuntu 16.04.6 LTS
> GCC 版本：(Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> CMake 版本：無法收集
> 
> Python 版本：3.7
> CUDA 是否可用：是
> CUDA 運行時版本：無法收集
> GPU 模型和配置：GPU 0：Tesla V100-SXM2-32GB
> Nvidia 驅動程序版本：450.80.02
> cuDNN 版本：無法收集

**Comment by liqiangniu** [comment]
fixed!

**Comment by zhangyichent** [comment]
How did you solve it？

**Comment by MeinhardMark** [comment]
> PyTorch version: 1.4.0+cu100 Is debug build: No CUDA used to build PyTorch: 10.0
> 
> OS: Ubuntu 16.04.6 LTS GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609 CMake version: Could not collect
> 
> Python version: 3.7 Is CUDA available: Yes CUDA runtime version: Could not collect GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB Nvidia driver version: 450.80.02 cuDNN version: Could not collect

How did you solve this?
