### ISSUE TITLE
How to install pytorch-nightly 1.0 ?

### ISSUE THREAD

**Issue by nanzh-19** [facebookresearch/maskrcnn-benchmark#1317]
## ❓ Questions and Help
Step 16/23 : RUN conda install pytorch-nightly cudatoolkit=${CUDA}   && conda clean -ya
 ---> Running in 030eca041397
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-nightly

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

The command '/bin/sh -c conda install pytorch-nightly cudatoolkit=${CUDA}   && conda clean -ya' returned a non-zero code: 1

And I can not find pytorch-nightly 1.0 for linux on https://anaconda.org, can anybody give me some advice if you know ? Thank you in advance!

**Comment by Park-ing-lot** [comment]
Me too. Help please

**Comment by LeviViana** [comment]
This issue doesn't seem related to this repo. But, here are some tips:

- Refer to [the official site](https://pytorch.org/) for installation guidance.
- The command should look a little more like `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch-nightly`

**Comment by nanzh-19** [comment]
I fixed it. You can install pytorch 1.2.0 (stable), it will also work.
