### ISSUE TITLE
build problem.

### ISSUE THREAD

**Issue by jiangtaoo2333** [facebookresearch/maskrcnn-benchmark#132]
## ❓ Questions and Help
unable to execute '/usr/local/cuda:/bin/nvcc': No such file or directory
error: command '/usr/local/cuda:/bin/nvcc' failed with exit status 1

thanks for u code. need your help

**Comment by jiangtaoo2333** [comment]
> Hi,
> 
> Make sure that you have the cuda toolkit and the cuda drivers properly installed in your system. You are missing the nvcc compiler, which is the nvidia compiler for cuda programs.

jiangtao@jiangtao:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

thanks for your help. does it means i already have nvcc?

**Comment by jiangtaoo2333** [comment]
running build
running build_py
running build_ext
/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py:182: UserWarning: Error checking compiler version for g++: a bytes-like object is required, not 'str'
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'maskrcnn_benchmark._C' extension
gcc -pthread -B /home/jiangtao/anaconda2/envs/Pytorch1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda:/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/include/python3.6m -c /home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/jiangtao/anaconda2/envs/Pytorch1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda:/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/include/python3.6m -c /home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp -o build/temp.linux-x86_64-3.6/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/jiangtao/anaconda2/envs/Pytorch1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda:/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/include/python3.6m -c /home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp -o build/temp.linux-x86_64-3.6/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda:/bin/nvcc -DWITH_CUDA -I/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/jiangtao/anaconda2/envs/Pytorch1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda:/include -I/home/jiangtao/anaconda2/envs/Pytorch1.0/include/python3.6m -c /home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.cu -o build/temp.linux-x86_64-3.6/home/jiangtao/github/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute '/usr/local/cuda:/bin/nvcc': No such file or directory
error: command '/usr/local/cuda:/bin/nvcc' failed with exit status 1

**Comment by fmassa** [comment]
I think I see the issue:
your `CUDA_HOME` environment variable has a trailing `:` in the end `/usr/local/cuda:` instead of `/usr/local/cuda`.
Can you try modifying it to match what I mentioned?

**Comment by jiangtaoo2333** [comment]
> I think I see the issue:
> your `CUDA_HOME` environment variable has a trailing `:` in the end `/usr/local/cuda:` instead of `/usr/local/cuda`.
> Can you try modifying it to match what I mentioned?
thanks for your help sincere.
i have changed 
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda:$CUDA_HOME
to
export LD_LIBRARY_PATH=/usr/local/cuda/lib64
export CUDA_HOME=/usr/local/cuda. build completed.

**Comment by fmassa** [comment]
Great!
I'm closing the issue, but let us know if you face other problems.
