### ISSUE TITLE
Image type question

### ISSUE THREAD

**Issue by ChenjieXu** [facebookresearch/maskrcnn-benchmark#133]
There is difference between images opened by PIL and openCV. In instruction of building our own dataset, it says load image as PIL images. But in coco_demo.run_on_opencv_image and webcam demo, they are loaded as cv2 images. Which type should I use when I build my own dataset? 

## Environment

PyTorch version: 1.0.0a0+02d3787
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.0.0a0+02d3787           <pip>

**Comment by fmassa** [comment]
Hi,

I would say that you should just use PIL to load the images in your dataset when doing training / inference.
The necessary image conversions have already been done in the transforms that have been provided, so you should be good to go.

Let me know if you have further questions.

**Comment by prafulag** [comment]
@fmassa: what if my image pixel ranges in float 32 bit format ?
PIL does not support the 3 channel image for this type. Any thoughts?
