### ISSUE TITLE
Mask Rcnn is too slow in Google Colab

### ISSUE THREAD

**Issue by hasanhut** [facebookresearch/maskrcnn-benchmark#1349]
Hello, I am using google colab pro and when I want to train a model with mask rcnn, 1 epoch takes about 45 minutes. This time has nothing to do with the dataset because it takes 45 minutes with a dataset of 150 images and 45 minutes with a dataset of 3000 images. What is the reason?

**Comment by kent252** [comment]
> Hello, I am using google colab pro and when I want to train a model with mask rcnn, 1 epoch takes about 45 minutes. This time has nothing to do with the dataset because it takes 45 minutes with a dataset of 150 images and 45 minutes with a dataset of 3000 images. What is the reason?

I'm a newbie in colab. Could you provide me the command to run it on colab, I have a problem with cuda 11 and apex. Thank you.
