### ISSUE TITLE
[Tutorial] Conda + gcc5 on Ubuntu 14.04

### ISSUE THREAD

**Issue by jinyu121** [facebookresearch/maskrcnn-benchmark#135]
## ❓ Questions and Help

Well, I have a server with Ubuntu 14.04, whose `gcc` is 4.8.X. Hey, it is 2018 now, the latest version is 18.10, and we are using Ubuntu 14.04, without `sudo`.

After some tries, here is a short tutorial.

```
conda create --name maskrcnn-benchmark
conda activate maskrcnn-benchmark

conda install gcc-5 gcc-5-mp -c psi4
conda install ipython ninja cython matplotlib
conda install pytorch-nightly torchvision -c pytorch 
pip install yacs pycocotools 

git clone https://github.com/facebookresearch/maskrcnn-benchmark.git
cd maskrcnn-benchmark
```

Then, open `setup.py`, add `extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']` in `ext_modules`>`extension`, so this section will like

```
    ext_modules = [
        extension(
            "maskrcnn_benchmark._C",
            sources,
            include_dirs=include_dirs,
            define_macros=define_macros,
            extra_compile_args=extra_compile_args,
            extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']  # Yes~ I am here
        )
    ]
```

Finally, 

```
python setup.py build develop
```

and have fun.

**Comment by fmassa** [comment]
Thanks for the information!

We have included in the `TROUBLESHOOTING` section of the README a part that mentions [how to install a newest version of gcc](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/TROUBLESHOOTING.md#segmentation-fault-core-dumped-when-running-the-library).

Let us know if we could improve the documentation with further information.
