### ISSUE TITLE
Inference on new data set model

### ISSUE THREAD

**Issue by bradasteiner** [facebookresearch/maskrcnn-benchmark#136]
## ❓ Questions and Help
What modifications should be made to the inference example in order to use a model trained on a new dataset? I trained a model using my own data and have multiple *.pth models created, but I don't see anywhere in the inference example config yaml to point to a .pth model. Thanks

**Comment by fmassa** [comment]
Hi,

You can perform inference on your new model by changing the `MODEL.WEIGHT` argument in the config to point to your trained model. You can for example use the command-line overrides for that:
```
python tools/test_net.py --config-file path_to_your_cfg.yaml MODEL.WEIGHT path/to/your/model.pth
```

I'm closing this issue, but let us know if you have more questions;
