### ISSUE TITLE
ClobberError: The package 'defaults::ninja-1.8.2-py37h6bb024c_1' cannot be installed due to a path collision for 'bin/ninja'.

### ISSUE THREAD

**Issue by zhang11wu4** [facebookresearch/maskrcnn-benchmark#148]
## ❓ Questions and Help
when I run "conda install pytorch-nightly -c pytorch", I encounter following error, who can help me to fix it? Thanks!

_Solving environment: done

## Package Plan ##

  environment location: /home/ab/anaconda2/envs/maskrcnn_benchmark

  added / updated specs: 
    - pytorch-nightly

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.15.4               |   py37h1d66e8a_0          35 KB
    blas-1.0                   |              mkl           6 KB
    ------------------------------------------------------------
                                           Total:          41 KB

The following NEW packages will be INSTALLED:

    blas:            1.0-mkl                                                 
    cffi:            1.11.5-py37he75722e_1                                   
    intel-openmp:    2019.0-118                                              
    libgfortran-ng:  7.3.0-hdf63c60_0                                        
    mkl:             2019.0-118                                              
    mkl_fft:         1.0.6-py37h7dd41cf_0                                    
    mkl_random:      1.0.1-py37h4414c95_1                                    
    ninja:           1.8.2-py37h6bb024c_1                                    
    numpy:           1.15.4-py37h1d66e8a_0                                   
    numpy-base:      1.15.4-py37h81de0dd_0                                   
    pycparser:       2.19-py37_0                                             
    pytorch-nightly: 1.0.0.dev20181112-py3.7_cuda9.0.176_cudnn7.1.2_0 pytorch

Proceed ([y]/n)? y

Downloading and Extracting Packages
numpy-1.15.4         | 35 KB     | ##################################### | 100% 
blas-1.0             | 6 KB      | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: - 
SafetyError: The package for pytorch-nightly located at /home/ab/anaconda2/pkgs/pytorch-nightly-1.0.0.dev20181112-py3.7_cuda9.0.176_cudnn7.1.2_0
appears to be corrupted. The path 'lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so'
has a sha256 mismatch.
  reported sha256: fcc2691c7495fbfa4876ef39cb6033d7a5218f517e12c7ae9875a701bd76815f
  actual sha256: b723c6a9c30573142041eda789ee82476ba595bdbfad484929569a23167bfc9a

ClobberError: The package 'defaults::ninja-1.8.2-py37h6bb024c_1' cannot be installed due to a
path collision for 'bin/ninja'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.

ClobberError: The package 'defaults::numpy-base-1.15.4-py37h81de0dd_0' cannot be installed due to a
path collision for 'bin/f2py'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.

ClobberError: The package 'defaults::numpy-base-1.15.4-py37h81de0dd_0' cannot be installed due to a
path collision for 'lib/python3.7/site-packages/numpy/LICENSE.txt'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.
...(there are so many similar errors)
done
Executing transaction: done_

**Comment by fmassa** [comment]
Hi,

This is a conflict in your system, probably because you already have ninja installed globally in the system, and that is conflicting with conda.

I'd try cleaning up your global ninja install, and then trying installing again with conda.

I'm closing this issue as it's not a problem with `maskrcnn-benchmark`, but let me know if you have further questions.
