### ISSUE TITLE
Training on my own dataset

### ISSUE THREAD

**Issue by BelhalK** [facebookresearch/maskrcnn-benchmark#159]
## ❓ Questions and Help

I am trying to train this mask-RCNN on my own dataset with only one class (not a class of COCO though)
I used the VGG Annotator to annotate my data. The json file are thus coherent with COCO style.
As a result, I am wondering if I could train this mask r-cnn on my dataset (where the folders are correctly named after looking at `maskrcnn_benchmark/config/paths_catalog.py` using the following command: 
`python tools/train_net.py --config-file "configs/caffe2/e2e_mask_rcnn_R_50_FPN_1x_caffe2.yaml"`

Let me know if I'm missing something.
Thank you very much

**Comment by fmassa** [comment]
Have a look at https://github.com/facebookresearch/maskrcnn-benchmark/issues/15 if you want to start from a pre-trained detection model.

You'll need to override some arguments in the config, like the number of classes and (maybe) the dataset names.
Apart from that and the things discussed in the aforementioned issue, everything should work ok.

I'm closing this issue because I think that I've answered your question, but let me know if you have further questions.

**Comment by BelhalK** [comment]
Great thanks I will have a look.
So you're saying that this should work even with a new class (a class my pre-trained model has never been trained on before)?
If yes, then that's what I needed.
Thanks @fmassa !

**Comment by fmassa** [comment]
Yes, you'll need training and you will need to follow one of the steps in that were discussed in #15, but this should work fine.

**Comment by fmassa** [comment]
It depends if your dataset is in COCO-style or not.

This PR shows how to add an entirely new dataset (and evaluation functions)
https://github.com/facebookresearch/maskrcnn-benchmark/pull/207

About the `caffe2` config files being empty, I just focused on adding them for evaluation, and not for training. You can add the remaining bits from the `config/e2e_mask_rcnn_X_101_32x8d_FPN_1x.yaml` file, or just use it straight away (by passing the path to the pre-trained models from caffe2)

**Comment by BelhalK** [comment]
Yes I made sure my training set is in COCO style and that the structure is as in patahs_catalog.py
Indeed using the config file you suggested is better.
For the rest I will look at the PR.
Thank you.

**Comment by fmassa** [comment]
Note that the PR I sent is doing way more than what you need, because it also adds a Python implementation and evaluation.
You basically need to change the `paths_catalog.py` file.

**Comment by BelhalK** [comment]
The thing is I make sure that my floder architecture follows the unchanged paths_catalog.py file as follows 
```
DATASETS = {
        "coco_2014_train": (
            "coco/train2014",
            "coco/annotations/instances_train2014.json",
        ),
        "coco_2014_val": ("coco/val2014", "coco/annotations/instances_val2014.json"),
        "coco_2014_minival": (
            "coco/val2014",
            "coco/annotations/instances_minival2014.json",
        ),
        "coco_2014_valminusminival": (
            "coco/val2014",
            "coco/annotations/instances_valminusminival2014.json",
        ),
    }
```

So I believe I don't need any changes on that file.
And since I am training on my own COC-style dataset that has two classes 0 and 1, all the modifications I need to make will be made to the config and model files (num_casses, dataset['categories'] etc..) don't you agree?

**Comment by Shahdate** [comment]
Hi,
I got the following error in step 2 when trained coco dataset with Maskrcnn_Benchmark model. Any suggestion please.

v: i + 1 for i, v in enumerate(self.coco.getCatIds())
File "/home/zst19phu/anaconda3/envs/ptorch/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 170, in getCatIds
cats = self.dataset['categories']
KeyError: 'categories'

The error is in Step-2, Pycoco tools is not finding the catgories from the annotation file provided. Anyone else face the similar problem, if yes, what is the solution please?

Thank you.
