### ISSUE TITLE
Train on Open Images Dataset

### ISSUE THREAD

**Issue by sophia-wright-blue** [facebookresearch/maskrcnn-benchmark#161]
## ❓ Questions and Help

Would it be possible to train this model on the Open Images Dataset (https://storage.googleapis.com/openimages/web/factsfigures.html) ?

If yes, I'd greatly appreciate any guidance on the steps to do so.

thanks,

**Comment by fmassa** [comment]
Hi,

If you want to finetune from a pre-trained detection model, you could have a look at https://github.com/facebookresearch/maskrcnn-benchmark/issues/15

If you want to start from an ImageNet pre-trained model, basically all you need to do is to write your Dataset class (following the COCODataset for example) and change the number of classes.

It should be fairly simple. Let me know if you have more precise questions.

**Comment by sophia-wright-blue** [comment]
thanks for the quick reply @fmassa , i'll get started on this and get back to you if I hit any roadblocks,
