### ISSUE TITLE
Can this run on CUDA 8.0 ?

### ISSUE THREAD

**Issue by Meraing** [facebookresearch/maskrcnn-benchmark#173]
I run "webcam.py": 
AssertionError: 
The NVIDIA driver on your system is too old (found version 6050).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

I have two nvidia gpu, but only install one driver, another one is unknown model.
Quadro FX580 nvidia driver version 340

torch 1.0.0.dev20181108
Cuda compilation tools, release 8.0, V8.0.61

**Comment by fmassa** [comment]
It is possible to run on CUDA 8.0, but you might need to update your driver.

Also, you'd need to see if both GPUs can work with the same driver, which might not be the case if one of the GPUs is very old.
