### ISSUE TITLE
Any more fast base network? Currently only 2 fps on GTX1080 which is really slow.

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/maskrcnn-benchmark#186]
MaskRCNN has only 2 fps and need 500-600ms per img on GTX 1080ti. Does there any further action can be take to accelerate the speed of maskrcnn?

**Comment by fmassa** [comment]
Hi,

This is related to https://github.com/facebookresearch/maskrcnn-benchmark/issues/42

I'd like to add a `MobileNet` backbone, which will make the models run significantly faster.
But I still need to train models with this backbone, and it might still take a few weeks before I can release something.

But contributions are more than welcome!

Let's keep the discussion in #42
