### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by steve-goley** [facebookresearch/maskrcnn-benchmark#189]
## ❓ Questions and Help
Is there a preferred method to cite this work? Who are the authors?

**Comment by fmassa** [comment]
Hi @steve-goley ,

We will get back to you shortly with more info on that.

**Comment by fmassa** [comment]
@steve-goley a bibtex has been added in https://github.com/facebookresearch/maskrcnn-benchmark/pull/193

Let me know if you have further questions
