### ISSUE TITLE
small typo in demo instruction

### ISSUE THREAD

**Issue by macfly1202** [facebookresearch/maskrcnn-benchmark#19]
## ❓ Questions and Help
There is a small typo in demo instruction sample command line : 
correct launch is done with: 
```python webcam.py --config-file ../configs/caffe2/e2e_mask_rcnn_R_101_FPN_1x_caffe2.yaml --min-image-size 300 MODEL.DEVICE cpu```
and not like written in https://github.com/facebookresearch/maskrcnn-benchmark with : 
```python webcam.py --config-file ../configs/caffe2/e2e_mask_rcnn_R_101_FPN_1x_caffe2.py --min-image-size 300 MODEL.DEVICE cpu```

Thanks for such amazing performance !

**Comment by fmassa** [comment]
Oh, thanks for catching that up, it took me some time to spot the difference :-)
Could you please send a PR fixing the instructions?

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/20
