### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by markaustinbrophy** [facebookresearch/maskrcnn-benchmark#190]
## ❓ Questions and Help
Firstly, thank you for this wonderful library; it's very intuitive and easy to get started with.

There's a pattern that exists throughout the entire codebase, like for example in roi_heads.py, where there is a method called _build_roi_heads_ that is responsible for constructing the instance of CombinedROIHeads. Is there a standard name for this type of design? I'd like to read more about it.

Thanks again,
Mark

**Comment by fmassa** [comment]
Hi,

Thanks for your feedback!

I believe this pattern is called [builder pattern, see here for some more information](https://en.wikipedia.org/wiki/Builder_pattern).

Let me know if you have further questions!

**Comment by markaustinbrophy** [comment]
Thank you kindly.
