### ISSUE TITLE
Segmentation fault (core dumped) during training

### ISSUE THREAD

**Issue by Mikarnival** [facebookresearch/maskrcnn-benchmark#194]
## ❓ Questions and Help
Hi again,

The code works perfect with webcam. But when I try to train with coco dataset, I get segmentation fault, as showing below. I use single GPU. The GPU of my working notebook is not good. Is the small GPU the problem? Thank you!

I. System environment:

`2018-11-21 10:20:26,515 maskrcnn_benchmark INFO: Collecting env info (might take some time)
2018-11-21 10:20:28,013 maskrcnn_benchmark INFO: 
PyTorch version: 1.0.0.dev20181113
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.5 LTS
GCC version: (GCC) 5.2.0
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 390.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] pytorch-nightly           1.0.0.dev20181113 py3.6_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch
        Pillow (5.3.0)
`
II. Part of the response when trainning:

`2018-11-21 10:22:42,559 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.2.conv3.weight               loaded from layer4.2.conv3.weight        of shape (2048, 512, 1, 1)
2018-11-21 10:22:42,559 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.bn1.bias                       loaded from bn1.bias                     of shape (64,)
2018-11-21 10:22:42,559 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.bn1.weight                     loaded from bn1.weight                   of shape (64,)
2018-11-21 10:22:42,559 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.conv1.weight                   loaded from conv1.weight                 of shape (64, 3, 7, 7)
Segmentation fault (core dumped)
`

**Comment by fmassa** [comment]
Hi,

It seems that you have CUDA 7.5 in your system, but you installed a PyTorch nightly from CUDA 8.0.
Maybe that's the issue? Can you try upgrading your CUDA?

**Comment by Mikarnival** [comment]
Hi,

Thank you for your answering. This problem was solved. Actually, I installed cuda-8.0.61 in my computer, but I forget to build the path. 

Now everything works fine. Thank you again! :)
