### ISSUE TITLE
Pycharm configuration - multi GPU training

### ISSUE THREAD

**Issue by barakhi** [facebookresearch/maskrcnn-benchmark#199]
## ❓ Questions and Help
Hi, 
I'm trying to run multi-GPU training in Pycharm and can't figure out how to configure my run.
I've tried:
Module name (instead of script path): torch.distributed.launch
Parameters: --nproc_per_node=2 tools/train_net.py --config-file ...
with sum variations and with no success.

How should I configure my run ?
Thanks

**Comment by miguelvr** [comment]
Here you go

![image](https://user-images.githubusercontent.com/7456627/48898813-0bf0f280-ee4e-11e8-9717-119caa4ba50c.png)

**Comment by fmassa** [comment]
Closing thanks to @miguelvr suggestion

**Comment by barakhi** [comment]
Hi, 
I tried Miguel's suggestion - but got:
"No module named tools/train_net.py"
![image](https://user-images.githubusercontent.com/23358711/48942792-9c503580-ef29-11e8-93a4-b86d4eafa89b.png)

Have I missed anything?

Thanks,

**Comment by miguelvr** [comment]
`tools/train.net` is not a module so you are not filling the correct fields

**Comment by barakhi** [comment]
This is my config:
![image](https://user-images.githubusercontent.com/23358711/48942956-3b752d00-ef2a-11e8-8b23-1a113c03cfda.png)
Where is my mistake? Can't find it

**Comment by miguelvr** [comment]
that indeed looks ok... can you show me the output of the terminal?

**Comment by barakhi** [comment]
It is working well from the terminal. 
When I'm trying to run the configuration - It is also working.
The problem only occurs while debugging the configuration. 
I don't understand the reason, but I guess it's a question to PyCharm - not to you.
Thanks, anyway

**Comment by miguelvr** [comment]
you are better off debugging with a single GPU, because torch.launch.distributed is spawning multiple processes. Not sure if pycharm can handle that
