### ISSUE TITLE
Whether need to -1 for Pascal VOC bbox index

### ISSUE THREAD

**Issue by xuw080** [facebookresearch/maskrcnn-benchmark#210]
Because Pascal VOC is labeled using 1-based index and MS-COCO is 0-based index, I am not sure whether you need to -1 when loading annotation bbox from Pascal VOC .xml file?( 
https://github.com/facebookresearch/maskrcnn-benchmark/blob/9a1ba140c8d8294f23b0a28a87bffd09d7b1adbe/maskrcnn_benchmark/data/datasets/voc.py#L100-L104)

**Comment by fmassa** [comment]
Yes, this is a bug in the code and there is an open PR to fix it. Thanks for raising up this issue!

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/209
