### ISSUE TITLE
FPN missing last scale-specific conv layers.

### ISSUE THREAD

**Issue by thangvubk** [facebookresearch/maskrcnn-benchmark#212]
I found that FPN is missing the last scale-specific convolutional layers as in [Dectectron](https://github.com/facebookresearch/Detectron/blob/8170b25b425967f8f1c7d715bea3c5b8d9536cd8/detectron/modeling/FPN.py#L186).

Is this a mistake or an intentional implementation?

**Comment by fmassa** [comment]
I believe this is implemented in [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fpn.py#L31), isn't it?

Also, our implementation is able to read Detectron pre-trained models, so it should at least match all the parameters from Detectron for the tested configurations.

**Comment by thangvubk** [comment]
Thank you for your information.

**Comment by fmassa** [comment]
Cool, let me know if you have further questions, or if I'm missing something
