### ISSUE TITLE
 No module named maskrcnn_benchmark.config

### ISSUE THREAD

**Issue by yaoliUoA** [facebookresearch/maskrcnn-benchmark#22]
## ❓ Questions and Help
Hi
I have followed the instructions to install this package. However, when I run the notebook demo under './demo', it gives an error: 

`ImportError: No module named maskrcnn_benchmark.config`.

**Comment by Kongsea** [comment]
Use python 3.x.

**Comment by jiapei100** [comment]
@Kongsea 
I've got the same ERROR message, but I'm using python 3.6.6

```
$ python --version
Python 3.6.6
```

Any other suggestions?

**Comment by yaoliUoA** [comment]
@jiapei100 I found the solution. You need to create an empty `__init__.py` under the folder "maskrcnn_benchmark".

**Comment by moyans** [comment]
Traceback (most recent call last):
  File "webcam.py", line 6, in <module>
    from predictor import COCODemo
  File "/data/Data/HeiRen/code/maskrcnn-benchmark/demo/predictor.py", line 7, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/data/Data/HeiRen/code/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 7, in <module>
    from maskrcnn_benchmark.utils.model_serialization import load_state_dict
  File "/data/Data/HeiRen/code/maskrcnn-benchmark/maskrcnn_benchmark/utils/model_serialization.py", line 7, in <module>
    from maskrcnn_benchmark.utils.imports import import_file
  File "/data/Data/HeiRen/code/maskrcnn-benchmark/maskrcnn_benchmark/utils/imports.py", line 3, in <module>
    import importlib.util
ImportError: No module named util

**Comment by fmassa** [comment]
I am adding support for Python 2 in https://github.com/facebookresearch/maskrcnn-benchmark/pull/11 and it should fix the errors you are seeing.

I'll verify that the training that I launched yesterday matches the excepted accuracies and I'll merge it

**Comment by fmassa** [comment]
For info, I've just merged https://github.com/facebookresearch/maskrcnn-benchmark/pull/11 , so the codebase should work with Python 2 as well.

**Comment by fmassa** [comment]
Let me know if you still face problems after pulling from latest version of maskrcnn-benchmark

**Comment by fmassa** [comment]
yes, I've improved the documentation to add the `source activate maskrcnn_benchmark` after creating the environemnt

**Comment by jiapei100** [comment]
@fmassa 
Nope... I didn't use **conda** at all....

@yaoliUoA 
I've added __init__.py under the folder **maskrcnn_benchmark**, but the **ERROR** continues....

**Comment by fmassa** [comment]
Make sure that the installation wmis done properly 
Also, pull from latest master, I've fixed the missing `__init__.py` files 

As a note, having conda is a very easy and simple way of managing several python environments, and I'd highly recommend it.

**Comment by moyans** [comment]
when i use 3.x python with conda, every thing is all right.

**Comment by Kongsea** [comment]
@moyans me too.

**Comment by fmassa** [comment]
We now support python2 as well, so if it wasn't working before with Python 2, now it should be.

**Comment by Maosef** [comment]
I had the same issue, trying this link helped: https://github.com/jupyter/notebook/issues/1524

**Comment by kira0992** [comment]
@fmassa  I pulled recently from the latest master, but I still get No module found errors when I try using a python 2 conda environment, everything works fine if I switch back to my python 3.x environment
