### ISSUE TITLE
ImportError: ../maskrcnn_benchmark/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEl

### ISSUE THREAD

**Issue by ypxie** [facebookresearch/maskrcnn-benchmark#225]
## ❓ Questions and Help
python 3.5
pytorch 0.4.1
cuda 9.0

**Comment by fmassa** [comment]
`maskrcnn-benchmark` only works with PyTorch 1.0.
Try updating your PyTorch installation and the error should disappear.
