### ISSUE TITLE
from .nms import nms

### ISSUE THREAD

**Issue by zhosteven** [facebookresearch/maskrcnn-benchmark#23]
## ❓ Questions and Help
```
  File "/home/idea/model/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C'
```

`python3 demo/webcam.py --min-image-size 800`

**Comment by fmassa** [comment]
Hi,

Yes, there will be a conflict between pytorch version 0.4.1 and pytorch 1.0.
I'd recommend creating a new conda environment, as illustrated in the INSTALL.md file. This will make sure that there are no conflicts.

**Comment by zhosteven** [comment]
Thank you ,I  got it .
