### ISSUE TITLE
how to apply "dilation" in Resnet backbone?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [facebookresearch/maskrcnn-benchmark#236]
i find that `_C.MODEL.RESNETS.RES5_DILATION` is not used in building the Resnet backbone, so how to apply `dilation` in Resnet backbone?

**Comment by fmassa** [comment]
We have currently not exposed dilation in the models I believe.
It would require plugging it in the necessary places, for example following what has been [done in Detectron](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/ResNet.py)

**Comment by zimenglan-sysu-512** [comment]
thanks @fmassa

**Comment by zimenglan-sysu-512** [comment]
hi @fmassa 
it's wired that after adding dilation for C5, the runing procedure is too slow. it seems that pytorch 1.0 is not friendly to astrous conv.  
btw, have u met this problem?

**Comment by fmassa** [comment]
There have been some reports that dilated convolutions became a bit slower in latest versions of PyTorch.
But it's worth noting that dilated convolutions usually mean larger feature maps, which implies larger memory footprint and more computations

**Comment by ShihuaiXu** [comment]
Hello @zimenglan-sysu-512 我也是中国的大学生，请问您能把您加了空洞卷积的代码 发一下我邮箱吗 我想学习一下 谢谢您 我的邮箱是531232693@qq.com
