### ISSUE TITLE
Converting e2e_faster_rcnn_X_101_32x8d_FPN_1x_caffe2.pkl to protobuf

### ISSUE THREAD

**Issue by karanchawla** [facebookresearch/maskrcnn-benchmark#24]
## ❓ Questions and Help
Do we use the Detectron's script to convert the pkl config files to protobuf for C++ deployment? 

I'm getting the following error when I try to convert the aforementioned file using that python script: 
```
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by fmassa** [comment]
Hi,

Could you expand on what you are trying to do?
It's not very clear to me.

Thanks!

**Comment by fmassa** [comment]
Hi,

If you want to use Detectron for C++ deployment, you should ask your questions in https://github.com/facebookresearch/Detectron, as they will be in a better position to help you.

That being said, I will at some point add support for exporting PyTorch models into C++ using new functionality from PyTorch 1.0. But it might still take a few weeks for that.

Given that this doesn't look like a question / issue with `maskrcnn-benchmark`, I'm closing this issue.

**Comment by fmassa** [comment]
Hi,

I indeed misunderstood your question.

I'll be looking into supporting jit tracing in the future. This will probably involve modifying the way I use C++ extensions.
This means that it will be possible to have `maskrcnn-benchmark` running in standalone C++ apps.

I can send you some pointers on how to approach that, but I don't have all the answers ahead of time, and there might be some subtle issues that might require some digging.

I'm currently tracking this issue in https://github.com/facebookresearch/maskrcnn-benchmark/issues/27, so to avoid duplicates I'll be closing this issue. Let's continue the discussion there.
