### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by shayxurui** [facebookresearch/maskrcnn-benchmark#253]
## ❓ Questions and Help
thanks for sharing code. and when i train on COCO2014 dataset,i meet such error:
 [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_valminusminival2014.json'.

**Comment by fmassa** [comment]
You should follow the instructions in the README in order to setup the training / testing dataset paths.

I'm closing the issue, but let me know if you have further questions

**Comment by shayxurui** [comment]
i solve this problem by changing  th e file name of instances_val2014.json to instances_valminusminival2014.json.

**Comment by shayxurui** [comment]
hi , when i test fasterrcnn net using pretrained model ,and the result is look this 
![prediction_dog](https://user-images.githubusercontent.com/30276311/49681026-4c02d700-fad6-11e8-913f-8ee1beb74b3f.jpg)
![prediction](https://user-images.githubusercontent.com/30276311/49681029-545b1200-fad6-11e8-977d-1f745cc178d8.jpg)
why there are some star in the bounding box?

**Comment by fmassa** [comment]
There is definitely a problem with the model you are using.
What are the commands that you are using? What have you changed from the original implementation?

**Comment by shayxurui** [comment]
i just want to test a detection net,so i test the picture to pass the faster r cnn instead of mask r cnn ,
and modify 
config_file = "../configs/caffe2/e2e_mask_rcnn_R_50_FPN_1x_caffe2.yaml"
to
config_file = "../configs/caffe2/e2e_faster_rcnn_R_50_FPN_1x_caffe2.yaml"

**Comment by fmassa** [comment]
Did you change anything in the config file from faster r-cnn? We normally have a check in [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L177) that doesn't overlay the masks if `MODEL.MASK_ON` is False/

**Comment by rwwneu** [comment]
> ## question Questions and Help
> 
> thanks for sharing code. and when i train on COCO2014 dataset,i meet such error:
> [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_valminusminival2014.json'.

Have you solved this problem？How to slove it? thanks a lot
