### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

### ISSUE THREAD

**Issue by shuxp** [facebookresearch/maskrcnn-benchmark#257]
## ❓ Questions and Help
I installed according 'conda install pytorch-nightly-cpu -c pytorch' (torch-nightly1.0.0.dev20181209), also I installed pytorch stable from official site following "conda install pytorch-cpu torchvision-cpu -c pytorch", but I still found this problem.

c:\users\xp\test\maskrcnn-benchmark\maskrcnn_benchmark\utils\comm.py in is_main_process()
     26 
     27 def is_main_process():
---> 28     if not torch.distributed.is_initialized():
     29         return True
     30     return torch.distributed.get_rank() == 0
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

In my win10 system, my torch is 1.0.0, and 'dir(torch.distributed)' returns

`['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'deprecated', 'is_available', 'torch']`

In my ubuntu system, I installed a GPU version,  torch version is also 1.0.0, and 'dir(torch.distributed)' returns

`['AllgatherOptions', 'AllreduceOptions', 'Backend', 'BarrierOptions', 'BroadcastOptions', 'FileStore', 'GatherOptions', 'GroupMember', 'PrefixStore', 'ProcessGroup', 'ProcessGroupGloo', 'ProcessGroupNCCL', 'ReduceOp', 'ReduceOptions', 'ScatterOptions', 'Store', 'TCPStore', 'Work', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_backend', '_dist_broadcast_coalesced', '_dist_bucket_tensors', '_queue_reduction', '_sync_params', '_sync_reduction', 'all_gather', 'all_gather_multigpu', 'all_reduce', 'all_reduce_multigpu', 'barrier', 'broadcast', 'broadcast_multigpu', 'deprecated', 'destroy_process_group', 'dist_backend', 'distributed_c10d', 'gather', 'get_backend', 'get_rank', 'get_world_size', 'group', 'init_process_group', 'irecv', 'is_available', 'is_initialized', 'is_mpi_available', 'is_nccl_available', 'isend', 'new_group', 'recv', 'reduce', 'reduce_multigpu', 'reduce_op', 'register_rendezvous_handler', 'rendezvous', 'scatter', 'send', 'string_classes', 'timedelta', 'torch', 'warnings']
`

So why this happened, who can help? Many thanks.

**Comment by shuxp** [comment]
It seems on windows, pytorch can't run with distributed mode, however on ubuntu, there are more functions to support distribute trainning. 

So after I comment some functions in utils/comm.py, it runs OK.

Closed.

**Comment by fmassa** [comment]
Thanks for opening the issue!
So you are able to run the cod without problem (including compilation) on Windows 10, after commenting out a few things on the distributed backend?

**Comment by shuxp** [comment]
> Thanks for opening the issue!
> So you are able to run the cod without problem (including compilation) on Windows 10, after commenting out a few things on the distributed backend?

Yes, win10(cpu) + anaconda5.2(python3.6), but inference time is a bit long, 8-9s per image with faster rcnn. Maybe my image is too big (4000*3000) . But  with win10 + tf(cpu) costs 2-3s per image with mobilenet-SSD.

**Comment by fmassa** [comment]
Thanks for the information!
It's not surprising that mobilenet-SSD is faster than Mask R-CNN R-50, given that the base network architecture is much bigger.

**Comment by shuxp** [comment]
> Thanks for the information!
> It's not surprising that mobilenet-SSD is faster than Mask R-CNN R-50, given that the base network architecture is much bigger.

Looking forward to see more official network architecture^_^
