### ISSUE TITLE
Transfer learning freeze layers [clarification]

### ISSUE THREAD

**Issue by Igal20** [facebookresearch/maskrcnn-benchmark#260]

**Comment by Igal20** [comment]
Hello, please I need some clarification about freeze layers following issue [Transfer learning freeze layers #201 ] specially following answer:

> Hi,
By default and for simplicity, we freeze entire resnet stages, see https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/resnet.py#L112-L113 for an example.
You can modify that part of the code to better suit your needs, but if you are ok training the last 9 layers (instead of 10) you can just set FREEZE_CONV_BODY_AT = 3, and you'll train the last two resnet stages, which sums up to 9 layers.

one can fined at mentioned link following:

> ResNet50FPNStagesTo5 = tuple(
    StageSpec(index=i, block_count=c, return_features=r)
    for (i, c, r) in ((1, 3, True), (2, 4, True), (3, 6, True), (4, 3, True))
)

Correct me if I'm wrong in case of :
FREEZE_CONV_BODY_AT = 1  train resnet only 16 last layers
FREEZE_CONV_BODY_AT = 2  train resnet only 13 last layers
FREEZE_CONV_BODY_AT = 3  train resnet only 9 last layers
FREEZE_CONV_BODY_AT = 4  train resnet only 3 last layers

But if I want to taring 25 or 30 last layers what would you recommend me to do ?

**Comment by fmassa** [comment]
In this case, you'll need to be more intrusive in the code-base and modify the layers that you want in [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/resnet.py#L107-L113).
But that means defining an ordering of the layers. Given that resnets have a skip-connection, it's not a straight sequential model, so the ordering is not unique and need to be specified beforehand.

**Comment by fmassa** [comment]
And to be more clear on your question about the layers of resnet, the counting of the "layers" is right, but each layer is composed of a number of convolutions / relu / batch-norm.

**Comment by sshuair** [comment]
@Igal20 If `FREEZE_CONV_BODY_AT = 0`  means no layer will be frozen?
