### ISSUE TITLE
how to load my own trained model to make prediction

### ISSUE THREAD

**Issue by shayxurui** [facebookresearch/maskrcnn-benchmark#262]
## ❓ Questions and Help
i load my trained model pretrained on pascal voc 2012 dataset,but how make predict on my own model???

**Comment by fmassa** [comment]
By prediction, you mean outputting an image with bounding boxes etc?
You can modify the [predictor](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py) for that.
The changes should be minimal, like just changing the [`CATEGORIES`](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L14) by those from Pascal.

If you are instead looking into computing the final evaluation metric, then it's already computed for you in the end of training I believe.

**Comment by shayxurui** [comment]
thanks

**Comment by fmassa** [comment]
Closing as it seems that I've answered your question
