### ISSUE TITLE
error when running with --show-mask-heatmaps

### ISSUE THREAD

**Issue by yewenlong** [facebookresearch/maskrcnn-benchmark#266]
I have no problem when running demo without --show-mask-heatmaps. But error occurs when adding the parameter --show-mask-heatmaps. The output log is as follow:
```
Traceback (most recent call last):
  File "webcam.py", line 80, in <module>
    main()
  File "webcam.py", line 71, in main
    composite = coco_demo.run_on_opencv_image(img)
  File "/home/ywl/dl/maskrcnn-benchmark/demo/predictor.py", line 175, in run_on_opencv_image
    return self.create_mask_montage(result, top_predictions)
  File "/home/ywl/dl/maskrcnn-benchmark/demo/predictor.py", line 311, in create_mask_montage
    masks.float(), scale_factor=1 / masks_per_dim
  File "/home/ywl/.virtualenvs/pymask/lib/python3.5/site-packages/torch/nn/functional.py", line 2437, in interpolate
    return torch._C._nn.upsample_nearest2d(input, _output_size(2))
RuntimeError: invalid argument 2: 4D input tensor expected but got: [0 x 1 x 480 x 640] at /pytorch/aten/src/THNN/generic/SpatialUpSamplingNearest.c:19
```
My enviroment is pytorch preview, python 3.5 and CUDA 9.0. Looking forward to your apply.

**Comment by fmassa** [comment]
Thanks for opening the issue!

The problem happens in [this line](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L310) because there were no predictions in your case.

In order to fix this, can you replace
```python
masks = torch.nn.functional.interpolate(
```
with
```
from maskrcnn_benchmark import layers as L
masks = L.interpolate(
```
and report back?

If this works for you, would you mind sending a PR?

Thanks!

**Comment by yewenlong** [comment]
Thanks very much. That works for me.

**Comment by fmassa** [comment]
Great, can you send a PR with this fix? it would be greatly appreciated!

**Comment by yewenlong** [comment]
I have send a PR. Thanks
