### ISSUE TITLE
The error "segment error" occured then break when training

### ISSUE THREAD

**Issue by LDoubleZhi** [facebookresearch/maskrcnn-benchmark#268]
## ❓ Questions and Help

2018-12-13 16:26:25,967 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.conv1.weight                  loaded from conv1.weight                 of shape (64, 3, 7, 7)
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2018-12-13 16:26:26,296 maskrcnn_benchmark.trainer INFO: Start training
段错误#It means segment error
(maskrcnn_benchmark) [liulinzhi@localhost maskrcnn-benchmark]$

I don't know why? Hope your reply

**Comment by fmassa** [comment]
Can you run your script with gdb?
```
gdb python
> run tools/train_net.py --config-file /path/to/config
```
and then, when it stops, do
```
bt
```
and paste the result here?

Also, what is your system info?

**Comment by LDoubleZhi** [comment]
@fmassa
 PyTorch version: 1.0.0.dev20181212
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 390.77
cuDNN version: Could not collect  

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] mkl                       2019.1                      144    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] pytorch-nightly           1.0.0.dev20181212 py3.6_cuda9.0.176_cudnn7.4.1_0    pytorch
        Pillow (5.2.0)
#my cudnn version is 7.4.1.5

**Comment by LDoubleZhi** [comment]
@fmassa I find the error ：
segfault at b ip 00007f1ed041046c sp 00007ffdbfd3b280 error 6 in _C.cpython-36m-x86_64-linux-gnu.so
the _C.cpython-36m-x86_64-linux-gnu.so is locate in maskrcnn_benchmark/

**Comment by LDoubleZhi** [comment]
Is the gcc(version4.8.5) worked?

**Comment by fmassa** [comment]
@LDoubleZhi your issue is due to gcc 4.8, see https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/TROUBLESHOOTING.md#segmentation-fault-core-dumped-when-running-the-library for more information on how to update gcc in order to fix the problem.

**Comment by LDoubleZhi** [comment]
@fmassa Thanks！

**Comment by lijain** [comment]
请问运行 demo出现段吐核？？
