### ISSUE TITLE
Boxlist's __getitem__ function doesn't work correctly

### ISSUE THREAD

**Issue by MathematicianProgrammer** [facebookresearch/maskrcnn-benchmark#276]
## 🐛 Bug

call the Boxlist's __getitem__ function can cause an error
## To Reproduce

1.create a BoxList instance 
boxList = BoxList(...)
2.call the  __getitem__ function like this : 
boxList[index]

It will cause:
File "/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 24, in __init__
    "bbox should have 2 dimensions, got {}".format(bbox.ndimension())
ValueError: bbox should have 2 dimensions, got 1

## Expected behavior
It can take another BoxList for the bbox[index]

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by MathematicianProgrammer** [comment]
Can  reproduce by 
Add "print(bbox[0])" at the end of the main test in the file "bounding_box"

**Comment by fmassa** [comment]
In order to make things consistent, we enforce that BoxList is always 2d.
If you want to index a single element, you can do something like
```python
boxlist[[0]]
```

**Comment by MathematicianProgrammer** [comment]
Thanks a lot.
I got this.

**Comment by buxpeng** [comment]
> 为了使情况一致，我们强制BoxList始终为2d。
> 如果要为单个元素建立索引，可以执行以下操作
> 
> ```python
> 盒子清单[[ 0 ]]
> ```

hi,I don't understand this boxlist type, I encountered this error,I get this error even if using  boxlist[[0]],Can you help me?thanks!
