### ISSUE TITLE
keypoints branch annotation json files Not Found

### ISSUE THREAD

**Issue by FangYang970206** [facebookresearch/maskrcnn-benchmark#277]
## ❓ Questions and Help
Thanks for sharing code @fmassa , I have a question. In the keypoints branch, I found the keypoints annotation files are different from the COCO dataset annotations. So, where can i get the modified annotation files(`person_keypoints_train2017_train_mod.json`, `person_keypoints_val2017_mod.json`, `person_keypoints_train2017_valminusminival_mod.json`)

**Comment by fmassa** [comment]
They should be available in the COCO website

**Comment by FangYang970206** [comment]
Even though I have downloaded the all annotations file in COCO website and the `minval` and `valminusminval` annotations files in the [Detectron](https://s3-us-west-2.amazonaws.com/detectron/coco/coco_annotations_minival.tgz), I didn't find the three files. Have you ever renamed the three files? @fmassa

**Comment by fmassa** [comment]
@FangYang970206 yes, those files have been renamed by myself (as that is a WIP branch), you should just modify the code in the PR to point to the files that you have downloaded.

**Comment by karenyun** [comment]
Hi @fmassa, I do not find the 'person_keypoints_train2014_train.json' and 'person_keypoints_val2014.json' in the COCO website, do you where can i download them?
Thanks a lot!
