### ISSUE TITLE
Metric Logger bug

### ISSUE THREAD

**Issue by congve1** [facebookresearch/maskrcnn-benchmark#278]
## 🐛 Bug

when getting an attr that does not exists of a metric logger,  an error occurs `type object 'object' has no attribute '__getattr__'`
## To Reproduce

1. get an instance of MetricLogger
2. use `getattr` function to get an attr that does not exits

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux):Windows 10
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version:3.6
 - CUDA/cuDNN version:none
 - GPU models and configuration:none
 - Any other relevant information:

**Comment by fmassa** [comment]
Thanks for the bug report!
It has been fixed in #282.
