### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

### ISSUE THREAD

**Issue by benjaminrwilson** [facebookresearch/maskrcnn-benchmark#280]
## 🐛 Bug

When running the webcam demo on macOS 10.14.1 as so:

`python webcam.py --min-image-size 300 MODEL.DEVICE cpu`

I get the error:

`AttributeError: module 'torch.distributed' has no attribute 'is_initialized'`

## To Reproduce

1. Followed install guide here: https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md
2. Use the following command:

`python webcam.py --min-image-size 300 MODEL.DEVICE cpu`

## Expected behavior

I expect this to run the webcam demo.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0 (nightly)
 - OS (e.g., Linux): macOS 10.14.1
 - How you installed PyTorch (`conda`, `pip`, source): Conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

I fixed this issue by changing all instances of `is_initialized()` to `is_available()` in `maskrcnn-benchmark/maskrcnn_benchmark/utils/comm.py`. I'm not sure if this is what is intended or if I am installing something incorrectly. After making that change, I was able to run the webcam demo.

**Comment by congve1** [comment]
I've got the same error.
You could check what `torch.distributed.is_available()` returns. If `False`, it's obvious that your pytorch version doesn't support distributing training, and the code may face some error

**Comment by fmassa** [comment]
This is weird, and might point up to the fact that there might be a mismatch of PyTorch versions in your system that is conflicting with each other.

**Comment by benjaminrwilson** [comment]
@fmassa I'm using a clean Conda environment -- do you think there could somehow be a weird conflict in the environment?

`conda list` shows `pytorch-nightly` version `1.0.0.dev20181215`

**Comment by fmassa** [comment]
yes, this looks weird, because `torch.distributed.is_initialized()` should exist.
Also, note that `torch.distributed.is_initialized()` is fundamentally different than `torch.distributed.is_available()`.

**Comment by fmassa** [comment]
Oh, I see.

A fix would be to guard all occurrences of our distributed functions with a `distributed.is_available()` just before.

For example, in
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/utils/comm.py#L16
replace it with
```
if not torch.distributed.is_available():
    return 1
if not torch.distributed.is_initialized():
    return 1
```
and so on

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/287

**Comment by apacha** [comment]
I'm afraid, that there is one occurence, you've missed: https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/engine/inference.py#L68

It could be fixed by writing:
```
if torch.distributed.is_available():
    num_devices = (
        torch.distributed.get_world_size()
        if torch.distributed.is_initialized()
        else 1
    )
else:
    num_devices = 1
```

**Comment by fmassa** [comment]
@apacha good catch! Could you send a PR fixing it?

Maybe a better solution would be to use https://github.com/facebookresearch/maskrcnn-benchmark/blob/1818bb2f457c082dfd3759e6331e40f97d3059c7/maskrcnn_benchmark/utils/comm.py#L13-L18
