### ISSUE TITLE
bug in GPU code for NMS

### ISSUE THREAD

**Issue by aosokin** [facebookresearch/maskrcnn-benchmark#289]
## 🐛 Bug

GPU implementation of NMS seems to be broken

## To Reproduce

```
from maskrcnn_benchmark.layers import nms as nms
import torch

bbox = torch.tensor([[ 7.0,    0.0000, 12.0,  63.0],
                     [ 7.0,    0.0000, 12.0,  65.0]], device='cuda:0')

scores = torch.tensor([0.0, 1.0], device='cuda:0')
nms_iou_threshold = 0.3

print( 'GPU:', nms(bbox, scores, nms_iou_threshold) )
print( 'CPU:', nms(bbox.cpu(), scores.cpu(), nms_iou_threshold) )
```
I see the following output, which is clearly wrong. The CPU and GPU versions should match.
```
GPU: tensor([0, 1], device='cuda:0')
CPU: tensor([1])
```

## Environment

PyTorch version: 1.0.0a0+db5d313
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 396.54
cuDNN version: Probably one of the following:
/usr/local/cudnn-9.1-linux-x64-v7.1/lib64/libcudnn.so.7.1.2
/usr/local/cudnn-9.1-linux-x64-v7.1/lib64/libcudnn_static.a
/usr/local/cudnn-9.1-linux-x64-v7/lib64/libcudnn.so.7.0.5
/usr/local/cudnn-9.1-linux-x64-v7/lib64/libcudnn_static.a
/usr/local/cudnn-9.2-linux-x64-v7.1/lib64/libcudnn.so.7.1.4
/usr/local/cudnn-9.2-linux-x64-v7.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda92                    1.0                           0    pytorch
[conda] magma-cuda92              2.4.0                         1    pytorch
[conda] torch                     1.0.0a0+db5d313           <pip>
[conda] torchfile                 0.1.0                     <pip>

**Comment by fmassa** [comment]
Hi Anton,

I couldn't reproduce the issue on my system, using PyTorch `1.0.0.dev20181025`.
What is the last commit of `maskrcnn-benchmark` that you have in your version?

**Comment by aosokin** [comment]
Hi Francisco,
I've tried installing everything again in a fresh environment and could not reproduce the bug. Smth possibly got screwed up when compiling. Sorry for the false report.
Best,
Anton
