### ISSUE TITLE
Can this benchmark support grad CAM?

### ISSUE THREAD

**Issue by robotpp** [facebookresearch/maskrcnn-benchmark#290]
## ❓ Questions and Help
Can this benchmark support grad CAM?
I noticed that this benchmark can create mask montage to show probability heatmaps  during mask segmentation. Can it also be fit for object detection?

**Comment by fmassa** [comment]
Sorry, could you please expand a bit on what you meant by grad CAM?
I didn't understand the question.

**Comment by robotpp** [comment]
Sorry, I didn’t express it clearly.

**Comment by fmassa** [comment]
You can attach a hook in one of the layers of the model to return the feature activation, as discussed in https://github.com/facebookresearch/maskrcnn-benchmark/pull/164
It should be fairly easy, but let me know if you have any further questions.
