### ISSUE TITLE
ModuleNotFoundError: No module named 'maskrcnn_benchmark.config'

### ISSUE THREAD

**Issue by jiapei100** [facebookresearch/maskrcnn-benchmark#30]
## ❓ Questions and Help
$ python webcam.py --min-image-size 800
Traceback (most recent call last):
  File "webcam.py", line 5, in <module>
    from maskrcnn_benchmark.config import cfg
ModuleNotFoundError: No module named 'maskrcnn_benchmark.config'

**Comment by fmassa** [comment]
Hi, are you using python 2?
Also, did you follow the installation instructions in INSTALL.md?

**Comment by fmassa** [comment]
I've added a section in the README with instructions that should help you fix your problem. It is probably related to https://github.com/facebookresearch/maskrcnn-benchmark/issues/22

I'm closing this issue, but let me know if you don't manage to solve your problem.

**Comment by sheep1234567** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/48812213/54792385-156f4900-4bfb-11e9-964f-021d36ca015c.png">

<img width="625" alt="image" src="https://user-images.githubusercontent.com/48812213/54792401-28821900-4bfb-11e9-9532-60d4e2a3aba9.png">

Hi I still have this problem using this setup, do you know what's wrong with it?@fmassa Thanks!

<img width="646" alt="image" src="https://user-images.githubusercontent.com/48812213/54792428-4a7b9b80-4bfb-11e9-844e-cb17babc602e.png">

**Comment by fmassa** [comment]
You didn't install `maskrcnn-benchmark` properly.

Note that now you need to have a nightly version of PyTorch. 1.0.0 or 1.0.1 won't work

**Comment by satyamr1** [comment]
Same error.

$ pwd
      /home/emblab/satyam/maskrcnn/maskrcnn-benchmark/demo

$ python -V
Python 3.6.8 :: Anaconda custom (64-bit)

>>> import torch
>>> print(torch.__version__)
1.2.0.dev20190704

$ nvcc --version
      The pinstarogram 'nvcc' is currently not installed. You can install it by typing:
      sudo apt ll nvidia-cuda-toolkit

$ gcc --version
       gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
       Copyright (C) 2015 Free Software Foundation, Inc.
       This is free software; see the source for copying conditions.  There is NO
       warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
No GPU on the system
$ python webcam.py --min-image-size 300 MODEL.DEVICE cpu
       Traceback (most recent call last):
           File "webcam.py", line 5, in <module>
        from maskrcnn_benchmark.config import cfg
        ModuleNotFoundError: No module named 'maskrcnn_benchmark'

Can you help me out @fmassa

**Comment by AnnZhn** [comment]
> Same error.
> 
> ```
> $ pwd
>       /home/emblab/satyam/maskrcnn/maskrcnn-benchmark/demo
> ```
> 
> ```
> $ python -V
> Python 3.6.8 :: Anaconda custom (64-bit)
> ```
> 
> ```
> >>> import torch
> >>> print(torch.__version__)
> 1.2.0.dev20190704
> ```
> 
> ```
> $ nvcc --version
>       The pinstarogram 'nvcc' is currently not installed. You can install it by typing:
>       sudo apt ll nvidia-cuda-toolkit
> ```
> 
> ```
> $ gcc --version
>        gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
>        Copyright (C) 2015 Free Software Foundation, Inc.
>        This is free software; see the source for copying conditions.  There is NO
>        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```
> 
> **GPU-No (Only CPU)**
> 
> ```
> $ python webcam.py --min-image-size 300 MODEL.DEVICE cpu
>        Traceback (most recent call last):
>            File "webcam.py", line 5, in <module>
>         from maskrcnn_benchmark.config import cfg
>         ModuleNotFoundError: No module named 'maskrcnn_benchmark'
> ```
> 
> Can you help me out @fmassa

i have the same problem with u , have u solved it?

**Comment by satyamr1** [comment]
@AnnZhn, yeah the torchvision-nightly version was conflicting with torchvision. I uninstalled torchvision using: pip uninstall torchvision.
