### ISSUE TITLE
performance speed up

### ISSUE THREAD

**Issue by YohannXu** [facebookresearch/maskrcnn-benchmark#304]
Can anyone tell me how infenrence speed up compare with Detectron on GTX 1080Ti?

**Comment by fmassa** [comment]
I don't have a GTX 1080Ti, but on 8 V100, the performances can be found in https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/MODEL_ZOO.md

A user in https://twitter.com/thekaranchawla/status/1055581631656783873 mentioned that he obtained up to 13fps with a 1080Ti for the demo, if I understand it correctly.

**Comment by YohannXu** [comment]
thank you, you can close it
