### ISSUE TITLE
why use relu instead of relu_ in box/mask head?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [facebookresearch/maskrcnn-benchmark#306]
## ❓ Questions and Help
hi i find that the backbone use `relu_`, while in the heads of bbox and mask, it uses `relu`, what is the difference between them?

**Comment by fmassa** [comment]
No particular reason, it could have been an in-place rely as well in the heads.
I'm not sure if that will make any significant different wrt memory, but I'd love to hear if it makes any difference.
