### ISSUE TITLE
How can I do inference without GPU?

### ISSUE THREAD

**Issue by mattans** [facebookresearch/maskrcnn-benchmark#308]
I am having CUDA issues:
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version

However, I have a trained model and I want to load it and do inference with CPU, to bypass my CUDA issue.
How can I do that?

**Comment by fmassa** [comment]
If you have custom code, just call `.cpu()` in the model and inputs.
If you are using the config, just pass `DEVICE cpu` to the config field.
