### ISSUE TITLE
1 class object per image support

### ISSUE THREAD

**Issue by acrola** [facebookresearch/maskrcnn-benchmark#311]
## ❓ Questions and Help
Do this implementation support fine-tuning training for images where each object class can appear only once?

**Comment by fmassa** [comment]
Do you mean that we need to enforce a constraint that there is only a single instance of any class per image?
If that's the question, then no, we don't have this constraint in the implementation, but it can be added on top of the current codebase.

**Comment by fmassa** [comment]
I'm closing the issue, but let me know if you have further questions.
