### ISSUE TITLE
will this benchmark plan to support retinanet?

### ISSUE THREAD

**Issue by mlinxiang** [facebookresearch/maskrcnn-benchmark#32]
## 🚀 Feature
retinanet report a high speed and mAP performance, will this benchmark support this

**Comment by fmassa** [comment]
RetinaNet support has been added in https://github.com/facebookresearch/maskrcnn-benchmark/pull/102 and will be merged soon.

**Comment by fmassa** [comment]
This has been added in https://github.com/facebookresearch/maskrcnn-benchmark/pull/102 by @chengyangfu
