### ISSUE TITLE
How to do CropAndResize?

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/maskrcnn-benchmark#320]
Many maskrcnn repos use `CropAndResizeFunction`  like in: https://github.com/longcw/RoIAlign.pytorch/blob/master/roi_align/crop_and_resize.py

Is there a way to do the same as `CropAndResizeFunction` using the functions available in this library?
Thanks.

**Comment by fmassa** [comment]
You can do a (not efficient) crop and resize using indexing and `interpolate`.
But for that we have [`RoiAlign`](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/layers/roi_align.py), which should be almost exactly what you are looking for.

**Comment by IssamLaradji** [comment]
Thanks!
