### ISSUE TITLE
P6 feature map used in config?

### ISSUE THREAD

**Issue by txytju** [facebookresearch/maskrcnn-benchmark#322]
## ❓ Questions and Help
in most config files, I found that len(POOLER_SCALES_==4, but if we use R-50-FPN, P2-P6 are used. If so, when operating the pooling operation, do we miss P6?

**Comment by fmassa** [comment]
Yes, FPN do not use P6, because for the FPN models we have it's just a downsampled version of F5, and doesn't bring any extra information.
This is the same behavior as in Detectron.

**Comment by JoyHuYY1412** [comment]
> Yes, the pooler doesn't use P6, because for the FPN models we have it's just a downsampled version of P5, and doesn't bring any extra information.
> This is the same behavior as in Detectron.

So why we need P6? In order to generate proposals in RPN? Since I see that the output features has 5 layers containing the P6's.

**Comment by fmassa** [comment]
@JoyHuYY1412 for the models we currently have in `maskrcnn-benchmark`, P6 is only used for generating the proposals from the RPN (it generates larger proposals).
