### ISSUE TITLE
How to add X-101-64x4d-FPN_2x? 

### ISSUE THREAD

**Issue by antocapp** [facebookresearch/maskrcnn-benchmark#323]
Hello to everyone, 
Where do I have to make changes in order to replicate the X-101-64x4d-FPN_2x architecture? 

I have tried for the moment just to set NUM_GROUPS: 64 and WIDTH_PER_GROUP: 4 in RESNETS key in config file, but loading converted pretrained weights on from Detectron (so caffe2) leads to poor results. 

Can you help me figure out the correct way to set the same architecture X-101-64x4d-FPN_2x used in Detectron?

**Comment by fmassa** [comment]
You should just change https://github.com/facebookresearch/maskrcnn-benchmark/blob/f25c6cff92d32d92abe8965d68401004e90c8bee/configs/e2e_faster_rcnn_X_101_32x8d_FPN_1x.yaml#L24-L25
and also the pre-trained model path, and it should work off-the-shelf.

If it doesn't work, I'd recommend having a look at the weights that were loaded (they are printed in the beginning of the log). They should show all weights in the model. If that's not the case, let me know

**Comment by antocapp** [comment]
Hi @fmassa, the problem is that I trained that network with Detectron repository on my own custom dataset, and now I want to ship all to pytorch using maskrcnn-benchmark repository; however the results are not the same. 

Are there any other things that I may change? I have also tried to remove the preprocessing on input images in COCODemo class in predictor.py file.

**Comment by antocapp** [comment]
Hi @fmassa, at the end I was able to reproduce the network. Thanks for the support.
What is the difference between using cfg.DATALOADER.SIZE_DIVISIBILITY or feeding the entire image to the network? 
Thanks again

**Comment by fmassa** [comment]
What was the problem?

> What is the difference between using cfg.DATALOADER.SIZE_DIVISIBILITY or feeding the entire image to the network?

Some models (like FPN) require that the image sizes are a multiple of a factor (because it performs upsampling with a fixed scale), that's why the `SIZE_DIVISIBILITY` is needed.

**Comment by antocapp** [comment]
I have changed the preprocessing operation performed in this line:
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L195

so I created my own preprocessing, which is 
```python
def preprocess(self, im):
        """
        Creates a basic transformation that was used to train the models
        """
        cfg = self.cfg

        target_size = 800
        max_size = 1333

        pixel_means=cfg.INPUT.PIXEL_MEAN
        im = im.astype(np.float32, copy=False)
        im -= pixel_means
        im_shape = im.shape
        im_size_min = np.min(im_shape[0:2])
        im_size_max = np.max(im_shape[0:2])
        im_scale = float(target_size) / float(im_size_min)
        # Prevent the biggest axis from being more than max_size
        if np.round(im_scale * im_size_max) > max_size:
            im_scale = float(max_size) / float(im_size_max)
        im = cv2.resize(
            im,
            None,
            None,
            fx=im_scale,
            fy=im_scale,
            interpolation=cv2.INTER_LINEAR
        )
        return torch.tensor(im.transpose(2,0,1))
```
which is basically the preprocessing used in detectron here: https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/blob.py#L100-L125

**Comment by antocapp** [comment]
Moreover, to overcome the previous error: 
>File "/home/antonio/repositories/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/fpn.py", line 62, in forward
last_inner = inner_lateral + inner_top_down
RuntimeError: The size of tensor a (143) must match the size of tensor b (144) at non-singleton dimension 3

I changed the line in the fpn backbone https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fpn.py#L57-L61 by removing the comment on inner_top_down at line 60 and commenting line 57

**Comment by fmassa** [comment]
@antocapp the error you faced is also fixed (following Detectron implementation) by considering `SIZE_DIVISIBILITY`

**Comment by antocapp** [comment]
> Moreover, to overcome the previous error:
> 
> > File "/home/antonio/repositories/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/fpn.py", line 62, in forward
> > last_inner = inner_lateral + inner_top_down
> > RuntimeError: The size of tensor a (143) must match the size of tensor b (144) at non-singleton dimension 3
> 
> I changed the line in the fpn backbone https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fpn.py#L57-L61 by removing the comment on inner_top_down at line 60 and commenting line 57

Never mind about this because I changed again the configuration as it is in the repo and it works now

**Comment by antocapp** [comment]
Could the problem be here: https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L142? My input images are already in the range 0-255 so the values probably exploded here..

**Comment by antocapp** [comment]
Hi @fmassa, I have tried again now with build_transforms and everything is just fine. Sorry to have bothered you but maybe the mistake was just to not have set --min-image-size to 800...

**Comment by fmassa** [comment]
Cool, good to know, thanks!
