### ISSUE TITLE
SoftNMS

### ISSUE THREAD

**Issue by kris-singh** [facebookresearch/maskrcnn-benchmark#330]
## 🚀 Feature

I am trying to add SoftNMS to the repo. This might be useful in few cases can be seen from here. 
[SoftNMS](https://arxiv.org/pdf/1704.04503.pdf)
## Motivation
see above

I tried to build the feature myself as an exercise for trying to build cpp extensions to pytorch. I was able to implement the softnms and build the package again. The build is successful but there is some issue with pybind11 ie it says it can't import layers as a symbol not found. I am new to ninja build, moreover, the error does little to help could you please help in this regard. Here all the files i changed 
[Gist](https://gist.github.com/kris-singh/219f2df5acb26fd4b07459df9b4ab44d)

Please let me know if any other information is required.

**Comment by fmassa** [comment]
Hi,

Thanks for the contribution.

Could you paste the full error log here?

Also, I'd recommend you `rm -rf buid/` and recompile it again, it might help.

**Comment by fmassa** [comment]
Sounds good, let me know how it goes and if it works for you, it would be great sending a PR!

**Comment by kris-singh** [comment]
Sorry had a couple of busy few days I had implemented an updated version for myself but never got around to pushing it here. Closing this in favor of #362.

**Comment by lyakaap** [comment]
@kris-singh Oh sorry.
I found some bugs in the PR, so if you already have correct implementation of SoftNMS, it's good if you  make new PR instead of me (if so, I'll close).

**Comment by kris-singh** [comment]
@lyakaap No issues. Please go ahead with you PR. I will work on the GPU implementation once I test it out.

**Comment by sunycl** [comment]
@lyakaap @fmassa I am ashamed that I met the error ""ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (/media/szu/hardware/ycl/lab/maskscoring_nms/maskrcnn_benchmark/__init__.py)"
But I changed the code and rebuild it. would you mind telling me how to deal with this?

**Comment by sunycl** [comment]
@lyakaap @fmassa I am ashamed that I met the error "ImportError: cannot import name '_C' from 'maskrcnn_benchmark'"
But I have changed the soft_nms code and rebuild it. Would you mind telling me how to deal with this?
