### ISSUE TITLE
Do you have a API to output COCO format?

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#332]

**Comment by fmassa** [comment]
Yes, when evaluating on COCO we output a `bbox.json` file which can be directly read by COCOeval, see https://github.com/facebookresearch/maskrcnn-benchmark/blob/f25c6cff92d32d92abe8965d68401004e90c8bee/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py#L277-L283
