### ISSUE TITLE
How can  I evaluate on coco2014?

### ISSUE THREAD

**Issue by woshildh** [facebookresearch/maskrcnn-benchmark#341]
I have trained this maskrcnn-R50-FPN coco dataset, how should I only evaluate my performence on coco again? Thank you.

**Comment by fmassa** [comment]
You can run `tools/test_net.py` and passing the `WEIGHT` to be the last checkpoint you have, or use the `OUTPUT_DIR` to be the path where you saved your logs / trained models.

Let me know if you have further questions.
