### ISSUE TITLE
Why need to re-create the BoxList in MaskPostProcessor?

### ISSUE THREAD

**Issue by chenzhutian** [facebookresearch/maskrcnn-benchmark#343]
## ❓ Questions and Help
Thanks for the great work. I have a silly question about the code in https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py#L53-L59

```python
        results = []
        for prob, box in zip(mask_prob, boxes):
            bbox = BoxList(box.bbox, box.size, mode="xyxy")
            for field in box.fields():
                bbox.add_field(field, box.get_field(field))
            bbox.add_field("mask", prob)
            results.append(bbox)
```

Why do we need to re-create a new BoxList based on the old one?
Is it possible to directly add the `mask` field on the old boxList?

Thanks very much!

**Comment by fmassa** [comment]
Hi,

The reason why I recreated a new `BoxList` was to avoid mutating the original object, which could have hard-to-track side effects on other parts of the model which still used the "old" `BoxList` (and was not expecting to have the `mask` field in that instance).

The reasoning is similar to modifying a tensor in-place, see the following for an example:
```python
def f(x):
    return x.exp_()  # inplace

a = torch.rand(2)
b = f(x)
c = b + a  # oups, "a" has been modified already
```

Let me know if you have further questions.

**Comment by chenzhutian** [comment]
I see. Thanks!
