### ISSUE TITLE
PRETRAINED MODEL WEIGHT PATH

### ISSUE THREAD

**Issue by mrayush18** [facebookresearch/maskrcnn-benchmark#349]
While specifying an absolute path in   _C.MODEL.WEIGHT in  maskrcnn_benchmark/config/defaults.py  does not changes default path ,it is still taking pretrained model from e2e_mask_rcnn_R_50_FPN_1x.yaml file.
if changing the path from the .yaml file it is working but not with  _C.MODEL.WEIGHT at any time .
Can someone clarify?
I have stored the pretrained weights of caffe detectron using this [ tools/trim_detectron_model.py](https://gist.github.com/wangg12/aea194aa6ab6a4de088f14ee193fd968  ) in folder maskrcnn-benchmark/pretrained_model

**Comment by fmassa** [comment]
You need to specify the default path in the config, by overriding it in the command-line via `MODEL.WEIGHT /path/to/weight`, or else whatever modifications that you do in `config/defaults.py` will be modified by the config files, which all have a default path.

**Comment by backpropagator** [comment]
ever modifications that you do in `config/defaults.py` will be modified by the config files, which all have a default path.

**Comment by backpropagator** [comment]
@fmassa but one thing that I couldn't understand is that why changing `_C.MODEL.WEIGHT` in `config/defaults.py` doesn't do anything....I have to manually give the weight path in `configs/e2e_mask_rcnn_R_50_FPN_1x.yaml'

**Comment by fmassa** [comment]
because they get overwritten in any of the configs that we have available

**Comment by rodrigoberriel** [comment]
@mrayush18 if you take a look at `tools/train_net.py`, you'll see that the config is loaded this way:

https://github.com/facebookresearch/maskrcnn-benchmark/blob/d3fed42afe59910dd650308c426640d183d044b5/tools/train_net.py#L14
https://github.com/facebookresearch/maskrcnn-benchmark/blob/d3fed42afe59910dd650308c426640d183d044b5/tools/train_net.py#L144-L146

What is happening? Let's say you ran the following command:

    python tools/train_net.py --config-file path/to/config.yaml MODEL.WEIGHT path/to/weights.pth

1. First, when the `cfg` is imported, `cfg` has all the default values defined in [`maskrcnn_benchmark/config/defaults.py`](https://github.com/facebookresearch/maskrcnn-benchmark/blob/d3fed42afe59910dd650308c426640d183d044b5/maskrcnn_benchmark/config/defaults.py#L33). As you may have noticed, the default value for `MODEL.WEIGHT` is `""`; that is, no weights will be loaded by default;
2. Then, the values defined in your `--config-file` (in our example, `path/to/config.yaml`) overwrite the default values. As @fmassa told you, all the config values that are available in this repository have a `MODEL.WEIGHT` defined, i.e., it will always be overwritten when using one of them;
3. Finally, the [remaining command-line arguments](https://github.com/facebookresearch/maskrcnn-benchmark/blob/d3fed42afe59910dd650308c426640d183d044b5/tools/train_net.py#L125-L130) can used to update any config value. In our example, we update `MODEL.WEIGHT` to `path/to/weights.pth`. You can update as many config values as you want.
4. The last line freezes cfg (i.e., [make the config values immutable](https://github.com/rbgirshick/yacs/blob/master/yacs/config.py#L209-L211)), making sure they are not (accidentally) changed during the execution.

As you can see, given that you can change any config value via a custom config file or a command-line argument, it is not recommended to change values directly on the `defaults.py`.

**Comment by fmassa** [comment]
Thanks for the explanations @rodrigoberriel !
Closing this, let us know if you have further questions
