### ISSUE TITLE
Pascal Voc dataset does not have test.txt file

### ISSUE THREAD

**Issue by JSharp4273** [facebookresearch/maskrcnn-benchmark#351]
## ❓ Questions and Help

Hello

I put this as a question because I did not really know where to write it.
It is more an observation than a question.

I recheck in the Pacal Voc datasets, some of them (from 2009 to 2012 included) does not have a file a file name "test.txt" in the folder: "ImageSet/Main".

I write this because in the file: "maskrcnn_benchmark/config/paths_catalog.py" in the member "'CATALOG" of the class "DatasetCatalog" there that instance: 

        "voc_2012_test": {
            "data_dir": "voc/VOC2012",
            "split": "test"
        },

In the File "maskrcnn_benchmark/data/datasets/voc.py" the argument split is assign to the member "image_set" that is later use to set the member "ids":

        with open(self._imgsetpath % self.image_set) as f:
            self.ids = f.readlines()            
        self.ids = [x.strip("\n") for x in self.ids]

with "self._imgsetpath" as "os.path.join(self.root, "ImageSets", "Main", "%s.txt")"

So if test.txt does not exist no image will be set and by extension no testing will be done.

**Comment by fmassa** [comment]
I have the `test.txt` in my copy of VOC2012, so I'm not sure why you do not have one.
It is true that we do not have the labels for the test images though, which means that we can't evaluate on the test set locally, but instead we need to submit to their server to obtain the mAP metrics.

Let me know if you have further questions.

**Comment by JSharp4273** [comment]
I recheck on the official Pascal Voc website when you download the dataset there is not test.txt

**Comment by JSharp4273** [comment]
I just recheck right now (this time only for Pascal 2012) and I did not find a test.txt in ImageSet/Main using the official link for Pascal 2012.
If you have download it from another source I might be interested to know the link.

**Comment by fmassa** [comment]
@JSharp4273 I just checked in http://host.robots.ox.ac.uk/pascal/VOC/voc2012/ on the `Test Data` section. You can download it from their servers in http://host.robots.ox.ac.uk:8080/ once you register to it.

**Comment by JSharp4273** [comment]
Thank you very much :)
Actually I just saw that 5 min ago I am downloading it.
Thank you very much for your help.
