### ISSUE TITLE
How to draw a precision-recall curve when testing.

### ISSUE THREAD

**Issue by guanbin1994** [facebookresearch/maskrcnn-benchmark#353]

**Comment by fmassa** [comment]
It will require using a few internal features from COCOeval (if you are evaluating on COCO, the answer changes if not).
After this part https://github.com/facebookresearch/maskrcnn-benchmark/blob/d28845e112de36781b2b5f7217a34b2b62de8d2f/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py#L289
you can grab the `coco_eval` object and you'll find in its `.eval` field both the `precision` and the `recall`, see https://github.com/cocodataset/cocoapi/blob/ed842bffd41f6ff38707c4f0968d2cfd91088688/PythonAPI/pycocotools/cocoeval.py#L412-L419
