### ISSUE TITLE
Issue Training on Pascal Voc datasets.

### ISSUE THREAD

**Issue by JSharp4273** [facebookresearch/maskrcnn-benchmark#356]
## 🐛 Bug

I tried to make a training bases on Pascal Voc 2012 Dataset by adapting the provided example for coco.
The example for COCO is:
python tools/train_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 TEST.IMS_PER_BATCH 1

This example works.
I adapted the code to:

python tools/train_net.py --config-file "configs/pascal_voc/e2e_mask_rcnn_R_50_FPN_1x_cocostyle.yaml" SOLVER.IMS_PER_BATCH 2 TEST.IMS_PER_BATCH 1

Note I payed attention to set properly the links to Pascal data in the datasets folder.
I applied the test on a version of maskrcnn-benchmark that I downloaded few hours ago.

## To Reproduce

Simply:
python tools/train_net.py --config-file "configs/pascal_voc/e2e_mask_rcnn_R_50_FPN_1x_cocostyle.yaml" SOLVER.IMS_PER_BATCH 2 TEST.IMS_PER_BATCH 1

RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
	size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([21]).
	size mismatch for roi_heads.box.predictor.bbox_pred.weight: copying a param with shape torch.Size([324, 1024]) from checkpoint, the shape in current model is torch.Size([84, 1024]).
	size mismatch for roi_heads.box.predictor.bbox_pred.bias: copying a param with shape torch.Size([324]) from checkpoint, the shape in current model is torch.Size([84]).
	size mismatch for roi_heads.mask.predictor.mask_fcn_logits.weight: copying a param with shape torch.Size([81, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([21, 256, 1, 1]).
	size mismatch for roi_heads.mask.predictor.mask_fcn_logits.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([21]).

## Expected behavior

Start Training The Network Specified in The Name of The File (Mask-rcnn, Faster-rcnn) using the specified configuration.

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN Xp COLLECTORS EDITION
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 415.13
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.3.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.4
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/cuda-9.1/lib64/libcudnn.so
/usr/local/cuda-9.1/lib64/libcudnn.so.7
/usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.1/lib64/libcudnn_static.a
/usr/local/cuda-9.2/lib64/libcudnn.so
/usr/local/cuda-9.2/lib64/libcudnn.so.7
/usr/local/cuda-9.2/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] cuda100                   1.0                           0    pytorch
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] cuda92                    1.0                           0    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl-include               2019.0                      118  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.4            py36h4414c95_1  
[conda] mkl_random                1.0.1            py36h4414c95_1  
[conda] pytorch                   1.0.0           py3.6_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181103 py3.6_cuda9.2.148_cudnn7.1.4_0  [cuda92]  pytorch
[conda] torch                     0.4.0                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                      py_2    pytorch

This error has appeared for each configuration file in config/pascal_voc.

**Comment by fmassa** [comment]
Because you are using weights from COCO, you need to do some weights surgery to remove the last classifier layers from COCO. See https://github.com/facebookresearch/maskrcnn-benchmark#finetuning-from-detectron-weights-on-custom-datasets for more information.

And let me know if you have further questions

**Comment by JSharp4273** [comment]
Hello 
Thanks for your help.

Wouldn't it better if rather than removing the last layer I replace it by one at the proper size ?
Is it enough to do the surgery resave everything and adapt the configuration file ?

**Comment by fmassa** [comment]
@JSharp4273 yes, you can either remove it or replace it in the checkpoint, and it should be enough.
But removing it will make the weights for this layer to be initialized with the expected distribution, so it might be better.

After that, you just need to adapt the config file to point to the new weights and change the number of classes.

**Comment by JSharp4273** [comment]
Ok thanks you very much for your help :)

**Comment by JSharp4273** [comment]
@fmassa Sorry to bother you again.


Just for make it clear for me: If I remove the weights for the last layer, some new weights will be automatically added ?

I feel a bit lost about the folowing point:
-Suppose I want to retrain mask-rcnn to detect and segments N labels.
I understand how by adapting the weights of the last layer it can works.
However I do not really understand how by removing the weights last layer I can get my N labels ?

Thanks in advance for your help.

**Comment by fmassa** [comment]
@JSharp4273 I meant to remove the weights from the checkpoint file, not from the model.
If you remove it there, the layer will still be present in the model definition in python, and will be randomly initialized.

**Comment by JSharp4273** [comment]
@fmassa Sorry to bother you again.

I  face an I think it has the same root as the one I initially mentioned here.
Here is what I want to do.
I want to train a Mask-Rcnn on a Pascal DataSet using the xml annotations.
In the config folder there is several configuration files (.yaml) two for train Faster-Rcnn and one for the whole Mask-Rcnn but using cocostyle annotations.
In order to realized what I want to do I copied, paste, rename and modify the configuration In order to use pascal annotations rather than coco i.e:
e2e_mask_rcnn_R_50_FPN_1x_cocostyle.yaml:

  _TRAIN: ("voc_2012_train_cocostyle",)
  TEST: ("voc_2012_val_cocostyle",)_

e2e_mask_rcnn_R_50_FPN_1x_voc.yaml

  _TRAIN: ("voc_2007_train",)
  TEST: ("voc_2007_test",)_

So at the end this is my configuraton file (e2e_mask_rcnn_R_50_FPN_1x_voc.yaml) :

_MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ("voc_2007_train",)
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, )
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1_

Now no matter what configuration file I do call non of the two files (e2e_mask_rcnn_R_50_FPN_1x_*) works.
Even the one that use cocostyle annotation that is downloaded with the project.

However it works for Faster-Rcnn.

In short:

this works:

`python tools/train_net.py --local_rank 1 --config-file "configs/pascal_voc/e2e_faster_rcnn_R_50_C4_1x_1_gpu_voc.yaml"`

But this do not (the configuation file is the default **untouch** one, not my custom):

`python tools/train_net.py --local_rank 1 --config-file "configs/pascal_voc/e2e_mask_rcnn_R_50_FPN_1x_cocostyle.yaml" `

the content of pascal_voc/e2e_mask_rcnn_R_50_FPN_1x_cocostyle.yaml is:

_MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 21
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("voc_2012_train_cocostyle",)
  TEST: ("voc_2012_val_cocostyle",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (18000,)
  MAX_ITER: 24000_

The error is that:

```
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for rpn.anchor_generator.cell_anchors.0: copying a param with shape torch.Size([9, 4]) from checkpoint, the shape in current model is torch.Size([3, 4]).
	size mismatch for rpn.head.conv.weight: copying a param with shape torch.Size([1024, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for rpn.head.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for rpn.head.cls_logits.weight: copying a param with shape torch.Size([9, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
	size mismatch for rpn.head.cls_logits.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([3]).
	size mismatch for rpn.head.bbox_pred.weight: copying a param with shape torch.Size([36, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([12, 256, 1, 1]).
	size mismatch for rpn.head.bbox_pred.bias: copying a param with shape torch.Size([36]) from checkpoint, the shape in current model is torch.Size([12]).
	size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([21, 2048]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
	size mismatch for roi_heads.box.predictor.bbox_pred.weight: copying a param with shape torch.Size([84, 2048]) from checkpoint, the shape in current model is torch.Size([84, 1024]).
```

I have the same error with if I try to train a using the xml annotation (the non coco style).

Like we discuss before it is definitively a question of model weights trimming.

My question is why does it works with Faster-Rcnn and not with Mask-Rcnn ?

Another question much less significant is where the 4 ratio come from ?
The one before last line of error mention a size of 21 x 1024 while the last report an 84 x 1024.

Thanks in advance for your time.

**Comment by fmassa** [comment]
@JSharp4273 the 4 ratio is probably from the box_regression (which is class-specific).
You probably forgot to trim some of the weights of the model (probably the bbox_regression_weights).

**Comment by JSharp4273** [comment]
@fmassa I did not trimed the weights however I wanted to check if "your" code does work and it does not with mask-rcnn but it does with faster-rcnn.
My question is why ?

**Comment by fmassa** [comment]
What's your `OUTPUT_DIR` folder? Is there already a pre-trained model there?

I think you might have trained using a C4 architecture first, and are now launching training on the same folder, and it's picking the state-dict from the pre-trained model.
