### ISSUE TITLE
Run `setup.py` no problem but failed when import `_C` cpython module

### ISSUE THREAD

**Issue by sydney0zq** [facebookresearch/maskrcnn-benchmark#367]
## 🐛 Bug

I git clone this project, and then use gcc-5.4 to compile the necessary modules by 
```
python3 setup.py build develop
```
And I passed this step, nothing wrong with it.

However, when I try to run `COCODemo`, exactly when I want to import `_C` module, it pops:

```
➜ [username train119 ] layers git:(master) ✗ python3
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nms import nms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data-1/username/research/real_time_VOS/RT-MDNet/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /mnt/data-1/username/research/real_time_VOS/RT-MDNet/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
>>>
```

It pops CUDA pop call configuration error. It is really strange. And I use pytorch1.0-CUDA9.0-cudnn7.4.1 version. My CUDA version is actually 9.2. Would it be the reason?

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: CentOS Linux release 7.5.1804 (Core)
GCC version: (GCC) 5.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN V
GPU 1: TITAN V
GPU 2: TITAN V
GPU 3: TITAN V

Nvidia driver version: 396.45
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cuda-9.2/lib64/libcudnn.so.7.3.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] numpydoc (0.7.0)
[pip3] torchfile (0.1.0)
[pip3] torchnet (0.0.2)
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.1                      144    defaults
[conda] mkl-include               2019.1                      144    defaults
[conda] mkl-service               1.1.2            py36he904b0f_5    defaults
[conda] mkl_fft                   1.0.10           py36ha843d7b_0    defaults
[conda] mkl_random                1.0.2            py36hd81dba3_0    defaults
[conda] pytorch                   1.0.0           py3.7_cuda9.0.176_cudnn7.4.1_1   
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.2                     <pip>

**Comment by sydney0zq** [comment]
And when I compile `_C` library, I always set my `CUDA_HOME` and `CUDNN_HOME` to cuda-9.2. So it should not be the problem.

**Comment by sydney0zq** [comment]
This issue has solved by reference the other issue and after a lot of struggles.

The inconsistent version of NVCC and CUDAToolKit is the root of the wired problem.

Thanks anyway!

**Comment by fmassa** [comment]
Great that you managed to fix your issue!
I believe this has been mentioned in the [TROUBLESHOOTING section of the README](https://github.com/facebookresearch/maskrcnn-benchmark#troubleshooting), would there be a better way of making it more visible?

**Comment by sydney0zq** [comment]
The problem has not mentioned in the README/TROUBLESHOOTING, it occured in the issue #48 instead. I am not sure whether it is a common problem.

I will send a PR to README/TROUBLESHOOTING after hours.
