### ISSUE TITLE
ImportError on from maskrcnn_benchmark import _C

### ISSUE THREAD

**Issue by adizhol** [facebookresearch/maskrcnn-benchmark#369]
## ❓ Questions and Help
ImportError: DLL load failed: The specified module could not be found.

I've build the project successfully on Winodws 10 with pytorch 1.0, python 3.6, VS 2017, CUDA 9.2, using Conda environment.
but I get the above error when calling
[nms.py]
`from maskrcnn_benchmark import _C
`
I ran `python setup.py build develop`
and I have a file `REPO_FOLDER/maskrcnn_benchmark/_C.cp36-win_amd64.pyd`
and _C.py file in `CONDA_ENV_FOLDER\pytorch10\Lib\site-packages\maskrcnn_benchmark-0.1-py3.6-win-amd64.egg\maskrcnn_benchmark`

Also, the demo notebook works correctly
#1

**Comment by fmassa** [comment]
Are you using the same conda environment for testing this?

It seems weird that the notebook works fine, it might indicate that you might not have switched to the right env before using `maskrcnn-benchmark`?

**Comment by adizhol** [comment]
@fmassa 
Yes, I made sure again

**Comment by fmassa** [comment]
If the notebook works, this means that the environment is able to pick the library correctly.
Did you compile `maskrcnn-benchmark` from the same environment as the jupyter notebook? I think this is very strange

**Comment by adizhol** [comment]
update:
When running from command line and activated conda environment, there is no error.
But using PyCharm, the error still exists.
I checked to %PATH% variables and it seams PyCharm has CUDA 8 in %PATH% while command line has CUDA 9.2.
So the issues seems to be PyCharm %PATH% not getting updated...

**Comment by fmassa** [comment]
You might need to update the settings in PyCharm to take into account your new environment maybe?

**Comment by adizhol** [comment]
Solved.
The PyCharm environment was correct.
After restarting windows, the training script works from PyCharm too.
Thanks :)
