### ISSUE TITLE
unmatched targets are clamped to 0?

### ISSUE THREAD

**Issue by opoppo** [facebookresearch/maskrcnn-benchmark#385]
## ❓ Questions and Help
in roi_heads\box_head\loss.py wrote
```
        # get the targets corresponding GT for each proposal
        # NB: need to clamp the indices because we can have a single
        # GT in the image, and matched_idxs can be -2, which goes
        # out of bounds
        matched_targets = target[matched_idxs.clamp(min=0)]
```
but clamping the idxs of -1 or -2 which stand for no match to beacome 0, would means the first target (target[0]) to be sampled as matched one? 
desperately wondering where I got wrong in here?

**Comment by fmassa** [comment]
Good question.

Note that the indices corresponding to no match will be filtered in https://github.com/facebookresearch/maskrcnn-benchmark/blob/5f2a8263a1a0f2f5f0137042cd4ba64efcb6859a/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L52, and we still keep the original indices in the extra field https://github.com/facebookresearch/maskrcnn-benchmark/blob/5f2a8263a1a0f2f5f0137042cd4ba64efcb6859a/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L42

The reason why I clamped it in https://github.com/facebookresearch/maskrcnn-benchmark/blob/5f2a8263a1a0f2f5f0137042cd4ba64efcb6859a/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L41
was simply to avoid cases where we don't have at least 2 GT boxes in an image (in which case it would raise an error trying to index -2). Note that this is just to perform the alignment between anchors/proposals and gt boxes, and the ignored anchors will be dropped in the sampler in https://github.com/facebookresearch/maskrcnn-benchmark/blob/5f2a8263a1a0f2f5f0137042cd4ba64efcb6859a/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L87 , as we have already modified the labels by taking into account the `matched_idx` in https://github.com/facebookresearch/maskrcnn-benchmark/blob/5f2a8263a1a0f2f5f0137042cd4ba64efcb6859a/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L63

Let me know if you have further questions.
