### ISSUE TITLE
Training from scrach

### ISSUE THREAD

**Issue by Computational-Camera** [facebookresearch/maskrcnn-benchmark#386]
As the paper titled  "Rethinking ImageNet Pre-training" suggests, it is possible to train the generalized R-CNN network from scratch. Does this feature currently support it?

**Comment by fmassa** [comment]
@zimenglan-sysu-512 has just recently added support for ResNet with GroupNorm in https://github.com/facebookresearch/maskrcnn-benchmark/pull/346

See for example this config file for reference https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/gn_baselines/scratch_e2e_mask_rcnn_R_50_FPN_3x_gn.yaml , which trains the model from scratch.

Let me know if you have further questions

**Comment by Antoine-ls** [comment]
@fmassa 
Is FREEZE_CONV_BODY_AT should be -1 to train from scratch instead of 0 as 0 will freeze stem network in resnet.py
`def _freeze_backbone(self, freeze_at):
        if freeze_at < 0:
            return
        for stage_index in range(freeze_at):
            if stage_index == 0:
                m = self.stem  # stage 0 is the stem
            else:
                m = getattr(self, "layer" + str(stage_index))
            for p in m.parameters():
                p.requires_grad = False
`
