### ISSUE TITLE
python setup.py build develop subprocess.CalledProcessError

### ISSUE THREAD

**Issue by disign-ming** [facebookresearch/maskrcnn-benchmark#388]
## ❓ Questions and Help
result:subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
Installation error, what is the cause?

**Comment by fmassa** [comment]
Looks like you don't have a `g++` available on your system?

**Comment by fmassa** [comment]
I'd recommend you installing `g++`, or overriding the `CXX` environment variable to point to a c++ compiler. This should fix your error. If not, let us know

**Comment by linhuaiyuan** [comment]
@fmassa  I installed G++, and the same error occurred.
