### ISSUE TITLE
How to do inference under ROS envoirment ? 

### ISSUE THREAD

**Issue by jediofgever** [facebookresearch/maskrcnn-benchmark#392]
## ❓ Questions and Help
Hello,
I would like to use maskrcnn for my ROS project, I have installed and tested the repo successfully under Anaconda envoirment. When I try to use ROS and Anaconda at same time I run into conflicts between anaconda and ROS. Is there a suggested way to do this ? , If I can get maskrcnn running without Anaconda probably I can get there ? 

Can someone please guide me with this ? 

Thank you

**Comment by fmassa** [comment]
Hi,

I have no experience at all with ROS unfortunately.

@soumith maybe knows a bit better?

**Comment by JiamingSuen** [comment]
According to [a solution on a chinese blog post](https://blog.csdn.net/qq_33521754/article/details/78829212), installing these packages resolves this problem.
```
$ conda install setuptools
$ pip install -U rosdep rosinstall_generator wstool rosinstall six vcstools
```

**Comment by jediofgever** [comment]
Thank you @fmassa and @JiamingSuen.
 
I did install the packages listed by @JiamingSuen  and I am able to get ROS running inside Anaconda envoirment  as in below picture. 

![rr](https://user-images.githubusercontent.com/18460336/51956729-c838eb80-2483-11e9-9a4f-19417908342a.png)

Now I am trying to get inference in a ROS node I am not sure if I will hit some errors there. So I will keep issue open for now, once I am done I will update here for reference.

Thank you for your help~!

**Comment by fmassa** [comment]
Hi @jediofgever 

Did you managed to make `maskrcnn-benchmark` work on ROS?

**Comment by ipa-mah** [comment]
Did anyone already make it?
Thanks
