### ISSUE TITLE
Can I use softnms and how to use it in this code?

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#397]
## ❓ Questions and Help
Do you have the model that trained with soft-nms? I think there may exist improvement.

**Comment by fmassa** [comment]
We don't currently have softnms available.
There is an open PR for that in https://github.com/facebookresearch/maskrcnn-benchmark/pull/362.

Let's keep the discussion in https://github.com/facebookresearch/maskrcnn-benchmark/issues/330
