### ISSUE TITLE
SIGSEGV: 11: ERROR 

### ISSUE THREAD

**Issue by mrayush18** [facebookresearch/maskrcnn-benchmark#400]
I'm trying to train mask-rcnn on my own dataset with 4 GPUs (p3.8x large)  ,after running train.py as mentioned in README.md 

`export NGPUS=4
python -m torch.distributed.launch --nproc_per_node=$NGPUS /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "path/to/config/file.yaml"`

I got following Error. @fmassa  can you please help .

`creating index... 2019-02-01 04:45:45,090 maskrcnn_benchmark.trainer INFO: Start training 0%| | 0/90000 [00:00<?, ?it/s]index created! 0%| | 0/90000 [00:00<?, ?it/s]Traceback (most recent call last): File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 222, in<module> main() File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 218, inmain cmd=process.args) subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch_p36/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config', 'configs/e2e_mask_rcnn_R_50_FPN_1x.yaml']' died with <Signals.SIGSEGV: 11>.`

**Comment by fmassa** [comment]
Hi,

Could you check that [this part of the TROUBLESHOOTING](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/TROUBLESHOOTING.md#segmentation-fault-core-dumped-when-running-the-library) is not the reason why your code segfaulted?

**Comment by mrayush18** [comment]
It worked 
Thanks @fmassa

**Comment by fmassa** [comment]
Cool, let me know if you face any other problems
