### ISSUE TITLE
pretrain models problem

### ISSUE THREAD

**Issue by mehrdadazizi72** [facebookresearch/maskrcnn-benchmark#406]
## ❓ Questions and Help
I run webcam.py on a single image with the pre-train model but the result didn't find anything. after that use detectron pre-train model and get better result but the result worse than the result of detectron.
Does anybody have an idea why this happens?
detectron result: 
https://imgur.com/a/82RaXlH
and this repo result:
https://imgur.com/a/SFVTkXy

**Comment by fmassa** [comment]
@mehrdadazizi72 hi,

which pre-trained model file did you use to run the demo?
If you used any of the models from the `caffe2/` folder, then this should have loaded pre-trained models for detection.
If not, then the model that you downloaded was for classification, and not for detection, and needs to be pre-trained.

**Comment by mehrdadazizi72** [comment]
@fmassa thank you for the quick answer.
I use Caffe pre-train model (e2e_faster_rcnn_X_101_32x8d_FPN_1x_caffe2) but in image have many false positive detection for example this image:
https://imgur.com/a/A0Omjg6
is this because of it's not like pictures from COCO or anything else?

**Comment by fmassa** [comment]
This doesn't look good.


What's the image size that you use, do you use 800 as a size in https://github.com/facebookresearch/maskrcnn-benchmark/blob/d3fed42afe59910dd650308c426640d183d044b5/demo/webcam.py#L25-L31

**Comment by mehrdadazizi72** [comment]
the picture size is 2048*2048

**Comment by fmassa** [comment]
Can you specify it to be `800` in the `--min-image-size` field? The network was trained for some particular image sizes, and it might not see large objects because of that.

**Comment by mehrdadazizi72** [comment]
@fmassa sorry for the late answer
I set min-image-size to 800 and result get so much better
thanks for your help
