### ISSUE TITLE
How to perform multi-gpu testing?

### ISSUE THREAD

**Issue by mks0601** [facebookresearch/maskrcnn-benchmark#416]
## ❓ Questions and Help

Hi, thanks for sharing nice code.
Can you guys teach me how to perform multi-gpu testing? I tried the same code with the multi-gpu training in README, however it causes some bugs.

**Comment by fmassa** [comment]
Hi,

Multi-GPU testing happens by default when you run `tools/train_net.py`.

If you just want to perform multi-gpu inference, just run
```
python -m torch.distributed.launch --nproc_per_node=$NGPU tools/test_net.py --config-file /path/to/pre-trained/model.pth
```
