### ISSUE TITLE
question about parameter SOLVER.STEPS

### ISSUE THREAD

**Issue by lixingyi8947** [facebookresearch/maskrcnn-benchmark#417]
## ❓ Questions and Help
Sorry for bothering. Could someone explain what SOLVER.STEPS means? Thanks a lot!

**Comment by fmassa** [comment]
Hi,

`SOLVER.STEPS` is the list of iterations on which the learning rate will be decreased, with a multiplicative factor of `SOLVER.GAMMA`.

For example, in
https://github.com/facebookresearch/maskrcnn-benchmark/blob/1589ce0941c118dda90a8b134c8708b67f36cb5f/maskrcnn_benchmark/config/defaults.py#L278

every 30000 iterations we will multiply the learning rate by
https://github.com/facebookresearch/maskrcnn-benchmark/blob/1589ce0941c118dda90a8b134c8708b67f36cb5f/maskrcnn_benchmark/config/defaults.py#L277
