### ISSUE TITLE
How to run the Docker I have created

### ISSUE THREAD

**Issue by Idolized22** [facebookresearch/maskrcnn-benchmark#418]
## ❓ Questions and Help
I have built a docker as described in install.md running the following commands : 

`nvidia-docker build -t maskrcnn-benchmark --build-arg CUDA=9.2 --build-arg CUDNN=7 docker/  `

I am very new to ML and using dockers. 
I don't know using what command to run the docker I have created,
and then how to  train the Network on  coco2017 data-set. 

I have tried to follow the training instructions without giving any docker related command 
(in order to train on a single 1080TI GPU ) 
`

> python /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "/path/to/config/file.yaml"

`

 and when I run the following  command in the terminal i have received the following error: 

```
maskrcnn-benchmark-master/tools/train_net.py", line 8, in <module>
    from maskrcnn_benchmark.utils.env import setup_environment  # noqa F401 isort:skip
ModuleNotFoundError: No module named 'maskrcnn_benchmark'
```

**Comment by fmassa** [comment]
Do you need to use docker?
It looks like you didn't started the docker container nor ssh in it maybe?

I'd recommend as a starting point to just use `anaconda` and follow the standard installation instructions in `INSTALL.md`.

**Comment by fmassa** [comment]
Let me know if you have questions installing `maskrcnn-benchmark` using the installation instructions with `anaconda`

**Comment by Idolized22** [comment]
> Do you need to use docker?
> It looks like you didn't started the docker container nor ssh in it maybe?
> 
> I'd recommend as a starting point to just use `anaconda` and follow the standard installation instructions in `INSTALL.md`.

I didn't start the docker container nor ssh in it, because i don't know how to do it , 
do I need to start both , and using which commands ? 
 I do know that the docker has been created successfully as the terminal printed the following line
after executing the command : `nvidia-docker build -t maskrcnn-benchmark --build-arg CUDA=9.2 --build-arg CUDNN=7 docker/` 

At the button line the terminal printed: 
`Installed /maskrcnn-benchmark
Processing dependencies for maskrcnn-benchmark==0.1
Finished processing dependencies for maskrcnn-benchmark==0.1
Removing intermediate container fd39cdbee814
 ---> 0f5d39d2afe3
Step 19/19 : WORKDIR /maskrcnn-benchmark
 ---> Running in d795449ad722
Removing intermediate container d795449ad722
 ---> de71cd59f772
Successfully built de71cd59f772
` 


> Let me know if you have questions installing `maskrcnn-benchmark` using the installation instructions with `anaconda`

Thank you very much!

**Comment by fmassa** [comment]
You can try something like
```
docker run -it maskrcnn-benchmark /bin/bash
```
and then try running the commends from there.

Googling around for basic docker commands will be very useful in this case I believe

**Comment by Idolized22** [comment]
Thank you,  
I have manged to run the docker, 
How ever I have received the following error when i tried to  train : 

> `Traceback (most recent call last):
>   File "tools/train_net.py", line 172, in <module>
>     main()
>   File "tools/train_net.py", line 165, in main
>     model = train(cfg, args.local_rank, args.distributed)
>   File "tools/train_net.py", line 32, in train
>     model.to(device)
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 384, in to
>     return self._apply(convert)
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 190, in _apply
>     module._apply(fn)
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 190, in _apply
>     module._apply(fn)
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 190, in _apply
>     module._apply(fn)
>   [Previous line repeated 1 more time]
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 196, in _apply
>     param.data = fn(param.data)
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 382, in convert
>     return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
>     _check_driver()
>   File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
>     http://www.nvidia.com/Download/index.aspx""")
> AssertionError: 
> Found no NVIDIA driver on your system. Please check that you
> have an NVIDIA GPU and installed a driver from
> http://www.nvidia.com/Download/index.aspx
> `

**Comment by fmassa** [comment]
This is the same issue as https://github.com/facebookresearch/maskrcnn-benchmark/issues/167

I'd strongly recommend not using docker, but you could try the workarounds presented in the end of #167
