### ISSUE TITLE
generating instance label map at inference 

### ISSUE THREAD

**Issue by yaoliUoA** [facebookresearch/maskrcnn-benchmark#422]
Hi 

Given a trained mask-rcnn model, I want to geneate an instance label map at inference time, which encodes each instance with an unique label (background with label 0). It is not trivial as sometimes the segmentations generated from mask-rcnn can be overlapping, ie, one pixel can assigned to multiple instances.  Does this package support generating instance label map? Are there any functions in the package support this?

**Comment by fmassa** [comment]
Hi,

Check the demo that we have, in particular https://github.com/facebookresearch/maskrcnn-benchmark/blob/1589ce0941c118dda90a8b134c8708b67f36cb5f/demo/predictor.py#L274-L298

We don't guarantee that the pixels of the different objects is non-overlapping though.
This repo currently only addresses instance segmentation, and not panoptic segmentation.

**Comment by fmassa** [comment]
I'm closing this issue as we are tracking panoptic segmentation request in https://github.com/facebookresearch/maskrcnn-benchmark/issues/337
