### ISSUE TITLE
Multi-GPU training error

### ISSUE THREAD

**Issue by lixingyi8947** [facebookresearch/maskrcnn-benchmark#423]
## ❓ Questions and Help
I encountered the following error when I do the Multi-GPU Training. I used Cuda 9.0, should I upgrade to cuda 9.2?

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch-nightly_1549065344879/work/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

**Comment by fmassa** [comment]
This looks like a problem with your installation maybe.

Can you try uninstalling PyTorch and `maskrcnn-benchmark`, and reinstalling both?

**Comment by lixingyi8947** [comment]
You are right! I reinstalled everything and it works now. Thanks a lot!
