### ISSUE TITLE
support deformable convolution?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [facebookresearch/maskrcnn-benchmark#424]
hi @fmassa 
do u have a plan to add `deformable conv`?

**Comment by fmassa** [comment]
I don't currently have plans to add support for deformable convolutions, but PRs are very much welcome! :-)

**Comment by zimenglan-sysu-512** [comment]
#693

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/693 , thanks a lot @zimenglan-sysu-512 !
