### ISSUE TITLE
Adapt to large images

### ISSUE THREAD

**Issue by maxsenh** [facebookresearch/maskrcnn-benchmark#428]
## ❓ Questions and Help
Hi

I am trying to train a model now with my own dataset (3 classes + 1 background class), where I modified the checkpointer class and changed MODEL.ROI_BOX_HEAD.NUM_CLASSES to 4 following the issue [#166](https://github.com/facebookresearch/maskrcnn-benchmark/issues/166). 

My images are quite large (2048x2048) and my question is if you have any idea on how to chunk the images into smaller pieces together with not loosing the context to their annotation file(s)? Resizing the images might not be a big problem (image_slicer.slice(...)) but what about the annotation file? Maybe someone else already thought about that, but I could not find a related issue.

Thanks in advance

**Comment by fmassa** [comment]
Hi,

You could try cropping the images during data augmentation, making sure that each crop has at least one object.
But this wouldn't keep the context of the whole image.

I'd recommend just using smaller-sized images. By default, the training will happen on 800 pixels on the smallest size.
If your images are larger, they (and the annotations) will just be resized.
Does that work for you?

**Comment by maxsenh** [comment]
Hi, 
Thanks again for your answer! I am using images from fluorescence microscopy and my project is to segment nuclei and other cell compartments. The images come with that high resolution and I would like to keep it. 
What I was thinking now is to chunk the images first and save them in .npy format which would look like this
```
[[[86  1  0 ...  0  0  0]
  [88  1  0 ...  0  0  0]
  [85  1  0 ...  0  0  0]
  ...
  [20  0  0 ...  0  0  0]
  [20  0  0 ...  0  0  0]
  [21  0  0 ...  0  0  0]]

 [[86  1  0 ...  0  0  0]
  [86  1  0 ...  0  0  0]
  [86  1  0 ...  0  0  0]
  ...
  [20  0  0 ...  0  0  0]
  [20  0  0 ...  0  0  0]
  [21  0  0 ...  0  0  0]]

 [[85  1  0 ...  0  0  0]
  [87  1  0 ...  0  0  0]
  [86  1  0 ...  0  0  0]
  ...
  [20  0  0 ...  0  0  0]
  [20  0  0 ...  0  0  0]
  [21  0  0 ...  0  0  0]]

 ...

 [[59  0  0 ...  0  0  0]
  [58  0  0 ...  0  0  0]
  [59  0  0 ...  0  0  0]
  ...
  [32  0  0 ...  0  0  0]
  [31  0  0 ...  0  0  0]
  [32  0  0 ...  0  0  0]]

 [[59  0  0 ...  0  0  0]
  [57  0  0 ...  0  0  0]
  [59  0  0 ...  0  0  0]
  ...
  [33  0  0 ...  0  0  0]
  [31  0  0 ...  0  0  0]
  [32  0  0 ...  0  0  0]]

 [[61  0  0 ...  0  0  0]
  [62  0  0 ...  0  0  0]
  [61  0  0 ...  0  0  0]
  ...
  [34  0  0 ...  0  0  0]
  [33  0  0 ...  0  0  0]
  [31  0  0 ...  0  0  0]]]
.shape(1024,1024,9)  # the number 9 corresponds to the fact that there are 8 objects in the picture and the 1024 is the image size
```
I reused the code to generate these chunks from a previous project, where I was using [Mask R-CNN from Matterport](https://github.com/matterport/Mask_RCNN), because there I could feed the chunks straight into the model.
That would already contain masks and bounding boxes which I could maybe feed into the model with creating an own DatasetClass. In the COCODatasetClass, the variables which are returned are img (tensor with shape (3, 800, 800)), target (bboxes) and ids, correct? 
My question is whether it would make sense to either create a DatasetObject on my own or use the one provided and convert the .npy files back to images and re-create their annotation files?

**Comment by fmassa** [comment]
You can do both, creating a dataset is easy but if you stick with COCO format, you'll have the evaluation function already implemented, so I'll be overall easier I think.

**Comment by maxsenh** [comment]
Thank you! Sorry for my late reply. I am sticking to the COCO-format now and I chunked the images before into .npy files and could get it to work! I have another question about normalization of the images before feeding them into the model, but I will open another issue! Thanks
