### ISSUE TITLE
why model_serialization.strip_prefix_if_present not work when train multi gpu

### ISSUE THREAD

**Issue by kakaluote** [facebookresearch/maskrcnn-benchmark#432]
## ❓ Questions and Help
model_serialization.strip_prefix_if_present  remove the  'module.' prefix for each tensor in checkpoint,
i found it not work on multi gpu train, and fine on single gpu train( do not use torch.distributed.launch)

i want to finetune my model, so i should prevent some layer which depends on num_classes to restore from checkpoint.

**Comment by fmassa** [comment]
Can you explain a bit better why it doesn't work? It used to work when I wrote it.

**Comment by kakaluote** [comment]
oh, reply so quickly.
single gpu:
`2019-02-14 17:29:28,382 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn1.bias                  loaded from backbone.body.layer1.0.bn1.bias                  of shape (64,)
2019-02-14 17:29:28,382 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn1.running_mean          loaded from backbone.body.layer1.0.bn1.running_mean          of shape (64,)`


multi gpu:
`2019-02-14 17:29:28,382 maskrcnn_benchmark.utils.model_serialization INFO: module.backbone.body.layer1.0.bn1.bias                  loaded from backbone.body.layer1.0.bn1.bias                  of shape (64,)
2019-02-14 17:29:28,382 maskrcnn_benchmark.utils.model_serialization INFO: module.backbone.body.layer1.0.bn1.running_mean          loaded from backbone.body.layer1.0.bn1.running_mean          of shape (64,)
2019-02-14 17:29:28,382 maskrcnn_benchmark.utils.model_serialization INFO: module.backbone.body.layer1.0.bn1.running_var           loaded from backbone.body.layer1.0.bn1.running_var           of shape (64,)
2019-02-14 17:29:28,382 maskrcnn_benchmark.utils.model_serialization INFO: module.backbone.body.layer1.0.bn1.weight                loaded from backbone.body.layer1.0.bn1.weight                of shape (64,)
2019-02-14 17:29:28,383 maskrcnn_benchmark.utils.model_serialization INFO: module.backbone.body.layer1.0.bn2.bias                  loaded from backbone.body.layer1.0.bn2.bias                  of shape (64,)`
all tensor name begin with 'module.'

**Comment by kakaluote** [comment]
i fix my code like this, at model_serialization.py  line 50
`        if is_training and (key.startswith('roi_heads.box.predictor.cls_score') or key.startswith(
                'roi_heads.box.predictor.bbox_pred') or key.startswith('module.roi_heads.box.predictor.cls_score') or key.startswith(
                'module.roi_heads.box.predictor.bbox_pred')):
            logger.info('ignore ' + key)
            continue`

**Comment by fmassa** [comment]
Yes, we strip the `.module` prefix, but in https://github.com/facebookresearch/maskrcnn-benchmark/blob/13b4f82efd953276b24ce01f0fd1cd08f94fbaf8/maskrcnn_benchmark/utils/model_serialization.py#L12-L23
we align the state dict with the parameters that have been loaded.

I don't know what exactly is your use-case, but for all the models that we have currently the combination works fine.

**Comment by kakaluote** [comment]
emm,all i want to do is finetune model with different num_classes, i want to skip the roi_heads.box.predictor.cls_score and roi_heads.box.predictor.bbox_pred  layers, so i add code 

if  (key.startswith("roi_heads.box.predictor.cls_score") or 
key.startswith( "roi_heads.box.predictor.bbox_pred") or key.startswith('module.roi_heads.box.predictor.cls_score') or 
key.startswith( "module.roi_heads.box.predictor.bbox_pred")):  
&emsp;&emsp;logger.info('ignore ' + key)  
&emsp;&emsp;continue


at here https://github.com/facebookresearch/maskrcnn-benchmark/blob/13b4f82efd953276b24ce01f0fd1cd08f94fbaf8/maskrcnn_benchmark/utils/model_serialization.py#L48

i add  last 2 "or"，because the prefix 'module.' not removed when train multi gpu

**Comment by fmassa** [comment]
@kakaluote in this case, just remove those entries from the serialized state-dict, as discussed in https://github.com/facebookresearch/maskrcnn-benchmark#finetuning-from-detectron-weights-on-custom-datasets

**Comment by kakaluote** [comment]
great

**Comment by fmassa** [comment]
Cool, I'm closing this issue then, but let me know if you have further questions
