### ISSUE TITLE
Faster RCNN using ROI Pooling in maskrcnn-benchmark?

### ISSUE THREAD

**Issue by mr2901** [facebookresearch/maskrcnn-benchmark#433]
## ❓ Questions and Help
I want to use Faster RCNN for training with ROI Pooling.
I use this command:
 python tools/train_net.py --config-file "configs/e2e_faster_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 700000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1

I think the default setting is ROI Align instead of ROI Pooling.
How can i use ROI Pooling?

Thanks.

**Comment by fmassa** [comment]
Hi,

I hard-coded that we would use RoiAlign in https://github.com/facebookresearch/maskrcnn-benchmark/blob/13b4f82efd953276b24ce01f0fd1cd08f94fbaf8/maskrcnn_benchmark/modeling/poolers.py#L66-L68

If you want to use Roi Pool, just change that line with something like
```python
ROIPool(
    output_size, spatial_scale=scale
)
```
(and import `ROIPool` from `layers`) and it should be fine.

Additionally, you could add an extra config argument to select between `ROIPool` or `ROIAlign`.
