### ISSUE TITLE
Distributed sampler shuffle bug

### ISSUE THREAD

**Issue by adrifloresm** [facebookresearch/maskrcnn-benchmark#437]
## 🐛 Bug
The initialization of the shuffle variable in the distributed shuffler is hard-coded to True. 

https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/samplers/distributed.py#L40

switch from:
`self.shuffle = True`

to
`self.shuffle = shuffle`

**Comment by fmassa** [comment]
Great point!

Could you send a PR fixing it?

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/438
