### ISSUE TITLE
fatal error: torch/extension.h

### ISSUE THREAD

**Issue by lz20061213** [facebookresearch/maskrcnn-benchmark#44]
## ❓ Questions and Help
Hello greate guys,
I followed the installation instructions in INSTALL.md with a little modification by install pythoch through pip.
But when I run the final command to install the pytorch detection, it gave me a  `fatal error: torch/extension.h: No such file or directory.`
Then I found that there has a `torch/torch.h` file in INCLUDE_PATH (site-packages/torch/lib/include/), which its content is same as the `torch/extension.h` found in the pytorch source codes.
However, there still has some missing files after I changed `torch/extension.h` to `torch/torch.h`, such like `ATen/cuda/CUDAContext.h`.

Follows are my installation commands:
$ virtualenv -p python3 maskrcnn-benchmark
$ source maskrcnn-benchmark/bin/activate
$ pip install ipython ninja yacs cython matplotlib
$ pip install http://download.pytorch.org/whl/cu80/torch-0.4.1-cp35-cp35m-linux_x86_64.whl
$ pip install torchvision
then follows the install pycocotools and pytorch detection.

Is the installation wrong?

**Comment by lz20061213** [comment]
torch_nightly?

**Comment by huazai-1994** [comment]
hey guy.I have met the same problem too.Have you found the right way to fix it ?thanks a lot

**Comment by lz20061213** [comment]
I think we should install torch_nightly, not the stable one.

**Comment by fmassa** [comment]
Yes, you should install the preview (nightly) version of PyTorch, which corresponds to PyTorch 1.0

I'm closing the issue, but let me know if you still have issues even after installing the nightly version

**Comment by Elena-ssq** [comment]
Hi, I've already installed pytorch-nightly using:
"conda install --use-local name_of_pytorch-nightly_version_1.0.0.whl"
And I can see pytorch-nightly is successfully installed through "conda list".
However, when I import torch and print version, the result is still "0.4.0"(my orignial version).

How can I cover the old version with newly installed pytorch-nightly? Please help.
