### ISSUE TITLE
How to train on keypoints?

### ISSUE THREAD

**Issue by renebidart** [facebookresearch/maskrcnn-benchmark#441]
## ❓ Questions and Help

When I try to run:
python tools/train_net.py --config-file "configs/e2e_keypoint_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1

I get this error:
size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).

Is this because the pre-trained model is made for localization with 81 classes? What would be the best way to get around this without having the proper pre-trained model?

Thanks!

**Comment by fmassa** [comment]
Hi,

You are probably running the training job in the same directory as where there is an already existing checkpoint from a previous run (from detection on 81 classes).

Can you change the `OUTPUT_DIR` from the keypoint config to point to a different folder?

**Comment by renebidart** [comment]
Thanks! I had forgotten to change it.

**Comment by my-hello-world** [comment]
@renebidart  @fmassa hi, I train on single GPU. What would be the best max_iters or parameters to train on keypoints?
maybe like:
```
SOLVER.IMS_PER_BATCH:2 
SOLVER.BASE_LR: 0.0025 
SOLVER.MAX_ITER: 720000 
SOLVER.STEPS: (480000, 640000)  
TEST.IMS_PER_BATCH: 1
```
