### ISSUE TITLE
is the training setting same as default Mask R-CNN 1×training setting?

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#442]

**Comment by fmassa** [comment]
Can you expand on your question?

If I understand your question correctly, then yes, the training setting in this repo for Mask R-CNN is the same as the one for Detectron, using the 1x schedule.

**Comment by JoyHuYY1412** [comment]
Yes, I mean the 1×training setting for MaskRCNN in Detectron. Thank you~
