### ISSUE TITLE
Attribute Error: RETINANET_ON

### ISSUE THREAD

**Issue by akshitac8** [facebookresearch/maskrcnn-benchmark#446]
I am not able to run the code again today because of the Attribute Error. But RETINANET_ON is defined in the config file and still not loading.

![screenshot from 2019-02-16 16-43-57](https://user-images.githubusercontent.com/21353757/52900004-5514d080-320a-11e9-93e9-a53ef07cc3df.png)

**Comment by fmassa** [comment]
Hi,

This is a bit weird, I've just launched a few trainings with latest master and it works fine for me.

I suppose there might be some conflict in your repo that didn't pick all the changes, can you verify?

**Comment by akshitac8** [comment]
Thank you, Now the code is working for me :slightly_smiling_face:
