### ISSUE TITLE
detectron dependency in tools

### ISSUE THREAD

**Issue by botcs** [facebookresearch/maskrcnn-benchmark#447]
## 🐛 Bug
As suggested in the [data/README.md](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/README.md) `tools/convert_cityscapes_to_coco.py` requires detectron to be installed.

## To Reproduce

1. Install `maskrcnn_benchmark` following the INSTALL.md
1. Install additional dependencies for the script: `pip install h5py scipy opencv-python`
1. run `python tools/cityscapes/convert_cityscapes_to_coco.py`

### Error:
`ModuleNotFoundError: No module named 'detectron'`

## Environment
PyTorch version: 1.0.0.dev20190207
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080
GPU 1: GeForce RTX 2080

Nvidia driver version: 410.72
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.1
[pip] torch==1.0.0.dev20190207
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch-nightly           1.0.0.dev20190207 py3.6_cuda10.0.130_cudnn7.4.2_0    pytorch

**Comment by fmassa** [comment]
Oh, you are totally right, thanks for spotting this!

The dependency on Detectron is really not necessary, and was probably an oversight from #232 

There are only a couple of places where detectron is needed, and only two functions are used, see https://github.com/facebookresearch/maskrcnn-benchmark/blob/e60f4ec8dc50531debcfd5ae671ea167b5b7a1d9/tools/cityscapes/convert_cityscapes_to_coco.py#L196-L198

We already have something similar to `bboxs_util.xyxy_to_xywh` in `BoxList` via the `convert` method. The second function can be taken from Detectron to avoid this dependency.

Contributions are more than welcome! :-)

**Comment by botcs** [comment]
I have looked into the 

> Oh, you are totally right, thanks for spotting this!
> 
> The dependency on Detectron is really not necessary, and was probably an oversight from #232
> 
> There are only a couple of places where detectron is needed, and only two functions are used, see
> 
> [maskrcnn-benchmark/tools/cityscapes/convert_cityscapes_to_coco.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/e60f4ec8dc50531debcfd5ae671ea167b5b7a1d9/tools/cityscapes/convert_cityscapes_to_coco.py#L196-L198)
> 
> Lines 196 to 198 in [e60f4ec](/facebookresearch/maskrcnn-benchmark/commit/e60f4ec8dc50531debcfd5ae671ea167b5b7a1d9)
>  ann['bbox'] = bboxs_util.xyxy_to_xywh( 
>      segms_util.polys_to_boxes( 
>          [ann['segmentation']])).tolist()[0] 
> 
> We already have something similar to `bboxs_util.xyxy_to_xywh` in `BoxList` via the `convert` method. The second function can be taken from Detectron to avoid this dependency.
> 
> Contributions are more than welcome! :-)

**Comment by fmassa** [comment]
Actually, I'd like to keep this open until the dependency on detectron is removed.

**Comment by botcs** [comment]
sorry, I have closed it accidentally.
I have a new PR on the detectron free implementation :)
