### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by langjiliang** [facebookresearch/maskrcnn-benchmark#450]
I have a question. Have you ever met it? Thank you in advance. RuntimeError: copy_if failed to synchronize: device-side assert triggered

**Comment by langjiliang** [comment]
Thank you. I have solved this problem._C.MODEL.ROI_BOX_HEAD.NUM_CLASSES = 22.
I gave it a wrong value.

**Comment by fmassa** [comment]
Cool, great that you managed to fix your problem!

**Comment by nicklausZJF** [comment]
> Thank you. I have solved this problem._C.MODEL.ROI_BOX_HEAD.NUM_CLASSES = 22.
> I gave it a wrong value.

I also meet the error, how to fix it ? What is `_C.MODEL.ROI_BOX_HEAD.NUM_CLASSES` ?

**Comment by VinACE** [comment]
I had five classes, I added + 1  on the defaults.py file  _C.MODEL.ROI_BOX_HEAD.NUM_CLASSES = 6

**Comment by HardysJin** [comment]
That's probably because the category id is staring from 1 instead of 0. `0 <= category_id < NUM_CLASSES`
