### ISSUE TITLE
need help for explaining the output loss

### ISSUE THREAD

**Issue by lixingyi8947** [facebookresearch/maskrcnn-benchmark#453]
## ❓ Questions and Help
Hi, when the training starts, I got loss info below. I found every there is a parentheses with a number included following after every loss, like loss: 0.3502 (0.3666). May I ask what does '(0.3666)' mean? Thanks a lot!

maskrcnn_benchmark.trainer INFO: eta: 12:09:25  iter: 60  loss: 0.3502 (0.3666)  loss_box_reg: 0.0919 (0.0962)  loss_classifier: 0.2111 (0.2162)  loss_objectness: 0.0264 (0.0290)  loss_rpn_box_reg: 0.0211 (0.0252)  time: 0.4228 (0.4866)  data: 0.0123 (0.0657)  lr: 0.004120  max mem: 5558

**Comment by LeviViana** [comment]
It stands for its median and global average. You can check it here: https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/utils/metric_logger.py#L64

**Comment by fmassa** [comment]
That's precisely what @LeviViana mentioned: it stands for the median (over the last 20 iterations) and the global average (since the beginning of the training).
