### ISSUE TITLE
AttributeError: nms

### ISSUE THREAD

**Issue by xelmirage** [facebookresearch/maskrcnn-benchmark#454]
I'm trying to do some modification on the original code. So I want to run the maskrcnn_benchmark code directly from the source dir instead of installing it as a package, then I can use pycharm to debug the code.

But when I run the train_net.py, the error shows as:

    tools/train_net.py:None (tools/train_net.py)

    tools/train_net.py:18: in <module>

    from maskrcnn_benchmark.engine.inference import inference

    maskrcnn_benchmark/engine/inference.py:10: in <module>

    from maskrcnn_benchmark.data.datasets.evaluation import evaluate

    maskrcnn_benchmark/data/datasets/evaluation/__init__.py:3: in <module>

    from .coco import coco_evaluation

    maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py:1: in <module>

    from .coco_eval import do_coco_evaluation

    maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py:10: in <module>

    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou

    maskrcnn_benchmark/structures/boxlist_ops.py:6: in <module>

    from maskrcnn_benchmark.layers import nms as _box_nms

    maskrcnn_benchmark/layers/__init__.py:8: in <module>

    from .nms import nms

    maskrcnn_benchmark/layers/nms.py:5: in <module>

    nms = _C.nms

    /anaconda3/envs/mrcnn/lib/python3.7/site-packages/yacs/config.py:115: in __getattr__

    raise AttributeError(name)

    E   AttributeError: nms

When installed the code as a package, the error doesn't show up and the net was trained well. 

What's weird is, I searched all around the code dir and found nowhere has the definition of `_C.nms`:
![image](https://user-images.githubusercontent.com/2993178/52953499-9cde5800-33c2-11e9-943e-785fdeee9806.png)

Now I'm wondering where the `_C.nms` is declared and why it only exists in the installed package.... or if I have no choice but run the code as installed package, is there anyway for me to debug the maskrcnn_benchmark code?

Thank everyone's help!

**Comment by fmassa** [comment]
Hi,

`_C` is an extension that is implemented in C++/CUDA, and needs to be compiled. Thus, you need to at least compile `maskrcnn-benchmark` once, so that the `_C.so` gets generated.

I'd recommend you installing `maskrcnn-benchmark` using `python setup.py build develop`, this way you can modify the python files without having to re-install everything. I believe if you set the right paths in PyCharm you'll be able to debug things properly.

**Comment by xelmirage** [comment]
Got it, thank you for your help :)
