### ISSUE TITLE
 I need no empty data in'bbox'in the JSON file，but have an error,   Do you know how to solve it? Thank you in advance.ValueError: No ground-truth boxes available for one of the images.

### ISSUE THREAD

**Issue by langjiliang** [facebookresearch/maskrcnn-benchmark#459]

**Comment by fmassa** [comment]
I think what might happen is that you might have an invalid bbox, for example with width/height less than one, or outside of the image. This image will get filtered by the dataset.
Can you check that?

**Comment by langjiliang** [comment]
Thank you sincerely.I have solve it.But I had another problem.
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCTensorMathCompare.cuh:82
.I hope to get your help.

**Comment by fmassa** [comment]
You maybe have an index in your dataset that is outside of the range defined in `NUM_CLASSES`?

**Comment by langjiliang** [comment]
Thank you so much for your answer. I have solved this problem according to your guidance. Thank you sincerely.

**Comment by fmassa** [comment]
Great to hear that you managed to fix your issue!
