### ISSUE TITLE
untimeError: Not compiled with GPU support (nms at ./maskrcnn_benchmark/csrc/nms.h:22)

### ISSUE THREAD

**Issue by zxphistory** [facebookresearch/maskrcnn-benchmark#46]
## ❓ Questions and Help
Why I can not compile gpu version nms following instructions?

**Comment by fmassa** [comment]
Did you compile the library on a machine with GPU?

Also, can you print the value of

```
from torch.utils.cpp_extension import CUDA_HOME
print(CUDA_HOME)
```

**Comment by zxphistory** [comment]
I have solved the problem, cause multiple versions of cuda exists. While it does not report errors/warnings during compile. Thanks!

**Comment by fmassa** [comment]
Great, let me know if you have other problems

**Comment by THuang001** [comment]
> I have solved the problem, cause multiple versions of cuda exists. While it does not report errors/warnings during compile. Thanks!


hello ,can you tell me how to solve this problems in detail？I meet the same problem and have no idea to solve it.

**Comment by fmassa** [comment]
@THuang001 check if the machine where you compiled `maskrcnn-benchmark` is the same as the one you are running it, and if there is a GPU in the machine that you used to compile it.

**Comment by luoyuxuan0528** [comment]
> @THuang001 check if the machine where you compiled `maskrcnn-benchmark` is the same as the one you are running it, and if there is a GPU in the machine that you used to compile it.

I have the same error when install maskrcnn-benchmark in docker mode. I re-compile maskrcnn-benmark after the docker image has been created. Then it works!

**Comment by thanujraju** [comment]
> > @THuang001 check if the machine where you compiled `maskrcnn-benchmark` is the same as the one you are running it, and if there is a GPU in the machine that you used to compile it.
> 
> I have the same error when install maskrcnn-benchmark in docker mode. I re-compile maskrcnn-benmark after the docker image has been created. Then it works!

Have you figured out a way to make it work from docker ?

**Comment by kangyisheng123456** [comment]
> > 我已经解决了问题，导致存在多个版本的cuda。虽然它不会在编译过程中报告错误/警告。谢谢！
> 
> 您好，您能告诉我如何详细解决此问题吗？我遇到同样的问题，不知道如何解决。


> > I have solved the problem, cause multiple versions of cuda exists. While it does not report errors/warnings during compile. Thanks!
> 
> hello ,can you tell me how to solve this problems in detail？I meet the same problem and have no idea to solve it.
can you tell me how to solve this problems in detail？I meet the same problem and have no idea to solve it.
