### ISSUE TITLE
My test_net got all 0 as result

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#462]
## ❓ Questions and Help
I used the coco_2017_val dataset from coco website, and I also changed the param in paths_catalog.py.
But when I run `python tools/test_net.py  --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml"`,
the reult AP for bbox and seg are all 0.
Do you have any idea?

**Comment by JoyHuYY1412** [comment]
I checked my inference/bbox.json and segm.json, and find the scores predicted for bounding boxes are very low, like around 0.05.
But I cannot see what's wrong in this process, do I need to change  the test_net.py?

**Comment by JoyHuYY1412** [comment]
I made a really silly mistake. The config-file should be "configs/caffe2/e2e_mask_rcnn_R_50_FPN_1x_caffe2.yaml"  instead. I will close issue.

**Comment by fmassa** [comment]
Great that you found the issue!

Indeed, the `configs/e2e_mask_rcnn_R_50_FPN_1x.yaml` file has not been pre-trained for detection on COCO, and is meant to be used for training.
