### ISSUE TITLE
how could I track the shape of blob like Detectron?

### ISSUE THREAD

**Issue by liuliu66** [facebookresearch/maskrcnn-benchmark#470]
## ❓ Questions and Help
Hi, I'd like to track and see the shape of each blob during training. Similar to Detectron, the shape of every blob in each layer (operation) could be shown in the first iteration. It is very helpful to check whether the network is running well. So is there any way to see the same thing in maskrcnn-benchmark?

**Comment by fmassa** [comment]
You can put prints in the code to output the shapes during forward maybe?

There is no graph construction step in PyTorch, as every image can be of potentially different sizes, so you'd need to do something in the forward to be able to get this.
