### ISSUE TITLE
Segmentation mask generated contains strings and letters at count keyword

### ISSUE THREAD

**Issue by akshitac8** [facebookresearch/maskrcnn-benchmark#471]
At evaluation time, The segmentation json file generated contains buffered strings and letters at ```count``` keyword.
Example:
```
{'size': [800, 800], 'counts': b'coa;<1E_h0b0M0O2O000O10000000000000001OO1000000000000000000000000000O1000000000000000000000000001O0000001N1000001O00001N101O0O1O2O2K]b^6'}

```

**Comment by akshitac8** [comment]
I followed the code given at #150 But then I got 
```
if not isinstance(segms[0], (list, Polygons)):
IndexError: list index out of range
```

**Comment by fmassa** [comment]
Hi,

I suppose you managed to fix the issue?
You were checking the `rle` encoding of the mask, instead of the polygons. Those are generally the encodings for `crowd` categories

**Comment by Jinksi** [comment]
On this topic, how do I extract polygon data after eval?
`segm.json` contains `counts` but no polygon.
Am I missing something?

**Comment by shaayaansayed** [comment]
+1, does segm.json not store the polygon/mask prediction?

**Comment by shaayaansayed** [comment]
@Jinksi you can use this to decode RLE string to mask: 
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py#L87

pass in the dict stored in the segmentation key

**Comment by Jinksi** [comment]
@shaayaansayed Good one, thanks.  
I combined this with @jsbroks [`imantics`](https://github.com/jsbroks/imantics) to convert the decoded mask to a segmentation polygon:
```
from imantics import Mask
def maskToPolygon(mask):
    polygons = Mask(mask).polygons()
    return polygons.segmentation
```
It could be good to add this to `segm.json` by default, but it adds to filesize.

**Comment by jsbroks** [comment]
Another way to do  this:
```python
from imantics import Polygons
def maskToPolygon(mask):
    return Polygons.from_mask(mask).segmentation
```
both do the same thing, just though I would share.

@Jinksi If you would like RLE support added to the library, post a feature request under the issues

**Comment by AmberHen** [comment]
Is your problem solved? I have the same problem.

**Comment by wangg12** [comment]
Binary mask to polygons can not guarantee correctness by naively finding contours. 

For example, a donut-like mask:  binary mask --> polygons(contours) --> binary mask(decode), the hole in the mask will disappear. 

Thus I would recommend not to convert any of binary mask or RLE back to polygons.

**Comment by AmberHen** [comment]
> Binary mask to polygons can not guarantee correctness by naively finding contours.
> 
> For example, a donut-like mask: binary mask --> polygons(contours) --> binary mask(decode), the hole in the mask will disappear.
> 
> Thus I would recommend not to convert any of binary mask or RLE back to polygons.

你好  我在inference里输出来的counts和上边一样 我应该怎么把这些轮廓线画到原图上 这样直观地看到分割的效果。
