### ISSUE TITLE
Best way to support bbox without keypoints?

### ISSUE THREAD

**Issue by adizhol** [facebookresearch/maskrcnn-benchmark#476]
## ❓ Questions and Help
Hi,

Thanks you for the merging support for the keypoints-head!
What would be the best way to support bboxes without keypoints? (For a custom dataset)

Thanks

**Comment by fmassa** [comment]
Hi,

There is no difference compared to what we had before.
Just make sure your dataset doesn't have the `keypoint` field and it should work as before.

**Comment by adizhol** [comment]
@fmassa 
hmm... I appologize if I weren't clear, but I meant to ask what if some classes don't have keypoints (i.e "persons" class with keypoints and "cars" without)?

**Comment by fmassa** [comment]
This is currently not supported, but should be doable by modifying the keypoint head to only be applied to instances that have keypoints.
