### ISSUE TITLE
KeyError: 'bbox' , self created dataset 

### ISSUE THREAD

**Issue by Idolized22** [facebookresearch/maskrcnn-benchmark#480]
## ❓ Questions and Help

I have used [labelme](https://github.com/wkentaro/labelme#anaconda) tool which was created  to create my own cocolike dataset  and solved few Bugs there.
My Data annotations doesn't have a field BBOX , which is probably why i received this key error: 

 ```
 ./maskrcnn_benchmark/data/datasets/coco.py", line 18, in <genexpr>
    return all(any(o <= 1 for o in obj["bbox"][2:]) for obj in anno)

KeyError: 'bbox' 

```

my data uses iscrowded =1, 
And I have few  Questions  in order to solve this bug: 

1. does each element of  the segmentation field  under annotations refers to x ,y x,y  dots of the polygon on  the original image size? 
 I am asking because some of the mask has been created on a 4k images  , and some on 640*480 .
2. How can I convert the encoded segmentation to the dots used to create the polygon in order to compute the BoundingBoxes ? 
  
Thank You Very Much

**Comment by fmassa** [comment]
Hi,

In this particular case, I'd recommend you removing that condition, i.e., commenting those lines
https://github.com/facebookresearch/maskrcnn-benchmark/blob/539b132217772c1157fd7ce7c9eb29889f477d63/maskrcnn_benchmark/data/datasets/coco.py#L26-L27

If your data uses iscrowded=1, I suppose that you only have RLE encodings and not polygons, right?

In this case, I'd use the PR that adds supports for `masks` in `maskrcnn-benchmark`, see #150 and #473 

For point 1, it refers to the original image size, whatever it is. Once the images get rescaled in the codebase, the masks will get rescaled accordingly.

**Comment by Idolized22** [comment]
I have manged to get the bounding boxes of my dataset and I might be able to save the polygons dots, 
however in case something goers wrong, can you please tell me how  do clone the edits made by 473 ( is there an other way but to paste the code from there into the code in my computer ? )

**Comment by fmassa** [comment]
@Idolized22 you can just checkout the branch from 473
```
git remote add botcs https://github.com/botcs/maskrcnn-benchmark
git fetch --all
git checkout pr150
```
or something like that
