### ISSUE TITLE
how to convert this model to tensorflow?

### ISSUE THREAD

**Issue by 95xueqian** [facebookresearch/maskrcnn-benchmark#481]
## ❓ Questions and Help
I want to train a model in pytorch, but for inference , it must be ran in tensorflow, how to convert both model and parameters to tensorflow?

**Comment by fmassa** [comment]
Hi,

It might not be easy to convert it to TensorFlow.
You can try using ONNX to export the model, but I believe not all the operations we need are available in ONNX.

One thing you could try would be to try to use #138 to export the model and run it in libtorch?

I don't think there are better solutions for now though.
