### ISSUE TITLE
Help me with the  python code?

### ISSUE THREAD

**Issue by Fighting-JJ** [facebookresearch/maskrcnn-benchmark#485]
## ❓ Questions and Help
 
I just wonder where the function bellow is called ????

@registry.BACKBONES.register("R-50-C4")
@registry.BACKBONES.register("R-50-C5")
@registry.BACKBONES.register("R-101-C4")
@registry.BACKBONES.register("R-101-C5")
def build_resnet_backbone(cfg):
    body = resnet.ResNet(cfg)
    model = nn.Sequential(OrderedDict([("body", body)]))
    model.out_channels = cfg.MODEL.RESNETS.BACKBONE_OUT_CHANNELS
    return model

whitout  the function  "def build_resnet_backbone(cfg):" called, how can the function: build_backbone pass success ???

def build_backbone(cfg):
    assert cfg.MODEL.BACKBONE.CONV_BODY in registry.BACKBONES, \
        "cfg.MODEL.BACKBONE.CONV_BODY: {} are not registered in registry".format(
            cfg.MODEL.BACKBONE.CONV_BODY
        )
    return registry.BACKBONES[cfg.MODEL.BACKBONE.CONV_BODY](cfg)

So, can anyone tell me where the registry.BACKBONES is registered ??

**Comment by Fighting-JJ** [comment]
@fmassa

**Comment by fmassa** [comment]
The registry is created in
https://github.com/facebookresearch/maskrcnn-benchmark/blob/539b132217772c1157fd7ce7c9eb29889f477d63/maskrcnn_benchmark/modeling/registry.py#L5-L12
and registered in several places in the code, for example in
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/backbone.py#L12-L15
and
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fbnet.py#L96

**Comment by Fighting-JJ** [comment]
> The registry is created in
> [maskrcnn-benchmark/maskrcnn_benchmark/modeling/registry.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/539b132217772c1157fd7ce7c9eb29889f477d63/maskrcnn_benchmark/modeling/registry.py#L5-L12)
> 
> Lines 5 to 12 in [539b132](/facebookresearch/maskrcnn-benchmark/commit/539b132217772c1157fd7ce7c9eb29889f477d63)
> 
>  BACKBONES = Registry() 
>  RPN_HEADS = Registry() 
>  ROI_BOX_FEATURE_EXTRACTORS = Registry() 
>  ROI_BOX_PREDICTOR = Registry() 
>  ROI_KEYPOINT_FEATURE_EXTRACTORS = Registry() 
>  ROI_KEYPOINT_PREDICTOR = Registry() 
>  ROI_MASK_FEATURE_EXTRACTORS = Registry() 
>  ROI_MASK_PREDICTOR = Registry() 
> 
> and registered in several places in the code, for example in
> https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/backbone.py#L12-L15
> and
> https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fbnet.py#L96

Thanks for your answer.  But when the first time the function "build_backbone(cfg)" was called，
 def build_backbone(cfg):
    assert cfg.MODEL.BACKBONE.CONV_BODY in registry.BACKBONES, \
        "cfg.MODEL.BACKBONE.CONV_BODY: {} are not registered in registry".format(
            cfg.MODEL.BACKBONE.CONV_BODY
        )
    return registry.BACKBONES[cfg.MODEL.BACKBONE.CONV_BODY](cfg)

the registry.BACKBONES is empyt . So what I really want to know is in which or wehre the registry.BACKBONES was feed with new value during the execution of the file "tools/train_net.py".

addtion: I know the func such as the function below can add new value in to  registry.BACKBONES, but i do not know where the build_resnet_backbone was called in the  Sequential execution of  train_net.py.
@registry.BACKBONES.register("R-50-C4") 
@registry.BACKBONES.register("R-50-C5")
@registry.BACKBONES.register("R-101-C4")
@registry.BACKBONES.register("R-101-C5")
def build_resnet_backbone(cfg):
    body = resnet.ResNet(cfg)
    model = nn.Sequential(OrderedDict([("body", body)]))
    model.out_channels = cfg.MODEL.RESNETS.BACKBONE_OUT_CHANNELS
    return model

**Comment by fmassa** [comment]
@Fighting-JJ I'm not sure I understand your question.

In `build_backbone`, all the backbones have already been registered.
And `build_ backbone` is called in https://github.com/facebookresearch/maskrcnn-benchmark/blob/f40f29931c7d68da696168d8fdf7332281de28a9/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py#L29
which in turns gets called when we create the detection model
https://github.com/facebookresearch/maskrcnn-benchmark/blob/f40f29931c7d68da696168d8fdf7332281de28a9/maskrcnn_benchmark/modeling/detector/detectors.py#L8-L10

**Comment by Fighting-JJ** [comment]
> @Fighting-JJ I'm not sure I understand your question.
> 
> In `build_backbone`, all the backbones have already been registered.
> And `build_ backbone` is called in
> 
> [maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/f40f29931c7d68da696168d8fdf7332281de28a9/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py#L29)
> 
> Line 29 in [f40f299](/facebookresearch/maskrcnn-benchmark/commit/f40f29931c7d68da696168d8fdf7332281de28a9)
> 
>  self.backbone = build_backbone(cfg) 
> 
> which in turns gets called when we create the detection model
> [maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/f40f29931c7d68da696168d8fdf7332281de28a9/maskrcnn_benchmark/modeling/detector/detectors.py#L8-L10)
> 
> Lines 8 to 10 in [f40f299](/facebookresearch/maskrcnn-benchmark/commit/f40f29931c7d68da696168d8fdf7332281de28a9)
> 
>  def build_detection_model(cfg): 
>      meta_arch = _DETECTION_META_ARCHITECTURES[cfg.MODEL.META_ARCHITECTURE] 
>      return meta_arch(cfg)

Sorry for my poor English, the question I describe is not so clearly.
I kown what you said. 
Regisery is "dict" with value "module_name: module", and `BACKBONES = Registry()` will instantiate the BACKBONES. Then the BACKBONES is empty.

> In `build_backbone`, all the backbones have already been registered.
what you means by registered? instantiation or add values( "module_name: module")?

and when the build_backbone is called, the "dict" BACKBONES is empty.  
https://github.com/facebookresearch/maskrcnn-benchmark/blob/f40f29931c7d68da696168d8fdf7332281de28a9/maskrcnn_benchmark/modeling/backbone/backbone.py#L74-L79

So I really want to know in which file the "dict" BACKBONES is feed with new value.
value means  "module_name: module".

**Comment by fmassa** [comment]
> what you means by registered? instantiation or add values( "module_name: module")?

I mean that the classes are present in the dict, but they haven't been instantiated yet.


> and when the build_backbone is called, the "dict" BACKBONES is empty.

I just added a print after this assert, and it printed the following
```
{'R-101-C5': <function build_resnet_backbone at 0x124ae9840>, 'R-101-C4': <function build_resnet_backbone at 0x124ae9840>, 'R-50-C5': <function build_resnet_backbone at 0x124ae9840>, 'R-50-C4': <function build_resnet_backbone at 0x124ae9840>, 'R-152-FPN': <function build_resnet_fpn_backbone at 0x124ae97b8>, 'R-101-FPN': <function build_resnet_fpn_backbone at 0x124ae97b8>, 'R-50-FPN': <function build_resnet_fpn_backbone at 0x124ae97b8>, 'R-101-FPN-RETINANET': <function build_resnet_fpn_p3p7_backbone at 0x124ae9730>, 'R-50-FPN-RETINANET': <function build_resnet_fpn_p3p7_backbone at 0x124ae9730>, 'FBNet': <function add_conv_body at 0x124b65730>}
```
showing that `BACKBONES` is not empty.

Also, did you install everything following the installation instructions in `INSTALL.md`, i.e., by calling `python setup.py build develop`?

**Comment by zoom1539** [comment]
@Fighting-JJ， do you find where the "dict" BACKBONES is feed with new value ?

**Comment by Fighting-JJ** [comment]
> @Fighting-JJ， do you find where the "dict" BACKBONES is feed with new value ?

Long time ago,  so I almost forgot whether I once found the "dict" BACKBONES feed with new value.

**Comment by zoom1539** [comment]
@Fighting-JJ， ok, thanks. There's no need to feed with new value. The code used the decorator in python to create a callback function
