### ISSUE TITLE
support for the pretrained weights in Detectron

### ISSUE THREAD

**Issue by 1Konny** [facebookresearch/maskrcnn-benchmark#49]
Hi, thanks for this great repo.

I wonder if you have any plan to support the use of the pretrained weights provided in [Detectron Model_ZOO](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md)

**Comment by fmassa** [comment]
Hi,

We already support pre-trained weights from Detectron,  see for example the caffe2 folder in configs.

Let me know of you have more questions
