### ISSUE TITLE
Would it be better to show multiple progress bar in testing stage?

### ISSUE THREAD

**Issue by yelantingfeng** [facebookresearch/maskrcnn-benchmark#493]
## 🚀 Feature
In testing stage, only one progress bar is shown at the bottom. The update of each process overwrite other processes, which looks a little chaotic. Actually, by adding one `position` parameter to the tqdm call, we could show multiple progress bars in parallel.
The effect is as follows.
![image](https://user-images.githubusercontent.com/22748802/53400259-6dde6c80-39e8-11e9-9916-0a615575ddfd.png)

**Comment by fmassa** [comment]
Sure, this looks like a nice contribution!

**Comment by yelantingfeng** [comment]
After using it for serveral hours,  I found that the effect was not perfect. There will be some redundant lines shown at the bottom, which I think is about the parallelism safety of tqdm.
![image](https://user-images.githubusercontent.com/22748802/53493605-afe5dc00-3ad6-11e9-9e21-1eef05636b60.png)
I would reopen this issue once the problem is fixed.

**Comment by fmassa** [comment]
Sounds good, thanks for the update!
