### ISSUE TITLE
How to get data output from inference? 

### ISSUE THREAD

**Issue by innerop** [facebookresearch/maskrcnn-benchmark#496]
Hey there,

Instead of getting an image that is overlyed with predictions, can we get a JSON with coordinates of the enclosing box and the type of object detected?

That seems like a very basic expectation for automated monitoring of premises and other applications. 

Any hints and tips you may have will be appreciated.

**Comment by LeviViana** [comment]
The model output is actually an object of the type `BoxList`. You can get the result information by doing something like :

```bash
output = model(image)
# Bounding boxes
boxes = output.bbox 
# Labels
labels = output.get_field("labels")
# Scores
scores = output.get_field("scores") 
```
You then can customize your JSON as you wish.

**Comment by fmassa** [comment]
Thanks for the explanation @LeviViana !
