### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by zabatani** [facebookresearch/maskrcnn-benchmark#50]
## 🐛 Bug

Hi,

When trying to run the exact same code that appear in the notebook: demo/Mask_R-CNN_demo.ipynb
I'm getting a segmentation fault error caused by this line:

`predictions = coco_demo.run_on_opencv_image(image)`

Any idea why?

## Environment

PyTorch version: 1.0.0.dev20181028
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 375.39
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn.so.5.0.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.15.3)
[pip] torch (1.0.0.dev20181028)
[pip] torchvision (0.2.1)
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] pytorch-nightly           1.0.0.dev20181028 py3.6_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch

**Comment by fmassa** [comment]
Hi,

This is the exact same issue as https://github.com/facebookresearch/maskrcnn-benchmark/issues/21

The problem you are having is that you are using GCC 4.8. But gcc 4.8 is ABI incompatible with PyTorch.

While compiling the extensions you probably saw a warning like

```
Your compiler (g++ 4.8) may be ABI-incompatible with PyTorch! Please use a compiler that is ABI-compatible with GCC 4.9 and above. See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html. See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6 for instructions on how to install GCC 4.9 or higher. 
```

The solution is to upgrade to gcc 4.9 or higher following the instructions in https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6

I've also added some more information in the TROUBLESHOOTING section of the README treating this issue.

I'm closing this issue as the fix should be easy (update your gcc and recompile maskrcnn-benchmark, marking sure to have deleted the `build` folder before). Let me know if you still face issues

**Comment by markaustinbrophy** [comment]
I was having the same issue and deleting the `build` folder was the key. Thanks @fmassa!
