### ISSUE TITLE
AttributeError: KEYPOINT_ON

### ISSUE THREAD

**Issue by Idolized22** [facebookresearch/maskrcnn-benchmark#500]
## ❓ Questions and Help

I have  trained the network with the model : e2e_mask_rcnn_X_101_32x8d_FPN_1x  
on a self  created data- set with the following script  I wrote: [coco like dataset] 

for instance segmentation task and after the train has saved the last model the following error has occurred : 

> 2019-02-27 02:52:46,742 maskrcnn_benchmark.utils.checkpoint INFO: Saving checkpoint to ./model_0180000.pth
2019-02-27 02:52:47,327 maskrcnn_benchmark.utils.checkpoint INFO: Saving checkpoint to ./model_final.pth
2019-02-27 02:52:47,806 maskrcnn_benchmark.trainer INFO: Total training time: 1 day, 1:54:59.497522 (0.5183 s / it)
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 170, in main
    run_test(cfg, model, args.distributed)
  File "tools/train_net.py", line 86, in run_test
    if cfg.MODEL.KEYPOINT_ON:
  File "/home/portablelinux/anaconda3/envs/maskrcnn25feb19/lib/python3.7/site-packages/yacs/config.py", line 118, in __getattr__
    raise AttributeError(name)
AttributeError: KEYPOINT_ON

how can I test the model ? 

thank for the help in advance.

**Comment by fmassa** [comment]
Hi,

I think that there might have been a conflict with your code.

Here is my hypothesis: maybe you have updated the repo while the model was training?
Then, the `cfg` would have already been created, but when you updated the code, it got reloaded in the evaluation part, and then it was expecting the `KEYPOINT_ON` flag to be present in the `cfg`, which wasn't because it was from the old codebase.

Here is my solution to solve this problem: just re-run the evaluation code by pointing to the serialized model, and it should be work fine now.

Let me know if it doesn't solve the problem.

**Comment by Idolized22** [comment]
Thank you very much for your help. 

thought as  I am not very experienced , I  didn't understood the following :  

@fmassa 
`Here is my hypothesis: maybe you have updated the repo while the model was training?`

what does updated the repo  means , I might have done it by a mistake because i don't know how to do it, 
and I have done some try and error. 

@fmassa 
> Here is my solution to solve this problem: just re-run the evaluation code by pointing to the serialized model, and it should be work fine now

what is the serialized model ? 
how do I rerun the evaluation code and how do I point to the serialized model?

**Comment by Idolized22** [comment]
Thank you very much for your help. 

thought as  I am not very experienced , I  didn't understood the following :  

@fmassa 
`Here is my hypothesis: maybe you have updated the repo while the model was training?`

what does updated the repo  means , I might have done it by a mistake because i don't know how to do it, 
and I have done some try and error. 

@fmassa 
> Here is my solution to solve this problem: just re-run the evaluation code by pointing to the serialized model, and it should be work fine now

what is the serialized model ? 
how do I rerun the evaluation code and how do I point to the serialized model?

**Comment by fmassa** [comment]
@Idolized22 I think you might have done
```
git pull
```
in the `maskrcnn-benchmark` repo, after you had already started training. This changed the source code of the library, but the code that was training had already loaded most of the code, except the inference code.

**Comment by Idolized22** [comment]
> @Idolized22 I think you might have done
> 
> ```
> git pull
> ```
> 
> in the `maskrcnn-benchmark` repo, after you had already started training. This changed the source code of the library, but the code that was training had already loaded most of the code, except the inference code.

@fmassa  , it is vert possible that I have done  that. 
But I don't understand  How to do what you proposed in order to solve that. 
I am very new to the field  so I need a little more detailed explanation  please. 

thank you very very much for helping!

**Comment by fmassa** [comment]
@Idolized22 just update the code to the latest version and run the testing again. It should work I believe
