### ISSUE TITLE
targets when SIZE_DIVISIBILITY > 1

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/maskrcnn-benchmark#501]
## ❓ Questions and Help
When SIZE_DIVISIBILITY is set larger than 1 some padding is applied to the input image. Shouldn't `targets` be shifted as well to match the padding?

**Comment by fmassa** [comment]
Hi,

Great question!

Note that the images are padded on the right / bottom. Given that the bounding boxes are referenced starting from the top/right corner, padding the images do not change the coordinates of the boxes.

Let me know if you have further questions.

**Comment by IssamLaradji** [comment]
Thanks! :)
