### ISSUE TITLE
is there a pretrained-model on keypoints using coco_2017 dataset?

### ISSUE THREAD

**Issue by MichaelTanger** [facebookresearch/maskrcnn-benchmark#505]

**Comment by fmassa** [comment]
I haven't uploaded the models I've trained, but you can use the pre-trained models from Caffe2, which are compatible and gives the same results.
This config contains the pre-trained model https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/caffe2/e2e_keypoint_rcnn_R_50_FPN_1x_caffe2.yaml
