### ISSUE TITLE
segmentation fault after updating GCC

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#514]
## ❓ Questions and Help
Hi at first my GCC is 4.8.5 and I got a segmentation fault in `boxlist_nmsI` in rpn/inference.py .
now I have already updated the GCC version, and there is no warning when I run `python setup.py build develop`, but the error still exists. What can I do?

**Comment by JoyHuYY1412** [comment]
Actually it is still GCC error after I delete build filefolder and rebuild. 
It says `gcc_compile/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/cc1plus: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory`
but I can do nothing.....

**Comment by spytensor** [comment]
gcc >= 4.9 may help you

**Comment by fmassa** [comment]
Yes, you need to use GCC >= 4.9.
Also, once you update GCC, don't forget to delete the `build` folder and try again.

Also, it might look like your GCC installation might be problematic.
