### ISSUE TITLE
How do trained models are loaded for inference?

### ISSUE THREAD

**Issue by maxsenh** [facebookresearch/maskrcnn-benchmark#518]
## ❓ Questions and Help
Hi

I trained my own model while using the pre-trained Imagenet model. Now, I have trouble understanding how my model is loaded for inference? Is first the model found in OUTPUT_DIR loaded and then the one from MODEL.WEIGHT ?
```
        save_dir = cfg.OUTPUT_DIR
        checkpointer = DetectronCheckpointer(cfg, self.model, save_dir=save_dir)        
        _ = checkpointer.load(cfg.MODEL.WEIGHT)

```
Thanks in advance

**Comment by fmassa** [comment]
If there is a `last_checkpoint` file in `OUTPUT_DIR`, it will take the file present there.
If there isn't any file named `last_checkpoint` in `OUTPUT_DIR`, it will load the weights from `MODEL.WEIGHT`.

**Comment by JoyHuYY1412** [comment]
> If there is a `last_checkpoint` file in `OUTPUT_DIR`, it will take the file present there.
> If there isn't any file named `last_checkpoint` in `OUTPUT_DIR`, it will load the weights from `MODEL.WEIGHT`.

if I just write,
`save_dir = cfg.OUTPUT_DIR
 checkpointer = DetectronCheckpointer(cfg, self.model, save_dir=save_dir)  `
If there isn't any file named last_checkpoint in OUTPUT_DIR, it will start from the scratch, right?
