### ISSUE TITLE
how can I get a quick training and testing demo

### ISSUE THREAD

**Issue by scut-salmon** [facebookresearch/maskrcnn-benchmark#520]
Hi, I was new to this project, 

I wonder would it be possible to train this model on a small dataset, 
so that I could get the training result and testing quickly, 
since that the coco dataset is too large (I only have 1 GPU, training is slow) and the json file is also too 
large to look up.

Thanks.

**Comment by fmassa** [comment]
If you just want to run quick training schedules for debugging purposes, check the configs in `quick_schedules`.

If you want to train on small datasets and obtain good performance, you probably want to start from a pre-trained detection model and then finetune it for your small dataset.
There are a number of open issues about this topic already, see https://github.com/facebookresearch/maskrcnn-benchmark#finetuning-from-detectron-weights-on-custom-datasets for some reference.
