### ISSUE TITLE
inference pth results and prediction pth files 

### ISSUE THREAD

**Issue by Idolized22** [facebookresearch/maskrcnn-benchmark#526]
## ❓ Questions and Help

Hello, 
I have few question about  testing self created dataset, 
 I have used the e2e_faster_rcnn_X_101_32x8d_FPN_1x.ymal model . 
1. what and how  does the results.pth and prediction.pth  used for ? 
2. does one of them holds the mask predictions ? 
3.is there a way to get a  json polygons prediction  file for the test set ?  
4. in order to visualize the results do I need to modify the [predictor.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py) categories ?  
    does  some more modifications are required ? 

Thanks for your help in advance !

**Comment by fmassa** [comment]
Hi,

Here is a thread that is related to your questions (specifically point 3) https://github.com/facebookresearch/maskrcnn-benchmark/issues/327

About the other points:
1 - Those files are intermediate results of the inference, and they contain different information. `coco_results.pth` is just a struct containing the mIoU, while `prediction.pth` holds the outputs of the model for every image in the dataset
2 - yes, the masks are stored in `prediction.pth`, but before being pasted in the image (so you need to use the `Masker` to paste the masks into the image space, see https://github.com/facebookresearch/maskrcnn-benchmark/blob/de42d895ad7c2cee72259207fa9f2a7580c72cd0/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py#L108 and https://github.com/facebookresearch/maskrcnn-benchmark/blob/de42d895ad7c2cee72259207fa9f2a7580c72cd0/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py#L122-L125
3 - the rle encodings are available in the `segm.json` file, you could try seeing if you can get the polygons out of it

I'm closing the issue, but let me know if you have further questions
