### ISSUE TITLE
bounding_box.py error

### ISSUE THREAD

**Issue by CF2220160244** [facebookresearch/maskrcnn-benchmark#532]
when my input image data contain  no labels，the following problems occurred ：
 

  File "bounding_box.py", line 260, in <module>
    bbox = BoxList([[]], (2, 2))
  File "bounding_box.py", line 32, in __init__
    "size of 4, got {}".format(bbox.size(-1))
ValueError: last dimenion of bbox should have a size of 4, got 0

and in bounding_box.py，when i run with the following input  can have the same error：

if __name__ == "__main__":
    # bbox = BoxList([[0, 0, 10, 10], [0, 0, 5, 5]], (10, 10))
    bbox = BoxList([[]], (2, 2))
    s_bbox = bbox.resize((5, 5))

i need train image with no labels，can you help me?

**Comment by fmassa** [comment]
Hi,

This is currently not supported in the codebase, but check #169 for a way of addressing it.
