### ISSUE TITLE
update pytorch cause crush in jupyter notebook

### ISSUE THREAD

**Issue by feihuidiqiu** [facebookresearch/maskrcnn-benchmark#533]
## To Reproduce

After update the pytorch to 1.0.1.post2 version, the inference of faster rcnn and retinanet (I just test that) will crush the jupyter notebook, rollback to 1.0.0 version and everythin is ok. 

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.0.1.post2
 - OS (e.g., Linux):Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:cuda 9,2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by fmassa** [comment]
Hi,

You need to re-compile `maskrcnn-benchmark` after updating PyTorch.
Don't forget to remove the `build` folder before compilation

**Comment by feihuidiqiu** [comment]
thank you for your solution ~
