### ISSUE TITLE
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2

### ISSUE THREAD

**Issue by gongzaizhou** [facebookresearch/maskrcnn-benchmark#534]
## ❓ Questions and Help
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
I try   python setup.py build develop

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/gongzaizhou/code/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/home/gongzaizhou/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/include -I/home/gongzaizhou/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/gongzaizhou/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/include/TH -I/home/gongzaizhou/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/gongzaizhou/anaconda2/envs/maskrcnn_benchmark/include/python3.7m -c /home/gongzaizhou/code/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu -o build/temp.linux-x86_64-3.7/home/gongzaizhou/code/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/home/gongzaizhou/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/include/c10/Half-inl.h(21): error: identifier "__half_as_short" is undefined

1 error detected in the compilation of "/tmp/tmpxft_000263c8_00000000-7_ROIAlign_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2

so, how I solve it?  please help me ,thanks!

**Comment by fmassa** [comment]
Which version of nvcc and cuda do you have? Also, what's your gcc version? There might be some incompatibilities there.

**Comment by gongzaizhou** [comment]
> Which version of nvcc and cuda do you have? Also, what's your gcc version? There might be some incompatibilities there.

$ cat /usr/local/cuda-8.0/version.txt
    CUDA Version 8.0.27
    CUDA Patch Version 8.0.27.1

$ gcc --version
    gcc (Debian 4.9.2-10) 4.9.2

$ nvcc -V
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2016 NVIDIA Corporation
  Built on Wed_May__4_21:01:56_CDT_2016

 $ echo $PATH
 /home/gongzaizhou/anaconda2/envs/maskrcn/bin:/home/gongzaizhou/anaconda2/condabin:/usr/local/cuda-8.0/bin:/home/gongzaizhou/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/tiger/ss_bin:/usr/local/jdk/bin:/usr/sbin/:/opt/tiger/ss_lib/bin:/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/django/bin:/opt/tiger/yarn_deploy/hadoop/bin/:/opt/tiger/yarn_deploy/hive/bin/:/opt/tiger/yarn_deploy/jdk/bin/:/opt/tiger/hadoop_deploy/jython-2.5.2/bin


cuda8.0 dose not support gcc4.9.2?

**Comment by suica** [comment]
Use gcc 5.x may be a solution.

**Comment by gongzaizhou** [comment]
> Which version of nvcc and cuda do you have? Also, what's your gcc version? There might be some incompatibilities there.

I solved it, cuda9.0 can be compiled through 

my env:
cuda9.0     gcc 4.9.2       python3.6.8

**Comment by gongzaizhou** [comment]
> Use gcc 5.x may be a solution.

I solved it, through cuda9.0.

**Comment by Markovcom** [comment]
@gongzaizhou hello,i solve it with ubuntu16.04, cuda8, gcc5.4

**Comment by LeviViana** [comment]
Closing, since a solution has been found.

**Comment by wangjunfeng90214** [comment]
The error is that the cuda 8.0.27 is too old, the "__half_as_short" is undefined in the /usr/local/cuda-8.0/include/cuda_fp16.h, you shold update your cuda to the version 8.0.61

**Comment by xiaozhuka** [comment]
I met this problem: csrc/type_shim.h(118): error: identifier "__shfl_down_sync" is undefined
gcc5.4, cuda8, cudnn6
does any one know how to solve it?

**Comment by weweus** [comment]
when i try "python setup.py install --cuda_ext --cpp_ext", there is the error "command '/usr/local/cuda/bin/nvcc' failed with exit status 2". 
What shall i do to solve the problem? Please help me, thx!

CUDA Version 9.2.148
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
python 3.6.8
pytorch 1.0.1

**Comment by Dongz666** [comment]
> @gongzaizhou hello,i solve it with ubuntu16.04, cuda8, gcc5.4
 cuda 8.0.61 gcc 5.4.0, I can't solve this error.

**Comment by Qian-nian** [comment]
> > @gongzaizhou hello,i solve it with ubuntu16.04, cuda8, gcc5.4
> > cuda 8.0.61 gcc 5.4.0, I can't solve this error.

I have the same problem,cuda8.0,gcc5.4,could you please give me some advice?

**Comment by huangteng1220** [comment]
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda
# Modify the above statement to:
export CUDA_HOME=/usr/local/cuda

http://www.programmersought.com/article/8191430209/

**Comment by JoyHuYY1412** [comment]
> > @gongzaizhou hello,i solve it with ubuntu16.04, cuda8, gcc5.4
> > cuda 8.0.61 gcc 5.4.0, I can't solve this error.

me too. cuda 8.0.61 gcc 5.4.0. Cannot solve.

**Comment by Jnyle** [comment]
> @gongzaizhou hello,i solve it with ubuntu16.04, cuda8, gcc5.4
@Markovcom how did you fix the error with cuda8 and gcc5.4 ?

**Comment by Jnyle** [comment]
> I met this problem: csrc/type_shim.h(118): error: identifier "__shfl_down_sync" is undefined
> gcc5.4, cuda8, cudnn6
> does any one know how to solve it?

did you solve the problem without upgrade the cuda version ?

**Comment by rishabhjoshi** [comment]
Updating cuda to 10.0 and pytorch to 1.4 solved it for me.
