### ISSUE TITLE
demo/Mask_R-CNN_demo.ipynb bug

### ISSUE THREAD

**Issue by LU4E** [facebookresearch/maskrcnn-benchmark#54]
## ❓ Questions and Help
ubuntu 18.04
cuda 9.0
cudnn 7.1.3

I test the demo/Mask_R-CNN_demo.ipynb on the ubuntu. Every time the code come to the last block:
predictions = coco_demo.run_on_opencv_image(image), the kernel will reboot without any erro infomation. I check the code step by step, and find out the No.200 : predictions = self.model(image_list) in the predictor.py is the source of the problem. 
I can't solve it by myself, anyone could give me some suggestion.
Thanks.

![default](https://user-images.githubusercontent.com/12681953/47641282-a5571c80-dba0-11e8-9c9d-4c16146aa5b9.PNG)

**Comment by fmassa** [comment]
Hi,

Can you try the webcam demo? It should fail as well, but with a more meaningful error message.

Also, what is your gcc version?
You need to have at least gcc version 4.9. Check the TROUBLESHOOTING section of the README for more details

**Comment by LU4E** [comment]
thanks for your reply.
gcc 4.8, I downgrade to 4.8 for installing the cuda9. 
I will check again with the gcc 4.9
thanks again.

**Comment by fmassa** [comment]
Cool!

So, as this seems to be the same error as the one explained in https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/TROUBLESHOOTING.md#segmentation-fault-core-dumped-when-running-the-library, I'll close this issue.

Please let me know if you still have issues.

**Comment by LU4E** [comment]
You have catch the key to the problem.
gcc 5.5 is ok. Both of gcc4.8 and gcc7 don't work well.
thanks a lot.
