### ISSUE TITLE
How to visualize mask in old fashion?

### ISSUE THREAD

**Issue by Fangyh09** [facebookresearch/maskrcnn-benchmark#546]
## ❓ Questions and Help
How to visualize mask in old fashion? That is, different object has its own mask with different color.

**Comment by fmassa** [comment]
Check https://github.com/facebookresearch/maskrcnn-benchmark/blob/558d7afad13db40bf7062f9c9b09bb7acf755a82/demo/predictor.py#L276-L300

If you want a different visualization scheme, you can use the one from Detectron, or use randomly generated colors for each instance

**Comment by M-Alami** [comment]
If someone needs it, you can use this function:
`def overlay_mask(self, image, predictions):
        masks = predictions.get_field("mask").numpy()
        labels = predictions.get_field("labels")

        colors = self.compute_colors_for_labels(labels).tolist()
        masked_image=image.astype(np.uint32).copy()
        for mask, color in zip(masks, colors):
            for c in range(3):
                image[:, :, c] = np.where(mask == 1, image[:, :, c] * (1 - 0.5) + 0.5 * color[c] * 255,image[:, :, c])
           composite = image

        return composite`

**Comment by TZebin** [comment]
Hi can we change the bounding box and contour colour according to the label?
