### ISSUE TITLE
Training from images without annotations

### ISSUE THREAD

**Issue by shimen** [facebookresearch/maskrcnn-benchmark#549]
## ❓ Questions and Help
Hello!
I'm training a model on my own data. The detection is ok, but I get to many false alarms.
I have much more data that I can use but the object that I'm training my model to detect is missing from these images but the background is the same. I would like to know is it possible to include this data too to train better the background class and to decrease the far?

Ilya

**Comment by fmassa** [comment]
Check #169 , it contains a lot of information to your question.

**Comment by maedmaex** [comment]
@shimen this issue [#169](https://github.com/facebookresearch/maskrcnn-benchmark/issues/169) might help you
