### ISSUE TITLE
DockerFile with nccl

### ISSUE THREAD

**Issue by mingruimingrui** [facebookresearch/maskrcnn-benchmark#56]
Hi all, I was wondering if you guys have a sample DockerFile with CUDA, CUDNN and NCCL?
Would be really helpful for pushing things to production! Thanks!

**Comment by fmassa** [comment]
We don't have a docker image, but maybe you could take the official PyTorch docker image from https://github.com/pytorch/pytorch#docker-image and adapt it to install `maskrcnn-benchmark`?

**Comment by mingruimingrui** [comment]
@fmassa Thanks! I actually found what I was looking for. Apparently nccl and even cudnn can be installed using apt get! https://github.com/uber/horovod/blob/master/Dockerfile

**Comment by mingruimingrui** [comment]
I'll be closing this issue now.

**Comment by fmassa** [comment]
Also note that there is a open PR which adds a Dockerfile for mask RCNN benchmark, see https://github.com/facebookresearch/maskrcnn-benchmark/pull/78
