### ISSUE TITLE
top_k function error

### ISSUE THREAD

**Issue by weiyaowu666** [facebookresearch/maskrcnn-benchmark#560]
## ❓ Questions and Help
When I testing my checkpoint, I encounter some errors like follow:
`objectness, topk_idx = objectness.topk(pre_nms_top_n, dim=1, sorted=True)`
this code is in rpn/inference.py
error like this : `/rpn/inference.py", line 101, in forward_for_single_feature_map
    box_regression = box_regression[batch_idx, topk_idx]
RuntimeError: CUDA error: device-side assert triggered`

and I find my topk_idx is out of index, as follow
`batch_dix: tensor([[0],
        [1],
        [2],
        [3]], device='cuda:0'), topk_idx: tensor([[9223372034707292159,                   0, 9223372032559808512,
          ...,          2147483647,                   0,
         9223372034707292159],
        [         2147483647, 9223372034707292159,                   0,
          ...,                   0, 9223372034707292159,
         9223372034707292159],
        [9223372032559808512, 9223372034707292159,          2147483647,
          ..., 9223372032559808512, 9223372034707292159,
                           0],
        [9223372032559808512,          2147483647,                   0,
          ..., 9223372034707292159,          2147483647,
         9223372034707292159]], device='cuda:0')`

**Comment by weiyaowu666** [comment]
I have checked other issus about classes not matched,  and not found errors about my labels.  because I have only one class of 'text', its class_id is 1, no zero(zero is background).  and my ROI_BOX_HEAD.NUM_CLASSES is 2, its also no problem.
Cloud someone tell me why?Thanks os much.
I use the model  maskrcnn_resnet50, is it not convergen?

**Comment by LIszu** [comment]
@weiyaowu666 I have the same problem. Did you solve it? Thanks!

**Comment by weiyaowu666** [comment]
> @weiyaowu666 I have the same problem:topk_idx is out of index. Did you solve it? Thanks!
Due to the model has  diverged, so you need to check your datasets and network config(such as lr, architecture, etc.) to ensure any steps are right.

**Comment by WeihongM** [comment]
@weiyaowu-md  @LIszu   How you solved the problem?  I also met the same question

**Comment by weiyaowu-md** [comment]
@WeihongM 


> @weiyaowu-md @LIszu How you solved the problem? I also met the same question

Yes，the problem comes from the model is divergency. Try to decrease the learning rate and check out the dataset is well processed.

**Comment by WeihongM** [comment]
I have checked the dataset, it seems no problem.  @weiyaowu-md  It is confusing why I can't train the model now, whose training process is normal earlier...  Can you give me some suggestions?

**Comment by weiyaowu-md** [comment]
> I have checked the dataset, it seems no problem. @weiyaowu-md It is confusing why I can't train the model now, whose training process is normal earlier... Can you give me some suggestions?

@WeihongM Maybe the environment is damaged, you can reinstall it and try it again. Clone a new coderepo and install it maybe better.
