### ISSUE TITLE
build error benchmark

### ISSUE THREAD

**Issue by petrick23** [facebookresearch/maskrcnn-benchmark#575]
## ❓ Questions and Help
/home/lk/lk/addtion/maskrcnn-benchmark-master/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp:71:46: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
   AT_DISPATCH_FLOATING_TYPES(dets.scalar_type(), "nms", [&] {
                                              ^
/home/lk/.local/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
     const at::Type& the_type = TYPE;                                         \
                                ^
error: command 'gcc' failed with exit status 1
i don't know how to fix that, please help me
thanks!

**Comment by xuzheyuan624** [comment]
I also have this problem. Have u solved it?

**Comment by xuzheyuan624** [comment]
May be your gcc version is too high for CUDA9.0.Try to install gcc-4.9 and g++-4.9 to solve this problem, which  works to me

**Comment by LeviViana** [comment]
It seems to me it is related to pytorch's version.

**Comment by LeviViana** [comment]
#25

**Comment by petrick23** [comment]
i don't know the reason, but i build it with cuda10.0. gcc-5.4 as ubuntu16.04 , so what can i do ?@xuzheyuan624

**Comment by petrick23** [comment]
(pytorch) lk@lk-pc:~/lk/addtion/maskrcnn-benchmark-master$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import maskrcnn_benchmark
i did this from terminal. it is right. But, when i run webdemo.py after i cd demo ,it will be "no such module"
can you figure it out?

**Comment by kyamagu** [comment]
Workaround: https://github.com/facebookresearch/maskrcnn-benchmark/pull/555#commitcomment-32760236

**Comment by LeviViana** [comment]
Following the [installation steps](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md) will do the job. This is break is due to #557.
