### ISSUE TITLE
Question about the parser

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#578]
## ❓ Questions and Help
In your code `train_net.py`, there are some lines https://github.com/facebookresearch/maskrcnn-benchmark/blob/b3d1de0088ad84b7a1cdee62c08418c7b9095acc/tools/train_net.py#L113-L119

but when you use it, the name is `config_file`, the'-' turns to '_'
https://github.com/facebookresearch/maskrcnn-benchmark/blob/b3d1de0088ad84b7a1cdee62c08418c7b9095acc/tools/train_net.py#L146

Do this make no difference?

**Comment by LeviViana** [comment]
This relates to the `argparse` library. You might find the answers to your questions [here](https://stackoverflow.com/questions/12834785/having-options-in-argparse-with-a-dash).

**Comment by fmassa** [comment]
Closing following @LeviViana comment. Thanks Levi!
