### ISSUE TITLE
how to transfer the mask-rcnn  model to c++ pytorch?

### ISSUE THREAD

**Issue by 95xueqian** [facebookresearch/maskrcnn-benchmark#579]
## ❓ Questions and Help
i have trained the mask-rcnn model on pytorch python, and saved the model and weights, now i want to use the model on pytorch c++, please tell me how could i do ?  thanks!

**Comment by mitsuix** [comment]
#138 
I followed this.
But I met some problems.
Any other suggestions?

**Comment by fmassa** [comment]
Try using #138 , that's the way to go. I have no better solutions than that for now
