### ISSUE TITLE
how to use this model only in objection detection

### ISSUE THREAD

**Issue by HuangQinJian** [facebookresearch/maskrcnn-benchmark#580]
## ❓ Questions and Help
how to use this model only in objection detection

**Comment by TyroneLi** [comment]
I want to know this question too.And how can I use this model to train my own dataset which is made like pascal voc format.If your know the answer, please tell me.thx

**Comment by fmassa** [comment]
For the first question, just use a config file for detection-only, like https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/e2e_faster_rcnn_R_50_FPN_1x.yaml
In those cases, `MASK_ON` is false.

For the second question, check https://github.com/facebookresearch/maskrcnn-benchmark/issues/77
