### ISSUE TITLE
Re-training possible?

### ISSUE THREAD

**Issue by maxsenh** [facebookresearch/maskrcnn-benchmark#581]
## ❓ Questions and Help

Hi! 
My question is whether retraining on new data is possible? Lets assume that I trained a model with satisfying accuracies but I want to further improve it by adding new data containing the features I want to add. Do I simply set the old model as pre-trained model (MODEL.WEIGHT) and train only on those new data?

Thank you in advance!

**Comment by chengyangfu** [comment]
Hi, 
    That's one of the solutions. The potential problem is your model may forget what it learns in the previous dataset. Another straightforward method is to concatenate these two data sets and re-train on it.  You can do it by modifying `DATASETS.TRAIN`. This could make sure your modal does well on both datasets but it may take longer training time. 


    This is also an open research problem, you can also check the following research paper for a better solution. 
    
You can also check the following research paper.  
- Piggyback: Adapting a Single Network to Multiple Tasks by Learning to Mask Weights, ECCV 2018
- Learning Without Forgetting, ECCV 2016

**Comment by fmassa** [comment]
Closing following @chengyangfu comments. Thanks Cheng-Yang!
