### ISSUE TITLE
Broken links when downloading the mdoels?

### ISSUE THREAD

**Issue by YuhangMing** [facebookresearch/maskrcnn-benchmark#582]
## ❓ Questions and Help
Thanks for the amazing works, but I have encountered problems when trying to download the models using "e2e_mask_rcnn_R_101_FPN_1x_caffe2.yaml". 
The error is:     urllib.error.HTTPError: HTTP Error 404: Not Found
This is weird as I didn't have this problem before. Have anyone met the same problem?

**Comment by fmassa** [comment]
You need to update your version of `maskrcnn-benchmark`.
The links have changed and have been updated in https://github.com/facebookresearch/maskrcnn-benchmark/pull/301
