### ISSUE TITLE
"local_rank" parameter does not work

### ISSUE THREAD

**Issue by shsjxzh** [facebookresearch/maskrcnn-benchmark#585]
## ❓ Questions and Help
Hi, I want to run the code on gpu 1, which is on my lab's gpu server. However, when I change the local rank with following code:

    python tools/train_net.py --config-file "configs/my_e2e_mask_rcnn_R_50_C4_1x.yaml" --local_rank 1

I find that it still runs on gpu 0 (which is the default setting), and wonder why?
（By the way, my_e2e_mask_rcnn_R_50_C4_1x.yaml only changes the dataset. )

I also try to change the default device to "cuda:1", while another error occurs:

    RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /home/xuzihao/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.cu:103

And I don't know how to train on a gpu other than gpu 0.

**Comment by fmassa** [comment]
You should use `CUDA_VISIBLE_DEVICE=1 python tools/train_net.py ...`.
`local_rank` is used by `torch.distributed.launch` to leverage multiple GPUs.
