### ISSUE TITLE
What is the image size backbone convolution stage expects?

### ISSUE THREAD

**Issue by muzammil360** [facebookresearch/maskrcnn-benchmark#586]
## ❓ Questions and Help
Reading the `Resize` code [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/transforms/transforms.py), it seems that smaller dimension is resized to 800 as long as longer side doesn't go beyond 1333 (in that case shorter side is rescaled accordingly). 

I think this can lead to images of different sizes. It is my understanding that conv net expects a particular `n x m x c` tensor (otherwise featuremap sizes won't match up at the end for classifiers). 

Can someone explain what's going on here!

**Comment by fmassa** [comment]
The implementation in here does not require the images to have the same size - they can have arbitrary sizes, as long as the minimum dimension is large enough for the backbone to go through -- generally 224 pixels.

The ROI layer will always rescale the bounding boxes to have the same dimension, so the classifiers are not affected.
