### ISSUE TITLE
    from maskrcnn_benchmark.config import cfg ModuleNotFoundError: No module named 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by sheep1234567** [facebookresearch/maskrcnn-benchmark#588]
## ❓ Questions and Help

<img width="674" alt="image" src="https://user-images.githubusercontent.com/48812213/54792535-bd851200-4bfb-11e9-9d92-9cfcdd243ce9.png">

**Comment by sheep1234567** [comment]
I follow the Install.md but without doing the last step : 
python setup.py build develop

Is it the reason?

**Comment by sheep1234567** [comment]
or to say he last step was failed due to :
<img width="384" alt="image" src="https://user-images.githubusercontent.com/48812213/54792690-5c117300-4bfc-11e9-9c43-d69a2c8d9173.png">

**Comment by LeviViana** [comment]
You must follow all the steps of the installation guide. It seems that you don't have a pytorch nightly version installed. Please refer to #557. You are getting the same error as #567.

**Comment by sheep1234567** [comment]
@LeviViana  Thanks!
And now the build process succeed, but it says the Nvidia Driver is old.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/48812213/54857981-7ceecc80-4cbf-11e9-9118-c8ec6f1c3850.png">

<img width="493" alt="image" src="https://user-images.githubusercontent.com/48812213/54857986-82e4ad80-4cbf-11e9-83c5-171d4bfffa45.png">

May I ask which one is old? Cuda version or Nvidia Driver version? Thanks!

**Comment by fmassa** [comment]
You are using the wrong PyTorch version, as pointed out by @LeviViana .

Uninstall PyTorch and install the nightly version.

**Comment by sheep1234567** [comment]
I installed the Pytorch-nightly version, 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/48812213/54942029-76449d00-4eeb-11e9-9f19-d70ebc7965e0.png">

but when I uninstalled Pytorch, the torchvision is also got uninstalled, which brings
<img width="680" alt="image" src="https://user-images.githubusercontent.com/48812213/54941989-67f68100-4eeb-11e9-8a1c-a0a7ca88813d.png">

and when I use 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/48812213/54942097-9bd1a680-4eeb-11e9-9396-d23e8c3c529f.png">
to install torchvision, Pytorch also requires to be installed which I think it should not be installed?

<img width="454" alt="image" src="https://user-images.githubusercontent.com/48812213/54942073-91171180-4eeb-11e9-9dfc-c349de9b27d7.png">

**Comment by sheep1234567** [comment]
@LeviViana @fmassa 
Thanks a lot!

**Comment by fmassa** [comment]
You can try installing torchvision from github
clone the torchvision repo and do
```
python setup.py install
```

**Comment by satyamr1** [comment]
I'm having required version of pytorch-nightly (1.2.0.dev20190704). Also, I'm using python3.6.8 but I'm getting the same error. Can you please help me out to fix it! @fmassa
