### ISSUE TITLE
Small mistake in box predictor weight initalization

### ISSUE THREAD

**Issue by godimarcovr** [facebookresearch/maskrcnn-benchmark#59]
## 🐛 Bug

It's probably just a nitpick since it works well enough as it is, but in the roy_box_predictors weight initalization there is a mistake probably caused by some copy-pasting https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py#L19-L23 .
As you can see, self.cls_score.weight and self.bbox_pred.weight get initialized twice, which makes no sense.
It should be something like this unofficial implementation of Detectron https://github.com/roytseng-tw/Detectron.pytorch/blob/master/lib/modeling/fast_rcnn_heads.py#L24-L27 in which the bias is the one initialized to 0 (as per the paper).

**Comment by fmassa** [comment]
Oh, right, that's definitely a bug!
Can you send a PR fixing this?

Thanks!

**Comment by fmassa** [comment]
I'm actually sending a PR to fix this, don't worry.
