### ISSUE TITLE
D:\\VS2015\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

### ISSUE THREAD

**Issue by lvpinrui** [facebookresearch/maskrcnn-benchmark#593]
## ❓ Questions and Help
C:/Anaconda3/envs/test/lib/site-packages/torch/include\THC/generic/THCTensorMathReduce.h(33): warning C4190: “THCudaHalfTensor_maxall”有指定的 C 链接，但返回 了与 C 不兼容的 UDT“c10::Half”
C:/Anaconda3/envs/test/lib/site-packages/torch/include\c10/util/Half.h(324): note: 参见“c10::Half”的声明
C:/Anaconda3/envs/test/lib/site-packages/torch/include\THC/generic/THCTensorMathReduce.h(34): warning C4190: “THCudaHalfTensor_medianall”有指定的 C 链接，但返回了与 C 不兼容的 UDT“c10::Half”
C:/Anaconda3/envs/test/lib/site-packages/torch/include\c10/util/Half.h(324): note: 参见“c10::Half”的声明
D:\VS2015\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Anaconda3\envs\test\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib/x64" /LIBPATH:C:\Anaconda3\envs\test\libs /LIBPATH:C:\Anaconda3\envs\test\PCbuild\amd64 /LIBPATH:D:\VS2015\VC\LIB\amd64 /LIBPATH:D:\VS2015\VC\ATLMFC\LIB\amd64 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" cudart.lib c10.lib caffe2.lib torch.lib torch_python.lib caffe2_gpu.lib _C.lib /EXPORT:PyInit__C build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\vision.obj build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\nms_cpu.obj build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\ROIAlign_cpu.obj build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cuda\nms.obj build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cuda\ROIAlign_cuda.obj build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cuda\ROIPool_cuda.obj build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cuda\SigmoidFocalLoss_cuda.obj /OUT:build\lib.win-amd64-3.7\maskrcnn_benchmark\_C.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\_C.cp37-win_amd64.lib
vision.obj : warning LNK4197: 多次指定导出“PyInit__C”；使用第一个规范
  正在创建库 build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\_C.cp37-win_amd64.lib 和对象 build\temp.win-amd64-3.7\Release\Anaconda3\envs\test\Lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\csrc\_C.cp37-win_amd64.exp
ROIAlign_cuda.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl c10::cuda::CUDAStream::operator struct CUstream_st *(void)const " (__imp_??BCUDAStream@cuda@c10@@QEBAPEAUCUstream_st@@XZ)
ROIPool_cuda.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl c10::cuda::CUDAStream::operator struct CUstream_st *(void)const " (__imp_??BCUDAStream@cuda@c10@@QEBAPEAUCUstream_st@@XZ)
SigmoidFocalLoss_cuda.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl c10::cuda::CUDAStream::operator struct CUstream_st *(void)const " (__imp_??BCUDAStream@cuda@c10@@QEBAPEAUCUstream_st@@XZ)
ROIAlign_cuda.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) class c10::cuda::CUDAStream __cdecl c10::cuda::getCurrentCUDAStream(short)" (__imp_?getCurrentCUDAStream@cuda@c10@@YA?AVCUDAStream@12@F@Z)
ROIPool_cuda.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) class c10::cuda::CUDAStream __cdecl c10::cuda::getCurrentCUDAStream(short)" (__imp_?getCurrentCUDAStream@cuda@c10@@YA?AVCUDAStream@12@F@Z)
SigmoidFocalLoss_cuda.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) class c10::cuda::CUDAStream __cdecl c10::cuda::getCurrentCUDAStream(short)" (__imp_?getCurrentCUDAStream@cuda@c10@@YA?AVCUDAStream@12@F@Z)
build\lib.win-amd64-3.7\maskrcnn_benchmark\_C.cp37-win_amd64.pyd : fatal error LNK1120: 2 个无法解析的外部命令
error: command 'D:\\VS2015\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

**Comment by bpfliegel** [comment]
Duplicate, please refer to https://github.com/facebookresearch/maskrcnn-benchmark/issues/547.
It can be closed.

**Comment by fmassa** [comment]
Closing following @bpfliegel comment. Thanks @bpfliegel !
