### ISSUE TITLE
confidence thresh? 

### ISSUE THREAD

**Issue by WeihongM** [facebookresearch/maskrcnn-benchmark#594]
## ❓ Questions and Help
In the code train_net.py, after the model trained, the code run into the inference part.
However, in the code inference.py, I couldnot find the object confidence thresh setting.
I am confused the model output based on which value of object confidence?
where can we use object confidence thresh as a parameter and pass into the model prediction function.

```
    logger.info("Start evaluation on {} dataset({} images).".format(dataset_name, len(dataset)))
    start_time = time.time()
    predictions = compute_on_dataset(model, data_loader, device)
    # wait for all processes to complete before measuring the time
    synchronize()
    total_time = time.time() - start_time
```

**Comment by WeihongM** [comment]
@pietern @sotte @Celebio @martinruenz  Need for help, thanks!

**Comment by WeihongM** [comment]
I found the function in demo/predictor.py can solve the problem.  Thanks for the great work!
```
select_top_predictions()
```

**Comment by chengyangfu** [comment]
Hi,  
   There is a parameter about this. 
    You can use `MODEL.ROI_HEADS.SCORE_THRESH` in inference. The default parameter is 0.05.

**Comment by WeihongM** [comment]
Yeap,  you are right, thanks for your help! @chengyangfu

**Comment by chengyangfu** [comment]
I'm closing this issue, please let me know if you have any further question.

**Comment by Pari-singh** [comment]
@chengyangfu could you explain why we are applying confidence threshold at the ROI head specifically and not at any other layer?
