### ISSUE TITLE
How to import cfg from from maskrcnn_benchmark??

### ISSUE THREAD

**Issue by ming71** [facebookresearch/maskrcnn-benchmark#595]
## ❓ Questions and Help
 Sorry to ask a stupid question:
I am confused by  following code in the given demo webcam.py:
`from maskrcnn_benchmark.config import cfg`
Firstly, there is no maskrcnn_benchmark folder in current directory;
Secondly , the installed package named maskrcnn-benchmark ,instead of maskrcnn_benchmark ,it can not be called directly
Using ipdb to debug,and I figure out the location.....
![image](https://user-images.githubusercontent.com/43720092/54867164-0aade300-4db8-11e9-8516-f79b73d23460.png)
Why in yacs???the code doesn't call it at all .....

**Comment by ming71** [comment]
I find that the constructor of  class CfgNode(dict)  in config.py  has been called for 18 times before  `cfg.merge_from_file(config_file)`.....
What it is that happens before loading cfg??

**Comment by LeviViana** [comment]
Did you follow the [installation](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md) steps? If everything works fine, you should be able to run `import maskrcnn_benchmark` from any folder.

When you run `from maskrcnn_benchmark.config import cfg`, the `CN()` constructor is called 18 times, you can verify it [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/b23eee0cb72af70f4e4a72e73537f0884cfd1cff/maskrcnn_benchmark/config/defaults.py).

**Comment by ming71** [comment]
> Did you follow the [installation](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md) steps? If everything works fine, you should be able to run `import maskrcnn_benchmark` from any folder.
> 
> When you run `from maskrcnn_benchmark.config import cfg`, the `CN()` constructor is called 18 times, you can verify it [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/b23eee0cb72af70f4e4a72e73537f0884cfd1cff/maskrcnn_benchmark/config/defaults.py).

Thanks for your reply , it really helps!

**Comment by fmassa** [comment]
Closing following to the comments from @LeviViana 

If you can't import `maskrcnn_benchmark`, this means that your installation didn't succeed.

**Comment by aumurphy** [comment]
@LeviViana I followed the linked installation steps (option 1) with one edit - changed cudatoolkit to 10.0. However, when I try to run Mask_R-CNN_demo.ipynb in demo, I get this: 

<img width="787" alt="Screen Shot 2019-05-29 at 1 10 11 PM" src="https://user-images.githubusercontent.com/23127040/58587843-31065980-8213-11e9-9a58-3baee2034b7e.png">

I'm not quite sure this isn't working. Any help is appreciated.
