### ISSUE TITLE
??    What's the problem

### ISSUE THREAD

**Issue by kaaier** [facebookresearch/maskrcnn-benchmark#602]
[class_logits], [box_regression]
  File "/MaskRCNN/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py", line 151, in __call__
    sampled_pos_inds_subset = torch.nonzero(labels > 0).squeeze(1)

RuntimeError: copy_if failed to synchronize: device-side assert triggered

**Comment by chengyangfu** [comment]
Hi @kaaier, 
      I guess you are running the dataset which is not COCO.  If this is the case, did you modify the `MODEL.ROI_BOX_HEAD.NUM_CLASSES`?

**Comment by kaaier** [comment]
thank u




| |
智合法律人事部
|
|
邮箱：15993096663@163.com
|

签名由 网易邮箱大师 定制

On 03/26/2019 10:16, Cheng-Yang Fu wrote:

Hi @kaaier,
I guess you are running the dataset which is not COCO. If this is the case, did you modify the MODEL.ROI_BOX_HEAD.NUM_CLASSES?

**Comment by chengyangfu** [comment]
Hi @kaaier 
I'm closing this issue, please let me know if you need any further help.
