### ISSUE TITLE
fatal error: ATen/cuda/CUDAGuard.h: No such file or directory

### ISSUE THREAD

**Issue by akiomik** [facebookresearch/maskrcnn-benchmark#607]
## 🐛 Bug

I'm facing the following error when trying to run `python setup.py build develop`:

```
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/content/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/root/miniconda/lib/python3.7/site-packages/torch/include -I/root/miniconda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda/lib/python3.7/site-packages/torch/include/TH -I/root/miniconda/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/miniconda/include/python3.7m -c /content/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.cu -o build/temp.linux-x86_64-3.7/content/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/content/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.cu:7:10: fatal error: ATen/cuda/CUDAGuard.h: No such file or directory
 #include <ATen/cuda/CUDAGuard.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
```

## To Reproduce

1. clone this repository (master, bd39d2c1019200a84a0799976e96cf96fdb0d573)
1. install requirements
1. build cocoapi with `python setup.py build_ext install`
1. run `python setup.py build develop`

## Expected behavior

No error.

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0.0.dev20190325
 - OS (e.g., Linux): Ubuntu 18.04.1 LTS
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source): `python setup.py build develop`
 - Python version: 3.7
 - CUDA/cuDNN version:
    - CUDA runtime version: 10.0.130
    - Nvidia driver version: 410.79
    - cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
 - GPU models and configuration: GPU 0: Tesla K80
 - Any other relevant information:

## Additional context

I can build that with no error when I checked out 9063850dc3069dce9d6a8ce9f65f8449b1cd3be7 in the same environment.

**Comment by fmassa** [comment]
I've reverted the offending commit, this should fix the error you were having

**Comment by akiomik** [comment]
Thank you!
