### ISSUE TITLE
Anything need to notice when we use multiple nodes?

### ISSUE THREAD

**Issue by yelantingfeng** [facebookresearch/maskrcnn-benchmark#610]
## ❓ Questions and Help
I found that in the `optimized` branch of this repo, different seeds were set manually for different ranks. However, in `master` branch there are no such codes. Is it necessary to set a different seed for each rank manually? What details should be noticed when we try to use multiple nodes? Thanks  in advance for your generous help.

**Comment by fmassa** [comment]
Hi,

I haven't tried training on multiple nodes, but I believe that in that branch they wanted to fix the random seed to try to have consistent results.
This means that they might want to set a fixed (and different) seed for each worker (for data processing etc).

**Comment by florence27** [comment]
@yelantingfeng did you try training on multiple nodes yet? If yes, do you have any advices on how to use or did you encounter any issues with it?
