### ISSUE TITLE
ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by xiaoxifei1223** [facebookresearch/maskrcnn-benchmark#614]
## To Reproduce

1. run tools\train_net.py  with Pycharm
when code running to 18-line (from maskrcnn_benchmark.engine.inference import inference)
then the bug is from maskrcnn_benchmark import _C
cannot import name _C

**Comment by fmassa** [comment]
It seems that you didn't install properly `maskrcnn-benchmark` following the instructions in the INSTALL.md.

Check https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md and make sure that it installs fine.
