### ISSUE TITLE
bug about webcam demo

### ISSUE THREAD

**Issue by sheep1234567** [facebookresearch/maskrcnn-benchmark#616]
## ❓ Questions and Help
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/48812213/55194757-caf44c00-5167-11e9-910b-d426c8462246.png">

Hi, I tried to run the webcam.py demo, but it occurs this problem, I am wondering what's wrong with it?

Thanks!

**Comment by fmassa** [comment]
I think you might have a problem with OpenCV not being able to read from your webcam.
See https://stackoverflow.com/questions/21043394/opencvs-video-capture-not-returning-an-image for more information.

I'm closing this issue as this is not a problem with `maskrcnn-benchmark`

**Comment by sheep1234567** [comment]
Thanks! @fmassa 

I tried to just run simple prediction using 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/48812213/55266378-de6fe780-5239-11e9-805e-1f13c3616f68.png">

but it occurs 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/48812213/55266393-ec256d00-5239-11e9-8ec4-f010070d737c.png">

I checked my gcc version
<img width="497" alt="image" src="https://user-images.githubusercontent.com/48812213/55266398-f7789880-5239-11e9-8d08-dc84fc775f9e.png">
and CUDA
<img width="373" alt="image" src="https://user-images.githubusercontent.com/48812213/55266408-02cbc400-523a-11e9-91a4-3378d5d6994e.png">

and I am wondering why I still cannot run simple demo. TAT

**Comment by fmassa** [comment]
I'd recommend uninstalling maskrcnn-benchmark, deleting the build folder and installing again, making sure that you are using the same python environment for compiling and for running the code

**Comment by emergencyd** [comment]
@sheep1234567 hi! have you solved the problem about webcam?
