### ISSUE TITLE
Use this model to convert a .pt file into . Pt file

### ISSUE THREAD

**Issue by lvpinrui** [facebookresearch/maskrcnn-benchmark#617]
python.py
import torch
import torchvision
import maskrcnn_benchmark
from maskrcnn_benchmark.modeling.detector import build_detection_model
from maskrcnn_benchmark.config import cfg

config_file="C:\\Anaconda3\\envs\\test\\Lib\\site-packages\\maskrcnn-benchmark\\configs\\e2e_mask_rcnn_X_101_32x8d_FPN_1x.yaml"
cfg.merge_from_file(config_file)
cfg.merge_from_list(["MODEL.DEVICE", "cpu"])
cfg.MODEL.WEIGHT='C:\\Users\\Lenovo\Desktop\\e2e_mask_rcnn_X_101_32x8d_FPN_1x.pth'

model = build_detection_model(cfg)
model.eval()
example = torch.tensor([10, 20])
trace_script_module=torch.jit.trace(model,example)
trace_script_module.save('maskSave.pt')

ht cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  num_rois = len(rois)
C:\Anaconda3\envs\test\lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\box_head\inference.py:60: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  boxes_per_image = [len(box) for box in boxes]
C:\Anaconda3\envs\test\lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\box_head\inference.py:119: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for j in range(1, num_classes):
C:\Anaconda3\envs\test\lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\box_head\inference.py:128: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  num_labels = len(boxlist_for_class)
C:\Anaconda3\envs\test\lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\box_head\inference.py:135: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  number_of_detections = len(result)
C:\Anaconda3\envs\test\lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\layers\misc.py:21: TracerWarning: new_empty is a legacy constructor and is not supported in the JIT.
  return x.new_empty(new_shape)
C:\Anaconda3\envs\test\lib\site-packages\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\mask_head\inference.py:47: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  boxes_per_image = [len(box) for box in boxes]
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    traced_net = torch.jit.trace(model,torch.rand(1, 3, 224, 224).cuda())
  File "C:\Anaconda3\envs\test\lib\site-packages\torch\jit\__init__.py", line 668, in trace
    var_lookup_fn, _force_outplace)
RuntimeError: Only tensors and (possibly nested) tuples of tensors are supported as inputs or outputs of traced functions (toIValue at C:\w\1\s\tmp_conda_3.7_105432\conda\conda-bld\pytorch-nightly_1553165830809\work\torch/csrc/jit/pybind_utils.h:97)
(no backtrace available)

**Comment by lvpinrui** [comment]
convert .pth file to .pt file

**Comment by fmassa** [comment]
Please refer to https://github.com/facebookresearch/maskrcnn-benchmark/pull/138 for tracing support
