### ISSUE TITLE
How to convert .pth to caffe2 model(.pb)?

### ISSUE THREAD

**Issue by sinboyxx** [facebookresearch/maskrcnn-benchmark#62]
## ❓ Questions and Help
I download models from the modelzoo, but I want to use them in caffe2 for inference. Can I convert the .pth file to .pb file?

**Comment by soumith** [comment]
@sinboyxx we dont provide this functionality of converting .pth to .pb, and we dont plan to provide it. However, all the models in the maskrcnn-benchmark modelzoo exist in .pb format in links given at https://github.com/facebookresearch/detectron
