### ISSUE TITLE
Prediction on panorama/huge image with large amount of objects

### ISSUE THREAD

**Issue by YubinXie** [facebookresearch/maskrcnn-benchmark#620]
## 🚀 Feature
  Prediction on panorama/huge image with large amount of objects  

## Motivation

 Big image like panorama, or image with dense objects in situation like concert, it is very memory expansive to calculate all the possibilities at one shot. Crop and stitching is one solution for this problem. However, the objects in the border will be cut into 2 parts and stitching won't recover this. Is there a way to overcome this? 

## Pitch

 One way to do it is that, instead of loading one huge image into memory at one time, feed part of the image RoI at one time and limit the memory. Another way to do prediction of overlapped cropped images and find a way to do voting on the overlap objects (same object in different image has slightly different prediction)

**Comment by fmassa** [comment]
Another possibility is to cut the image in several overlapping parts, apply the detection on each one of the parts, merge everything together and apply one last nms after the merging is done.
