### ISSUE TITLE
Can I train with multi-gpu while inference with one certain GPU during training?

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#623]

**Comment by chengyangfu** [comment]
This works. 
But you need to check there is enough memory for inference (you can reduce the batch size by setting `TEST.IMS_PER_BATCH`) and be aware this will also slow down our training.

**Comment by chengyangfu** [comment]
I'm closing this issue, please let me know if you have any further question.
