### ISSUE TITLE
problem about using the ipdb/pdb

### ISSUE THREAD

**Issue by Scarecrow0** [facebookresearch/maskrcnn-benchmark#629]
## ❓ Questions and Help
Hi.
I have some problems with using the ipdb/pdb. I don't know why I can't stop the program by set_trace(). 
Maybe there are some debug config need to turn it on？

Thank you.

**Comment by Bharat-Goyal** [comment]
Hi @Scarecrow0 how did you solve this issue? I'm dealing with a similar thing in the https://github.com/lhoyer/MIC/tree/master/det repository that relies on MaskRCNN. I'd appreciate any help!
