### ISSUE TITLE
need Retinanet!!

### ISSUE THREAD

**Issue by shiyongde** [facebookresearch/maskrcnn-benchmark#63]
## 🚀 Feature
add RetinaNet

**Comment by fmassa** [comment]
Hi

I'll be adding key points first.
But I'll keep retinanet in mind for next

**Comment by zylhub** [comment]
@fmassa It would be better if there were more guidelines for adding a network or backbone

**Comment by fmassa** [comment]
@zylhub by network you mean a different model, like Retinanet or YOLO?
I should write some documentation on that, that's a great question!

**Comment by fmassa** [comment]
RetinaNet has been implemented in https://github.com/facebookresearch/maskrcnn-benchmark/pull/102 and will be merged into master soon.

**Comment by AyeshaNirma** [comment]
@fmassa Hi, 
any updates on when it is going to be merged ?

**Comment by fmassa** [comment]
This has been implemented in https://github.com/facebookresearch/maskrcnn-benchmark/pull/102 by @chengyangfu
