### ISSUE TITLE
Dose batch size influence the inference result?

### ISSUE THREAD

**Issue by Tiamo666** [facebookresearch/maskrcnn-benchmark#633]
## ❓ Questions and Help
Hello, Thanks for your great work.
I found that I would get slightly different evaluation result when I use different batch size.
For example, on my own dataset,  batch size = 1, I got map@0.5 = 0.567, while switch batch  size = 4, I got map@0.5=0.566 , batch size = 8 , map@0.5 = 0.565.
Does the batch size will influence the inference result?

**Comment by fmassa** [comment]
This is a bit expected, because with a batch size > 1, all the images will be padded on the sides so that they have the same sizes. This in turn might lead to slightly different results.
