### ISSUE TITLE
without gpu

### ISSUE THREAD

**Issue by tatata1ta** [facebookresearch/maskrcnn-benchmark#634]
## ❓ Questions and Help
Is it possible to train without gpu? If yes what all changes i need to make?

**Comment by LeviViana** [comment]
No it isn't. For instance, there is no implementation of `ROIAlign_backward_cpu` for the moment. I think that there are no plans to enable cpu training for the moment, do you confirm that @fmassa ?

**Comment by fmassa** [comment]
Correct, no plans to enable CPU training in maskrcnn-benchmark.

Note though that all operations have been implemented on CPU in torchvision in https://github.com/pytorch/vision/pull/826 , so you could potentially use those
