### ISSUE TITLE
Batch size and RoiAlign

### ISSUE THREAD

**Issue by detectiveli** [facebookresearch/maskrcnn-benchmark#635]
Dear contributor,

Many thanks for your attention.

I got a question that if we train the module on multi-batch size (such as 2), the input of the module will be transformed to [2,3,1024,806] for picture size (1024,800) and (800,806). There is a different from 800*806 to 1024*806 but the bounding box will not fit this transform.

Could you give me some advice that where you deal with this problem?

Thanks very much

**Comment by chengyangfu** [comment]
Hi, 
   If I understood your problem properly, this part is done  in https://github.com/facebookresearch/maskrcnn-benchmark/blob/9a1ba140c8d8294f23b0a28a87bffd09d7b1adbe/maskrcnn_benchmark/structures/image_list.py#L29
  This takes the max height and width from each image to form the batch tensor. Height is max(1024, 800) and Width is (800,806). Then the image is copied and pasted to the top-left of the batch tensor.  
  So for the image(800, 806), pixels outside this region will be zero, so you don't need to change anything on the annotation.

**Comment by detectiveli** [comment]
wow
such a BRILLIANT idea! Thank you very much!
