### ISSUE TITLE
Could you give more explanantion about the dataloader you set?

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#636]
## ❓ Questions and Help
https://github.com/facebookresearch/maskrcnn-benchmark/blob/f55844c9aeb5e4d5e6b148c30cd87c64895dd268/maskrcnn_benchmark/data/build.py#L158-L169

why you use a batch_sampler instead of just using the sampler?

**Comment by fmassa** [comment]
Because we want to potentially group together images with similar aspect ratios in the same batch.
Thus, this needs to be handled at the batch sampler level, not the sampler.
