### ISSUE TITLE
How to specify num_epochs

### ISSUE THREAD

**Issue by YuhanLiu11** [facebookresearch/maskrcnn-benchmark#642]
## ❓ Questions and Help
Hi,

1. Could anyone give some suggestions on how to specify the number of training epochs in the code?
2. We only have around 60 images, and 3 classes. Any suggestions on hyper-parameter combination?

Thank you so much.

**Comment by LeviViana** [comment]
This repo's implementation is based on iterations rather then epochs. So, one simple way of setting a certain number of epochs, say `n`, is to set the number of iterations equal to `n * dataset_size / batch_size`. 

I'm not sure you can get good results by fine-tuning on a dataset having only this amount of data. I think you should try to collect more data, if you can.

**Comment by LeviViana** [comment]
I'm closing this issue, let me know if you have any further questions.

**Comment by rxqy** [comment]
Hi @LeviViana , I still have some problems regarding the number of iterations here.
Say we have 4k training images  and bs =1 , and number of iterations is set to 12k.
Is finishing the first 4k iterations equivalent to finishing the first epoch?
or, does every 4k iterations loop through the whole dataset once?

**Comment by chengyangfu** [comment]
Hi @rxqy , 
   In you case, there will be 3 epochs.  Every 4k iteration, the dataloader will go through the training images once.
