### ISSUE TITLE
How to choose a pre-training model？

### ISSUE THREAD

**Issue by dby2017** [facebookresearch/maskrcnn-benchmark#643]
I replaced WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50" in the e2e_faster_rcnn_R_50_C4_1x_1_gpu_voc.yaml2 file with WEIGHT: https://download.pytorch.org/models/resnet50-19c8e357.pth, this mAp value is from 0.73 dropped to 0.58. Have you encountered this situation? How did you choose at the time? Thank you!

**Comment by fmassa** [comment]
Here are a few reasons:
- you need to modify the mean / std for the image pre-processing to match the ones from torchvision. They are different from the ones from Caffe2
https://github.com/facebookresearch/maskrcnn-benchmark/blob/f917a555bc422ed5e06a402e739da0e21b00d0b5/maskrcnn_benchmark/config/defaults.py#L51-L53
- The image should be between 0-1 in RGB format, while Caffe2 uses BGR in 0-255
https://github.com/facebookresearch/maskrcnn-benchmark/blob/f917a555bc422ed5e06a402e739da0e21b00d0b5/maskrcnn_benchmark/config/defaults.py#L54-L55
- The stride in the 1x1 convolution is different between Caffe2 models and PyTorch models
https://github.com/facebookresearch/maskrcnn-benchmark/blob/f917a555bc422ed5e06a402e739da0e21b00d0b5/maskrcnn_benchmark/config/defaults.py#L261-L263
