### ISSUE TITLE
Image resolution of models in Model Zoo

### ISSUE THREAD

**Issue by anuar12** [facebookresearch/maskrcnn-benchmark#646]
## ❓ Questions and Help

Hi, just to get a better idea of speed performance of models, would you mind giving an image resolution of benchmarks used in the Model Zoo (the faster, FBNet ones are given but not the top ones).

Thank you!

**Comment by fmassa** [comment]
They have been all evaluated using a min size of 800 and a max size of 1333, as the models in the Caffe2 Detectron.
If you send a PR adding this information to the MODEL_ZOO it would be great!

**Comment by yxchng** [comment]
What does min_size and max_size actually mean in the settings? Shouldn't all images be resized to a fixed width and height? I am not quite sure how to set this.
