### ISSUE TITLE
-1 and 0 for precision and recall in my result

### ISSUE THREAD

**Issue by xrenaa** [facebookresearch/maskrcnn-benchmark#660]
There are -1 and 0 for precision and recall in my result. I test on my own dataset which is coco format and has 200 categories. I fished my training and run the test.py and got the results like this:
<img width="725" alt="result3" src="https://user-images.githubusercontent.com/31800248/55882273-d1a6a880-5bd6-11e9-868f-e077484fd118.png">
Need some help! 
Thank you!

**Comment by chengyangfu** [comment]
Looks like you don't have small objects in your groundtruth. 
The definition of a small object is its area is small than `32x32`.

**Comment by xrenaa** [comment]
> Looks like you don't have small objects in your groundtruth.
> The definition of a small object is its area is small than `32x32`.

**Comment by xrenaa** [comment]
Thank you！ @chengyangfu
