### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by yx3266** [facebookresearch/maskrcnn-benchmark#664]
## ❓ Questions and Help
When I try to train the model with the following command, the following error occurs. I've changed batch size to 1 and it's still the same. Can anyone help me?
<img width="913" alt="13" src="https://user-images.githubusercontent.com/34019970/55972403-03427100-5cb6-11e9-803f-2a880a07a3ec.PNG">

<img width="400" alt="1" src="https://user-images.githubusercontent.com/34019970/55972223-b1015000-5cb5-11e9-9305-16d3e35abe3e.PNG">

<img width="843" alt="3" src="https://user-images.githubusercontent.com/34019970/55972444-15bcaa80-5cb6-11e9-9e84-e645a734ef17.PNG">
<img width="816" alt="4" src="https://user-images.githubusercontent.com/34019970/55972457-1a815e80-5cb6-11e9-8995-40947a5a01d0.PNG">
<img width="634" alt="5" src="https://user-images.githubusercontent.com/34019970/55972463-1f461280-5cb6-11e9-94f7-2682a278799a.PNG">
<img width="831" alt="6" src="https://user-images.githubusercontent.com/34019970/55972475-23723000-5cb6-11e9-9169-162cf96c9b97.PNG">
<img width="825" alt="7" src="https://user-images.githubusercontent.com/34019970/55972486-2836e400-5cb6-11e9-9a01-1848fcf8866c.PNG">
<img width="841" alt="8" src="https://user-images.githubusercontent.com/34019970/55972488-2bca6b00-5cb6-11e9-83ff-bfc8d2fce656.PNG">
<img width="832" alt="9" src="https://user-images.githubusercontent.com/34019970/55972498-2e2cc500-5cb6-11e9-8221-a578240ac2ca.PNG">
<img width="789" alt="10" src="https://user-images.githubusercontent.com/34019970/55972504-3258e280-5cb6-11e9-8822-88cb4c3ccd8b.PNG">
<img width="763" alt="11" src="https://user-images.githubusercontent.com/34019970/55972523-3dac0e00-5cb6-11e9-9f1c-99b8b72acfd8.PNG">
<img width="215" alt="12" src="https://user-images.githubusercontent.com/34019970/55972532-41d82b80-5cb6-11e9-926c-91fb1aa9d32f.PNG">
There's also a lot of information similar to the picture below.
<img width="843" alt="2" src="https://user-images.githubusercontent.com/34019970/55972571-57e5ec00-5cb6-11e9-8b85-3d313ebd7a9d.PNG">

**Comment by rodrigoberriel** [comment]
Did you run `python setup.py build develop` on this machine? If you ran on another machine and synchronized with this one, this could happen.

<sup>_My eyes hurt. I see textual information in images :(_</sup>

**Comment by yx3266** [comment]
@rodrigoberriel 
Thank you for your response! I have solved this problem.

**Comment by rodrigoberriel** [comment]
@yx3266 Would you mind to close this issue?

**Comment by rodrigoberriel** [comment]
@fmassa just to let you know this issue can be closed

**Comment by sprigga** [comment]
@yx3266 I have some problem, I want to know how to solve, thank you.
