### ISSUE TITLE
change to my own dataset, there is a problem.

### ISSUE THREAD

**Issue by LU4E** [facebookresearch/maskrcnn-benchmark#67]
## ❓ Questions and Help
  File "/home/jason/github/maskrcnn-benchmark/maskrcnn_benchmark/data/collate_batch.py", line 17, in __call__
    images = to_image_list(transposed_batch[0], self.size_divisible)
  File "/home/jason/github/maskrcnn-benchmark/maskrcnn_benchmark/structures/image_list.py", line 62, in to_image_list
    batched_imgs = tensors[0].new(*batch_shape).zero_()
AttributeError: 'numpy.ndarray' object has no attribute 'new'

I change the dataset, complete the dataset, yaml, paths_catalog, but this bug don't seem like the problem of the logic. Is that the problem of version of tools again?

**Comment by fmassa** [comment]
Hi,

Your dataset needs to return (after all transforms are applied) a `torch.Tensor`.
In your case, you are returning a `numpy.ndarray`.

One possibility is to wrap your `np.array` in a `torch.Tensor`, following
```python
tensor = torch.as_tensor(array)
```

Please let me know if this isn't clear.

**Comment by LU4E** [comment]
It works. Thanks
The input could be change to tensor automatic when i use the pytorch0.4. I make a mistake.
thank for your patience.
