### ISSUE TITLE
pytorch 1.0.1

### ISSUE THREAD

**Issue by mama110** [facebookresearch/maskrcnn-benchmark#677]
## ❓ Questions and Help
Does maskrcnn-benchmark support pytorch 1.0.1 with cuda10 ?

**Comment by LeviViana** [comment]
Yes !

**Comment by M-Alami** [comment]
In install.md it says: PyTorch 1.0 from a nightly release. It will not work with 1.0 nor 1.0.1. 
Now you are saying the exact opposite. Can someone confirm this, and if so, change the comments in install.md ? 

Thanks
