### ISSUE TITLE
Fix two typos in the abstractions.md document: baseline to benchmark and BoxList argument size to image_size

### ISSUE THREAD

**Issue by cpoptic** [facebookresearch/maskrcnn-benchmark#68]
Here is an example on how to create a `BoxList` from a list of coordinates:
```python
from maskrcnn_baseline.structures.bounding_box import BoxList, FLIP_LEFT_RIGHT
from maskrcnn_benchmark.structures.bounding_box import BoxList, FLIP_LEFT_RIGHT

width = 100
height = 200
@ -49,7 +49,7 @@ boxes = [
  [10, 10, 50, 50]
]
# create a BoxList with 3 boxes
bbox = BoxList(boxes, size=(width, height), mode='xyxy')
bbox = BoxList(boxes, image_size=(width, height), mode='xyxy')

# perform some box transformations, has similar API as PIL.Image
bbox_scaled = bbox.resize((width * 2, height * 3))

**Comment by fmassa** [comment]
Can you send a PR fixing the documentation?

**Comment by belowmit** [comment]
Sent PRs to replace baseline with benchmark and size with image_size. Other differences between above text and documentation in ABSTRACTIONS.md were left unchanged.

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/81 and https://github.com/facebookresearch/maskrcnn-benchmark/pull/82

Thanks @belowmit for the PRs!
