### ISSUE TITLE
Will this benchmark support the deformable convnets？

### ISSUE THREAD

**Issue by jinzhenhh** [facebookresearch/maskrcnn-benchmark#681]
## ❓ Questions and Help
if the deform-conv will be added into this benchmark repo, that would be so great!...

**Comment by zimenglan-sysu-512** [comment]
hi @jinzhenhh 
i will add dcn in the next full days, please wait.

**Comment by zimenglan-sysu-512** [comment]
hi @jinzhenhh 
i add a PR #693 for dcn.

**Comment by jinzhenhh** [comment]
@zimenglan-sysu-512 nice to here that ^_^  and thanks for your open methods!
do you have test its performance after adding the dcn modules?

**Comment by zimenglan-sysu-512** [comment]
please see `configs/dcn/README.md`.

**Comment by jinzhenhh** [comment]
> please see `configs/dcn/README.md`.

thanks!!!

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/693
