### ISSUE TITLE
Which ROI mode should I select to run on CPU

### ISSUE THREAD

**Issue by zhuoc** [facebookresearch/maskrcnn-benchmark#684]
Hi,

I am trying to run this model on CPU (both forward and backward pass). However, I got error "RuntimeError: Not implemented on the CPU (ROIAlign_backward......" 

Looking at the code at maskrcnn_benchmark/csrc/ROIAlign.h and ROIPool.h, it seems neither fully supports cpu operations. Is there a particular ROI mode I should use to make it run on CPUs, then?

Thanks

**Comment by LeviViana** [comment]
Maybe the thread #634 could help you understand why it doesn't work.

**Comment by zhuoc** [comment]
Thanks, it helps.
