### ISSUE TITLE
Finetuning on Detectron vs. MODEL_ZOO

### ISSUE THREAD

**Issue by laberpalaber** [facebookresearch/maskrcnn-benchmark#687]
## ❓ Questions and Help
I want to finetune on my own dataset starting from a model pretrained on COCO. I had a look at several issues and I managed to adapt the models and run a training.

However in most issues people want to use the detectron models and I am wondering why this is the case.
* Aren't the models in MODEL_ZOO trained on COCO?
* What exactly is the difference between the models from MODEL_ZOO and the ones from Detectron (except for the format)?
*Actually I ran a training on a very small dataset starting from detectron and from MODEL_ZOO and the results with the second were better.*

Thanks in advance!

**Comment by LeviViana** [comment]
Maybe the answer I gave at #598 could help you understand a little better the purpose of this repo. Please tell me if it isn't enough to answer your questions.

**Comment by laberpalaber** [comment]
Thanks for your reply! 

Unfortunately I still don't understand what is the difference between the models from MODEL_ZOO and the ones from Detectron and why my training result is better if I start from MODEL_ZOO instead of Detectron.

Would be great if you could clarify that for me!

**Comment by GiuliaP** [comment]
@LeviViana thanks for pointing to that reply. So if I understood your answer, in order to fine-tune on a custom dataset starting from COCO weights, do you confirm that the proper way of proceeding is to download a model from the zoo (rather than from Detectron and then converting it to pth)?

**Comment by LeviViana** [comment]
> Thanks for your reply!
> 
> Unfortunately I still don't understand what is the difference between the models from MODEL_ZOO and the ones from Detectron and why my training result is better if I start from MODEL_ZOO instead of Detectron.
> 
> Would be great if you could clarify that for me!

This repo is meant to reproduce Detectron's results while using less resources. I honestly don't know why  your fine-tuning works better using this repo's weights, it wasn't built for that purpose. I'm not sure that it can be guaranteed in general. But it would be interesting to make some further experiments. @fmassa, what do you think?

@GiuliaP, I hope this answers your question as well!

**Comment by laberpalaber** [comment]
@LeviViana thanks!
I checked again carefully and the weights from the Detectron model were not loaded correctly, which explains the worse performance, so I suppose there shouldn't be any difference normally.

**Comment by fmassa** [comment]
I'm late for the discussion, but the weights from the MODEL_ZOO and from Detectron should be statistically the same.
