### ISSUE TITLE
Calculate mAP for each class?

### ISSUE THREAD

**Issue by Jacobew** [facebookresearch/maskrcnn-benchmark#690]
## ❓ Questions and Help
Hi, I want to calculate box AP and mask AP for each class, which is not currently supported in your code. I found this module [somewhere](https://github.com/cocodataset/cocoapi/pull/282) in cocoapi. However, the evaluation code  in [coco_eval.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py) in this repo is an alternative rather than a standard version. Can I replace coco_eval.py with the one in cocoapi? If not, I'll appreciate it if your can give some advice on it.

**Comment by chengyangfu** [comment]
Hi @Jacobew, 
    You can find the answer in this thread.   
    https://github.com/facebookresearch/maskrcnn-benchmark/issues/524
    I think the modification should be easy and straightforward.

**Comment by Jacobew** [comment]
It works, thanks a lot!  @chengyangfu

**Comment by fmassa** [comment]
@Jacobew would you mind sending a PR adding a section somewhere in the documentation highlighting the solution?

**Comment by Jacobew** [comment]
@chengyangfu My Pleasure. Please check it out [here](https://github.com/facebookresearch/maskrcnn-benchmark/pull/705).
