### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, list found

### ISSUE THREAD

**Issue by wlgcqh** [facebookresearch/maskrcnn-benchmark#7]
## 🐛 Bug
  File "/home/workplace/opt/anaconda2/lib/python2.7/distutils/unixccompiler.py", line 121, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
TypeError: coercing to Unicode: need string or buffer, list found

## To Reproduce

1.python setup.py build_ext install

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux):centos 7.0
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build_ext install
 - Python version:2.7.14
 - CUDA/cuDNN version:9.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by soumith** [comment]
I think we tested this only in Python3. We can test in Python 2.7 environment and push patches tomorrow.

**Comment by fmassa** [comment]
Yes, our code currently have (very few) places where we assumed Python3 was available.
I'll push some fixes to make this Python2 compatible today

**Comment by fmassa** [comment]
@wlgcqh I have the impression that your error message comes from the cocoapi compilation, and not from maskrcnn-benchmark?

I've just successfully compiled `maskrcnn-benchmark` using Python 2.7.

I expect some parts of the code not to work, but I'm working on fixing them now.

**Comment by wlgcqh** [comment]
> @wlgcqh I have the impression that your error message comes from the cocoapi compilation, and not from maskrcnn-benchmark?
> 
> I've just successfully compiled `maskrcnn-benchmark` using Python 2.7.
> 
> I expect some parts of the code not to work, but I'm working on fixing them now.

I have installed cocoapi

**Comment by fmassa** [comment]
So why did you use the installation instructions from cocoapi to install the library?
You mentioned that you used `python setup.py build_ext install `, but for the library we use `python setup.py build develop`.
