### ISSUE TITLE
Problems regarding invalid  instances in PolygonList?

### ISSUE THREAD

**Issue by rxqy** [facebookresearch/maskrcnn-benchmark#704]
## ❓ Questions and Help

Hi, I'm training maskrcnn with my own dataset. 
However, there seems to be a problem with the PolygonList.
In the segmentation_mask,  it would convert the PolygonLists and filter out some instances.
https://github.com/facebookresearch/maskrcnn-benchmark/blob/91d9fb9ffb1722252cdf02d4b2a0a24ce5d10883/maskrcnn_benchmark/structures/segmentation_mask.py#L362-L366

However, when later indexing the polygons, it still uses the 'origin' item. (before filtering)
https://github.com/facebookresearch/maskrcnn-benchmark/blob/91d9fb9ffb1722252cdf02d4b2a0a24ce5d10883/maskrcnn_benchmark/structures/segmentation_mask.py#L413-L427

So I might have 5 polygons before, and one might be invalid or somehow?
After filtering, I would only have 4 left, but in getitem, the item is still 0,1,2,3,4
this would give me an outofrange error.
Is there any way that I can fix this inconsistency without changing my annotation?

Many thanks!

**Comment by fmassa** [comment]
Is my understanding right that the error appears after filtering out all empty PolygonList, which means that you are left without any polygons?

**Comment by rxqy** [comment]
@fmassa No. I'm left with the valid polygons. But the code would still index the invalid ones.

For example, the original annotation might have  5 polygons in one image, with the last one being invalid.
However, here
https://github.com/facebookresearch/maskrcnn-benchmark/blob/91d9fb9ffb1722252cdf02d4b2a0a24ce5d10883/maskrcnn_benchmark/structures/segmentation_mask.py#L425-L426
self.polygons is the four valid polygons, but the item is still [0,1,2,3,4], (because we have 5 annotation), this gives me the out of range error.
In fact after I look into the code, the new PolygonList only keeps the polygons with length greater than 6. 
So I filter out all the polygons with len< 6 in my annotation and the code works fine with me.

**Comment by Zy1013921842** [comment]
> @fmassa No. I'm left with the valid polygons. But the code would still index the invalid ones.
> 
> For example, the original annotation might have 5 polygons in one image, with the last one being invalid.
> However, here
> https://github.com/facebookresearch/maskrcnn-benchmark/blob/91d9fb9ffb1722252cdf02d4b2a0a24ce5d10883/maskrcnn_benchmark/structures/segmentation_mask.py#L425-L426
> 
> 
> self.polygons is the four valid polygons, but the item is still [0,1,2,3,4], (because we have 5 annotation), this gives me the out of range error.
> In fact after I look into the code, the new PolygonList only keeps the polygons with length greater than 6.
> So I filter out all the polygons with len< 6 in my annotation and the code works fine with me.

Hello, miss.
I guess I met the same problem as you did, can you tell me what does filtering out all the polygons with len<6 in your annotation mean? Does it have anything to do with filtering item?

**Comment by rxqy** [comment]
Hi @Zy1013921842 , I'm running on my own dataset.  Training on coco should work fine.
However, in my case, my polygon is not a valid polygon.

> https://github.com/facebookresearch/maskrcnn-benchmark/blob/91d9fb9ffb1722252cdf02d4b2a0a24ce5d10883/maskrcnn_benchmark/structures/segmentation_mask.py#L178-L199

You can look into L 196 here, a polygon should have at least 3 sets of coordinates. Due to some annotation error, one of my polygons is only just one line ( 2 sets of coordinates ). This gives me the above error. Filtering these invalid polygons in your annotation.json will do.

**Comment by Zy1013921842** [comment]
@rxqy Thank you so much! I do have some line labels, that's the key of this problem, although I meet other problems after solving this one. Thanks again!
