### ISSUE TITLE
A question about the implementation in roi heads

### ISSUE THREAD

**Issue by rxqy** [facebookresearch/maskrcnn-benchmark#716]
## ❓ Questions and Help
Hi, I'm reading into the codes and notice a minor problem about roi heads.
https://github.com/facebookresearch/maskrcnn-benchmark/blob/d44c3fd86220d6b1ca5fe61e7f258fecabec396d/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py#L28-L54

In the mask head and the keypoint head, both features are set to roi_box_features if we share the feature extractor.

However, if we turn both masks on, x here (keypoint features)
https://github.com/facebookresearch/maskrcnn-benchmark/blob/d44c3fd86220d6b1ca5fe61e7f258fecabec396d/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py#L42-L50
would become the result from the mask head. (not the origin roi_box_features)
https://github.com/facebookresearch/maskrcnn-benchmark/blob/d44c3fd86220d6b1ca5fe61e7f258fecabec396d/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py#L39

I understand this wont happen in all the configs files
I'm just curious, is this the intended behavior? If so, why?
Or should the mask/keypoint_features be always set to roi_box_features?

From Fig 7 from the MASKRCNN paper, it seems reasonable to turn both masks on,
i.e, segment the person first then find the keypoints, right?

Many thanks!

**Comment by fmassa** [comment]
This is intended, but probably not the best one might want to do.

In order to overcome this and make things completely generic, we would need to put everything (all the heads) inside the same `forward`, for maximum flexibility.

**Comment by rxqy** [comment]
Understood. Many thanks!
