### ISSUE TITLE
Torchvision commit #872 breaks COCODataset.__getitem__(idx)

### ISSUE THREAD

**Issue by qizhuli** [facebookresearch/maskrcnn-benchmark#738]
### Summary
The latest torchvision after commit #872 ([[RFC] Add support for joint transformations in VisionDataset](https://github.com/pytorch/vision/commit/0c36735d2ca6dfbb56a95da444b708b7c535a2c8)) modifies its `CocoDetection` class and breaks the coco dataset in this repository (`COCODataset`), when the `transforms` attribute of the `COCODataset` is not `None`. 

The torchvision installed from conda as per instructions in [INSTALL.md](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md) is from an older version which still works. Therefore, this issue is not of immediate concern, but might be worth consideration to be future proof.

### Main Cause
Currently, `COCODataset` is written as a child class of `CocoDetection`. 

The torchvision commit #872 changes the `CocoDetection` class by combining its `transform` (w/o `s`) and `target_transform` attributes into a unified `transforms` (w/ `s`) attribute, which unfortunately is already in use by the `COCODataset` class of this repository. 

### Description
The problem manifests when the `__getitem__` method of `COCODataset` is called. 

According to the current [implementation](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/datasets/coco.py#L67), this would invoke the `__getitem__` method of its superclass `CocoDetection`. After commit #872, `CocoDetection.__getitem__` would pickup the `transforms` attribute of `COCODataset` and attempt to perform these transforms [here](https://github.com/pytorch/vision/blob/0c36735d2ca6dfbb56a95da444b708b7c535a2c8/torchvision/datasets/coco.py#L113-L114). 

This behaviour not only leads to errors since the `transforms` are meant for targets of `BoxList` class, but more importantly, is certainly not what is intended.

## To Reproduce

1. Use the latest torchvision from the github source.
2. Run any experiment that performs `transforms` on the image and target.

## Possible Solution

Rename the `transforms` attribute of `COCODataset` to something else.

**Comment by fmassa** [comment]
Yes, a quick workaround is to rename it `_transforms`.

**Comment by fmassa** [comment]
If you send a PR here I'd be happy to merge

**Comment by qizhuli** [comment]
@fmassa Sure, PR #744 sent.

**Comment by fmassa** [comment]
Fixed via #744
