### ISSUE TITLE
Getting proposals for a pretrained RPN

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/maskrcnn-benchmark#745]
## ❓ Questions and Help
Hi team!
Is there an easy way to get the top 1000 proposals using a pretrained RPN?
Thanks!
--Issam

**Comment by fmassa** [comment]
Just take one of the configs from https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/rpn_R_50_FPN_1x.yaml , download the corresponding weight from Detectron MODEL_ZOO, and that should be all (I didn't get the chance to update configs which have pre-trained weights, but they work)
