### ISSUE TITLE
Can this run on CUDA 9.2 ? 

### ISSUE THREAD

**Issue by guanbin1994** [facebookresearch/maskrcnn-benchmark#75]
## ❓ Questions and Help
ImportError: /home/l547/github/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEl

Collecting environment information...
PyTorch version: 0.4.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 410.73
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so
/usr/local/cuda-9.2/lib64/libcudnn.so.7
/usr/local/cuda-9.2/lib64/libcudnn.so.7.3.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.4.1.post2               <pip>
[conda] torch-nightly             1.0.0.dev20181029           <pip>

**Comment by fmassa** [comment]
Yes, this library can run on CUDA 9.2

But it requires PyTorch 1.0, and you have PyTorch 0.4.1 installed as well, and this might be conflicting with your install.

For example, if you do
```python
import torch
print(torch.__version__)
```
I believe it will print `0.4.1`.

Please follow the installation instructions in https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md for it to work. I would advise creating a new conda environment.

Let me know if you still have issues after following the instructions in the `INSTALL`.

**Comment by guanbin1994** [comment]
First,thanks for your reply!
Actually, I totally follow the  installation instructions.
Because of mu CUDA is 9.2, soI installed pytorch 1.0 by run:  
 conda install pytorch-nightly cuda92 -c pytorch

Then, when I install torchvision run:
```
cd ~/github
git clone https://github.com/pytorch/vision.git
cd vision
python setup.py install

```
the PyTorch 0.4.1 automatically be installed.

**Comment by fmassa** [comment]
This is weird, this PyTorch 0.4.1 installation should only happen if installing torchvision through conda / pip.

Can you try installing first torchvision, and then pytorch?
