### ISSUE TITLE
has someone merged the bn into conv?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [facebookresearch/maskrcnn-benchmark#769]
merging bn into conv can speed up the inference, so has someone merged the bn into conv?

**Comment by lsrock1** [comment]
I tried but there was no difference.

**Comment by zimenglan-sysu-512** [comment]
thanks

**Comment by chengyangfu** [comment]
The speedup only worked before Nvidia optimized the BN in cuDNN. 
I used this trick in Caffe at that time the BN is implemented in CUDA code. But once BN is optimized in cuDNN,  the improvement is pretty minor.
