### ISSUE TITLE
can not import name '_c'

### ISSUE THREAD

**Issue by xiaohai12** [facebookresearch/maskrcnn-benchmark#783]
## ❓ Questions and Help
Hi, I just use the Dockerfile under docker folder to create docker image and there are lots of warning also when I try to run train-net.py, it was written "can not import name _c"

**Comment by meteorshowers** [comment]
I met the same problem, can you tell me how to solve it? @xiaohai12

**Comment by xiaohai12** [comment]
> I met the same problem, can you tell me how to solve it? @xiaohai12

please make sure that your environment is the same as requirement
