### ISSUE TITLE
Overflow due to IntTensor in all_gather

### ISSUE THREAD

**Issue by caiqi** [facebookresearch/maskrcnn-benchmark#796]
## 🐛 Bug
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/utils/comm.py#L66-L67 use IntTensor to store tensor size may cause an overflow. For example, a tensor of shape [50000, 2000, 6] (50k images with each have 2k bounding boxes) will cause torch.IntTensor([tensor.numel()]).to("cuda") equals -1894966895. It seems that LongTensor is better choice for storing tensor size?

**Comment by fmassa** [comment]
Sure, changing Int to Long sounds good to me. Can you send a PR?

**Comment by caiqi** [comment]
Sure, I have created a pull request: https://github.com/facebookresearch/maskrcnn-benchmark/pull/799

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/799
