### ISSUE TITLE
Confused : Why out0 = self.conv3(out) in resnet.py

### ISSUE THREAD

**Issue by stevehjc** [facebookresearch/maskrcnn-benchmark#797]
## ❓ Questions and Help
Why use the `out0` in resnet.py? 
I think the out0 is unnecessary and it consumes more memory.
```python
    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = F.relu_(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = F.relu_(out)

        out0 = self.conv3(out)
        out = self.bn3(out0)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = F.relu_(out)

        return out
```
https://github.com/facebookresearch/maskrcnn-benchmark/blob/1127bdd368613f320f7b113320e62994c0baa216/maskrcnn_benchmark/modeling/backbone/resnet.py#L335

**Comment by fmassa** [comment]
Yes it's unnecessary, and it's a debug artifact from a long time ago. a PR cleaning it is welcome

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/858
