### ISSUE TITLE
About at::Tensor.data<scalar_t>() function in roialign

### ISSUE THREAD

**Issue by sadicLiu** [facebookresearch/maskrcnn-benchmark#800]
## ❓ Questions and Help
```  maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp
AT_DISPATCH_FLOATING_TYPES(input.type(), "ROIAlign_forward", [&] {
    ROIAlignForward_cpu_kernel<scalar_t>(
         output_size,
         input.data<scalar_t>(),
         spatial_scale,
         channels,
         height,
         width,
         pooled_height,
         pooled_width,
         sampling_ratio,
         rois.data<scalar_t>(),
         output.data<scalar_t>());
  });
````
My question is does the at::Tensor.data<scalar_t>() function transform the tensor to one dimensional array? And what's the purpose of this operation?

**Comment by yangwf1** [comment]
hi, i'm also curious about this, have you figured it out?

**Comment by fmassa** [comment]
Hey,

all this does it to get the pointer to the C data.

So `input.data<scalar_t>()` returns a `scalar_t *` type.

**Comment by sadicLiu** [comment]
> hi, i'm also curious about this, have you figured it out?

just as the author said, `input.data<scalar_t>()`returns a `scalar_t *` type, and you can use this pointer to visit multi dimension tensor data.
