### ISSUE TITLE
multi-task loss

### ISSUE THREAD

**Issue by zxpeter** [facebookresearch/maskrcnn-benchmark#803]
## ❓ Questions and Help
Hi, 
I'm using MRCNN and have some question about the understanding of the loss.
Do we use multi-task loss for fastercnn branch's classification and regression？
How do we combine the rpn/frcnn/mrcnn 's losses together?
Do we just simply stack the losses together and throw it into trainer or do we have other kind of ways?
Any help would be appreciate.

**Comment by ppwwyyxx** [comment]
They are added together.

**Comment by fmassa** [comment]
As @ppwwyyxx said, we sum all the losses together for multitasking.
