### ISSUE TITLE
Worse performance when enable FP16 training

### ISSUE THREAD

**Issue by Retiina** [facebookresearch/maskrcnn-benchmark#807]
## ❓ Questions and Help
When I enabled FP16 training, the speed is lower than FP32, and the memory is even larger than FP32, thought the final ap box and ap mask is almost the same with FP32, is this normal?

I test the config `e2e_mask_rcnn_R_50_FPN_1x.yaml` on 8 V100, I only change the `DTYPE` from `float32` to `float16` at this line https://github.com/facebookresearch/maskrcnn-benchmark/blob/16b8b09aea1b7ebee52bf8bf33098bdcf7b1cdf2/maskrcnn_benchmark/config/defaults.py#L443. 
Is there something wrong that I did? Thanks in advance!

**Comment by fmassa** [comment]
cc @slayton58 . 

What is your CUDNN version? I think that in order to expect a potential improvement, you need CUDNN 7.4

**Comment by Retiina** [comment]
I use cudnn 7.0.4, cuda 9.0, I will have a try on CUDNN7.4. Thanks for your reply!

**Comment by fmassa** [comment]
Oh, if you are not using CUDNN 7.4, then the slowdown is expected.

I'm closing this issue then, but please let us know if it's still slower after moving to CUDA 10 / CUDNN 7.4

**Comment by slayton58** [comment]
@fmassa is correct, you need a later version of cuDNN (v7.4 should be ok, but v7.6 is available now) in order to get best speedups

**Comment by zimenglan-sysu-512** [comment]
hi @slayton58
how much speed up using higher version of cuDNN?

**Comment by nicolasCruzW21** [comment]
I am also curious about this. Has anyone performed a bechmark on fp32 vs fp16 and on diferent cudnn versions?

**Comment by Retiina** [comment]
@fmassa @slayton58  Now I upgrade cuda from 9.0 to 10.1, cudnn from 7.0 to 7.5, however, when I test fp16 on that, the speed is still similar and even slower than FP32. Is it normal? 
My environment is 8-v100, cudnn 7.5, cuda10.1,  driver version Driver Version: 418.67, pytorch-1.1.0

Here is the screenshot:

This is fp32
<img width="970" alt="Screen Shot 2019-06-08 at 6 02 19 PM" src="https://user-images.githubusercontent.com/49137956/59145557-1359a100-8a18-11e9-9763-3d6f70b02fb2.png">



This is the fp16, loss scale show I am using fp16 mode training
<img width="967" alt="Screen Shot 2019-06-08 at 5 58 38 PM" src="https://user-images.githubusercontent.com/49137956/59145545-ec02d400-8a17-11e9-9b16-2fcfa6c7b2b2.png">

I am really confused about that. Have anyone train fp16 and get a speed and memory gain?

**Comment by dvd42** [comment]
I am also facing the same issue, any updates?

**Comment by diegodgs** [comment]
I am also facing similar issue too, mixed precision training are using much more memory than fp32 normal mode. My env: Ubuntu 18.04, python 3.6, pytorch 1.1.0, cuda 10.0, cudnn 7.6.

**Comment by ilanbiala** [comment]
Any update on this?
