### ISSUE TITLE
ImportError: /home/jiang/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19NonVariableTypeMode10is_enabledEv

### ISSUE THREAD

**Issue by jiangkeng123** [facebookresearch/maskrcnn-benchmark#813]
ImportError: /home/jiang/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19NonVariableTypeMode10is_enabledEv

**Comment by githubgsq** [comment]
@jiangkeng123 before you build, try to export CUDA_HOME=/cuda_dir, and build again.

**Comment by AlexG1105** [comment]
The same thing happens for me. Whenever I open python and attempt to import torch vision, this error pops up.

**Comment by AlexG1105** [comment]
Ok, I think you have to downgrade your torch vision version. Do
`conda uninstall pytorch`
`conda uninstall pytorch-nightly`
`conda uninstall torchvision`

then redo this:
`conda install -c pytorch pytorch-nightly torchvision=0.2.2 cudatoolkit=10.0`

**Comment by fmassa** [comment]
What happens is that you compiled with one version of PyTorch, and when you updated torchvision it reinstalled a new version of PyTorch.

Another solution is just to recompile `maskrcnn_benchmark` after deleting the `build` folder.

**Comment by 1032697379** [comment]
Hello, I have the same error, and finally how do you solve this problem?

**Comment by BCJuan** [comment]
As @AlexG1105 commented, apparently you have to downgrade torchvision. 

For the [tutorial](https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html) I had installed 0.3.0, but executing `conda install -c pytorch torchvision=0.2.2` solved the issue.

Seems you do not need to uninstall other modules.

**Comment by sureatgithub** [comment]
@fmassa does this whole maskrcnn-benchmark program has to work using pytorch 1.0 and torchvision 0.2 ? I have another piece of code using torchvision 0.3 (torchvision.models.detection.xxx), and want to make two of them work in the same conda environment, does that possible?
Thanks!

**Comment by Liusandian** [comment]
> @jiangkeng123 before you build, try to export CUDA_HOME=/cuda_dir, and build again.

can you give more detail about the cuda_dir?such as ?
