### ISSUE TITLE
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by jjjenny1008** [facebookresearch/maskrcnn-benchmark#815]
## ❓ Questions and Help
I have read several answers about the same question, but there is no way could solve my question. My pytorch vision is 1.0.1, and I guess it's not the reason of my error. I could not install pytorch-nightly, could that be the reason? I would appreciate it if someone could answer my questions!

**Comment by manueldiaz96** [comment]
Why did you closed it? Did you found a solution?

**Comment by manueldiaz96** [comment]
For anyone looking for a solution, https://github.com/facebookresearch/maskrcnn-benchmark/issues/771#issuecomment-498996443
