### ISSUE TITLE
Model save path

### ISSUE THREAD

**Issue by yaoliUoA** [facebookresearch/maskrcnn-benchmark#83]
## ❓ Questions and Help
Hi 

I noticed that after training, all models are saved in the current folder "./maskrcnn-benchmark". However, this can be a mess if one run multiple training experiments (as model names are definited by the common name "model_***"). I do not see the there is a model save path option in the `cfg`. Any suggestions for this issue?

**Comment by fmassa** [comment]
Hi,

You can set the `cfg` option `OUTPUT_DIR`, which specifies the path to save the logs / models / inference results.

I'm closing this issue, but let me know I'd you have further questions
