### ISSUE TITLE
Why not just change repository name to PyTorch-Detectron

### ISSUE THREAD

**Issue by peng-peter-li** [facebookresearch/maskrcnn-benchmark#830]
## ❓ Questions and Help
Why not just change repository name to "PyTorch-Detectron".

It's quite annoying to explain "maskrcnn-benchmark is not only for Mask R-CNN, in fact, it contains blah, blah" when promoting maskrcnn-benchmark to others.

It could be simplified as FAIR official PyTorch version of Detectron.

**Comment by soumith** [comment]
FAIR already published detectron, which is caffe2 -- so that is confusing. detectron.pytorch is already taken by pytorch project.

We pushed this as maskrcnn-benchmark for complicated reasons that i cant explain.
