### ISSUE TITLE
请问一下，怎么读取目标的具体位置坐标

### ISSUE THREAD

**Issue by linhuaiyuan** [facebookresearch/maskrcnn-benchmark#833]

**Comment by fmassa** [comment]
From google translate:

> Excuse me, how to read the specific position coordinates of the target

If that's the question, I'd recommend looking at http://cocodataset.org/#format-data

**Comment by linhuaiyuan** [comment]
@fmassa 你好，这个网址我进不去，可以麻烦您详细指导一下吗？非常感谢

**Comment by fmassa** [comment]
Sorry, I don't speak chinese.
