### ISSUE TITLE
Getting Bounding Boxes for images

### ISSUE THREAD

**Issue by goyalsaransh97** [facebookresearch/maskrcnn-benchmark#855]
I'm using the COCO dataset but for VQA. How can I get the bounding boxes with object labels(object labels are the main focus here) for the objects in the image? I just want the object labels as a list or array, and not superimposed on the image as in the demo.
Is there a function or a script for this?

**Comment by fmassa** [comment]
This is the result of calling `model(images)`, it returns the bounding boxes.

Also, note that it might be easier to use `torchvision` for your needs.
Check the demo in https://colab.research.google.com/github/pytorch/vision/blob/temp-tutorial/tutorials/torchvision_finetuning_instance_segmentation.ipynb
and the accompanying blog post https://pytorch.org/blog/torchvision03/

**Comment by goyalsaransh97** [comment]
On using torchvision.models.detection, I'm getting error " module 'torchvision.models' has no attribute 'detection'". Do you have any suggestions w.r.t. solving this? My pytorch version is 1.0.1 with torchvision 0.2.2.

**Comment by fmassa** [comment]
@goyalsaransh97 you need to update torchvision to version 0.3, and Pytorch to version 1.1 in order to be able to use the object detection functionality in torchvision
