### ISSUE TITLE
Installation Error: canot import _C from maskrcnn_benchmark

### ISSUE THREAD

**Issue by xiyinmsu** [facebookresearch/maskrcnn-benchmark#862]
## ❓ Questions and Help
Hi All, I am getting stuck with an installation problem for a while and could not figure out the issue. It would be great if anyone could provide some clue on how to further debug. This is a repeated issue I have seen in the issue lists. But none of the solutions work for me so far. 

So I have been using this repo. for a while, recently I have to re-install everything all over again. So I have installed a new conda, created a new environment following INSTALL.md. I use "which pip", "which conda" and "which python" to check I am using the right version inside the conda environment. I also clean the existing build/ folder before I recompile each time. However, I am stilling seeing the problem of "cannot import name _C from maskrcnn_benchmark". 

I tried a few different versions (I remove old version when installing a different version). It can compile without any error but when I run the code, it will show the above import error. 

Here is what I got: 
pytorch@1.2.0.dev20190604 and torchvision@0.3.0, I got error in "from torchvision import _C". 
pytorch@1.2.0.dev20190604 and torchvision@0.2.2, I got error in "from maskrcnn_benchmark import _C"
pytorch@1.1.0 and torchvision@0.2.2, I got error in "from maskrcnn_benchmark import _C". 

Any comments are appreciated. Thanks!

**Comment by xiyinmsu** [comment]
I have repeated the installation process today and it works fine now. I think it is a pytorch problem that has been fixed these two days. Thanks and I am closing it now.

**Comment by ztt0821** [comment]
> I have repeated the installation process today and it works fine now. I think it is a pytorch problem that has been fixed these two days. Thanks and I am closing it now.

May I ask your successful version of pytorch and torchvision?

**Comment by xiyinmsu** [comment]
> > I have repeated the installation process today and it works fine now. I think it is a pytorch problem that has been fixed these two days. Thanks and I am closing it now.
> 
> May I ask your successful version of pytorch and torchvision?

torch: 1.2.0.dev20190605
torchvision: 0.2.2

**Comment by LYH-YNU** [comment]
How to install torch: 1.2.0.dev20190605, I follow the instructions of install.md, and the torch version is always 1.0.0dev20190328, and there is always the error of 'cannot import _C from maskrcnn_benchmark' , I have no idea about this.

**Comment by ztt0821** [comment]
> How to install torch: 1.2.0.dev20190605, I follow the instructions of install.md, and the torch version is always 1.0.0dev20190328, and there is always the error of 'cannot import _C from maskrcnn_benchmark' , I have no idea about this.

install torch-nightly

**Comment by LYH-YNU** [comment]
> > How to install torch: 1.2.0.dev20190605, I follow the instructions of install.md, and the torch version is always 1.0.0dev20190328, and there is always the error of 'cannot import _C from maskrcnn_benchmark' , I have no idea about this.
> 
> install torch-nightly

pip install or conda install?

**Comment by ztt0821** [comment]
> > > How to install torch: 1.2.0.dev20190605, I follow the instructions of install.md, and the torch version is always 1.0.0dev20190328, and there is always the error of 'cannot import _C from maskrcnn_benchmark' , I have no idea about this.
> > 
> > 
> > install torch-nightly
> 
> pip install or conda install?

please have a look at the official website of Pytorch. You can choose stable or preview(nightly) on the first line.

**Comment by harshgrovr** [comment]
@xiyinmsu  How to clear the build?

**Comment by xiyinmsu** [comment]
> @xiyinmsu How to clear the build?

python setup.py clean --all
