### ISSUE TITLE
With conda2+python2.7+torch1.0.0+torch-nightly1.0.0+torchvision0.2.1, I still get the problem of No module named'maskrcnn_benchmark' while running the demo!  

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#866]
## ❓ Questions and Help
I tried several times of re-installing these, however it continues showing that no module named'maskrcnn_benchmark'

**Comment by manueldiaz96** [comment]
Did you compile it?
If you are using it with GPU support, what version of Cuda Toolkit are you using?
Do you have to use Python2.7? Why not use Python 3?

Maybe try as said on https://github.com/facebookresearch/maskrcnn-benchmark/issues/223#issuecomment-497991708 and how I got it to compile on https://github.com/facebookresearch/maskrcnn-benchmark/issues/771#issuecomment-498996443

**Comment by SkeletonOne** [comment]
@manueldiaz96 
Yeah i did compile it, my cuda version is 9.0, however it is not successful when i run  the 'conda install -c pytorch pytorch-nightly torchvision cudatoolkit=9.0' command, it shows that could not find cudatoolkit=9.0.
I installed pytorch-nightly and torchvision through pip command.
Since I got anaconda2, I have to use Python2.7, is it possible to use conda2+Python3? Cuz the envirionment seems to be fragile when I uninstall conda2 and install conda3+Python3.

**Comment by manueldiaz96** [comment]
Are you on Linux or Windows?
If you are in Linux, could you post the output of `gcc --version` and `nvidia-smi` please?
These are to check the version of the compiler and your drivers, because if you have `gcc 6.4.0` and `CUDA 9.0` this might be your problem as stated on [the troubleshooting section](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/TROUBLESHOOTING.md).

**Comment by manueldiaz96** [comment]
Were you able to solve your problem? If so, could you share the solution? 
Thanks!

**Comment by SkeletonOne** [comment]
@manueldiaz96  Well, the solution is simple. I just changed my environment to torch==1.1.0 and torch-nightly==1.2.0 :)

**Comment by manueldiaz96** [comment]
Thanks!
A word of advice: When you close an issue, share the reason and all the information you can about why you did it, **it may help others in the future!**.

**Comment by SkeletonOne** [comment]
@manueldiaz96  Yeah you're right. Thanks!
