### ISSUE TITLE
Anchor stride setup

### ISSUE THREAD

**Issue by Godricly** [facebookresearch/maskrcnn-benchmark#87]
## ❓ Questions and Help
Could it be possible to remove anchor_stride parameter? Since it can be inferred from image and feature map size. I also noticed some extra logic to make sure the its size identical to anchor_size.

**Comment by fmassa** [comment]
Yes, this should be removed indeed as it is redundant.

I didn't have the chance to remove it before the release, but it would be great to do so in a follow-up PR.

Contributions welcome! :-)
