### ISSUE TITLE
Raise ValueError: Type mismatch (<type 'str'> vs. <type 'tuple'>) with values (coco_2017_train vs. ('coco_2017_train',)) for config key: DATASETS.TRAIN

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#877]

**Comment by SkeletonOne** [comment]
Besides, have anyone used the dcn layer in this project?

**Comment by chang010453** [comment]
when building the datasets, required type is tuple. So you should use ('coco_2017_train',)

**Comment by SkeletonOne** [comment]
@chang010453  Yeah I solved this problem with your method. THX
