### ISSUE TITLE
how to set multi-scale training?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [facebookresearch/maskrcnn-benchmark#88]
## ❓ Questions and Help
when i set `MIN_SIZE_TRAIN: (600,700,800,900,1000)`, i met the problem: `ValueError: Type mismatch (<class 'int'> vs. <class 'tuple'>) with values (800 vs. (600, 700, 800, 900, 1000)) for config key: INPUT.MIN_SIZE_TRAIN`, so how to set the yml file to multi-scale trainging?

thanks.

**Comment by fmassa** [comment]
Multi-scale training support will be added in this PR https://github.com/facebookresearch/maskrcnn-benchmark/pull/69

If you need it for now, you could try cherry-pick the relevant changes there, or directly work from that branch

**Comment by zimenglan-sysu-512** [comment]
thanks @fmassa

**Comment by JoyHuYY1412** [comment]
> Multi-scale training support will be added in this PR #69
> 
> If you need it for now, you could try cherry-pick the relevant changes there, or directly work from that branch

Hi, is this multi-scale training also support mask rcnn?
