### ISSUE TITLE
why kernel_size is 1 in LastLevelMaxPool?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [facebookresearch/maskrcnn-benchmark#908]
hi @fmassa 
why u set kernel_size=1 in [LastLevelMaxPool](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fpn.py#L79)?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/Detectron/blob/a6a835f5b8208c45d0dce217ce9bbda915f44df7/detectron/modeling/FPN.py#L228-L229

**Comment by fmassa** [comment]
Exactly as @ppwwyyxx mentioned
