### ISSUE TITLE
About add more codes in maskrcnn-benchmark file

### ISSUE THREAD

**Issue by ztt0821** [facebookresearch/maskrcnn-benchmark#927]
## ❓ Questions and Help
Hi, I want to add some codes into maskrcnn_benchmark file.  I found when I install, the introduction says
""" 
cd maskrcnn-benchmark

# the following will install the lib with
# symbolic links, so that you can modify
# the files if you want and won't need to
# re-build it
python setup.py build develop
"""
Is that means I don't need to run "python setup.py build develop" again?
And what about the file in maskrcnn_benchmark/csrc? Should I need to change the ".h" files?
Thank you.

**Comment by fmassa** [comment]
@ztt0821 if you change `csrc` files, you need to re-run `python setup.py build develop`, after having removed the `build/` folder.
