### ISSUE TITLE
Will this benchmark support guided anchor?

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#930]
## ❓ Questions and Help
@fmassa  will this benchmark support guided anchor in the future?

**Comment by fmassa** [comment]
There are currently no plans to support Guided Anchor in `maskrcnn_benchmark`, but contributions are welcome!

**Comment by SkeletonOne** [comment]
Thanks! @fmassa @zimenglan-sysu-512 

Shall I close this issue or keep it ?
