### ISSUE TITLE
Which layers are getting trained?

### ISSUE THREAD

**Issue by Darshan2701** [facebookresearch/maskrcnn-benchmark#932]
## ❓ Questions and Help
Hi all,

As I am relatively new to the field of DL, I am trying to understand the code base here. I would like to know with the default settings/values of  "e2e_faster_rcnn_R_50_FPN_1x.yaml" , which layers are we training here when I run train_net.py using transfer learning.

What I have understood is that by default the Resnet-50 with FPN, all layers are frozen. So in that case, will the code start training the RPN network?

It would help if anyone can point me to the right post/provide me with insights about training the layers.

**Comment by bingogome** [comment]
If it is a general question regarding the training, you may want to read the paper in this link: https://arxiv.org/abs/1506.01497 
The training is described in section 3.2.

**Comment by Darshan2701** [comment]
@bingogome, thanks for the link but I do not think the paper talks about introducing FPN into Faster Rcnn which is confusing me here.:)

**Comment by Darshan2701** [comment]
@fmassa It will be really helpful to add a piece of detailed information or link to one which explains the code. I tried understanding the code about freezing layers but really cannot get a hold of it.

**Comment by Darshan2701** [comment]
Figured it out. Thanks
