### ISSUE TITLE
Returned bounding boxes

### ISSUE THREAD

**Issue by mtlouie-unm** [facebookresearch/maskrcnn-benchmark#933]
## ❓ Questions and Help
What is the format of returned bounding boxes found in bbox.json in Inference directory? Is it the same format that the model was trained in (xyxy) or (xywl)?

**Comment by chang010453** [comment]
It is in (xywh) format.

[https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py#L82](url)
