### ISSUE TITLE
How to visualize the segmentation results?

### ISSUE THREAD

**Issue by changxinC** [facebookresearch/maskrcnn-benchmark#934]
## ❓ Questions and Help
I want to visualize the segmentation results, in which different individuals are labeled with different colors. Similar to the infer_simple.py in Detectron version. Thank you very much!

**Comment by fmassa** [comment]
Check the demo in https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/demo
There is code to overlay the segmentation in `predictor.py`
