### ISSUE TITLE
error  in predict, sometimes no results returned after re-build

### ISSUE THREAD

**Issue by yiColddrink** [facebookresearch/maskrcnn-benchmark#945]
## ❓ Questions and Help
I got a trained model in linux, it can predict in windows10, but when i predict it in linux, it can not return results(bbox,mask,..) （remove build and .egg file to re-build are not work）
But i found that when the re-build information return 

```
  Removing maskrcnn-benchmark 0.1 from easy-install.pth file
  Adding maskrcnn-benchmark 0.1 to easy-install.pth file
```

model can be predicted

when return 

```
  maskrcnn-benchmark 0.1 is already the active version in easy-install.pth`
```

model cannot be predicted

Note that above are two different projects, second is from linux, first is copy from windows10
and re-builded.
In the end, I replaced the whole maskrcnn_benchmark folder and then re-build, it finally be normal.
What's the problem of above?

**Comment by Jacobew** [comment]
Hi, I've met the same problem. When maskrcnn-benchmark 0.1 is in the easy-install.pth file, the build log is quite short and the build is not successful (errors when executing "from maskrcnn_benchmark import _C"). 

I've successfully run this project on the same machine and it just failed when I tried to build a copy since I want to run two program simultaneously.

Could you share your solution?

**Comment by Jacobew** [comment]
running build
running build_ext
building 'maskrcnn_benchmark._C' extension
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/maskrcnn_benchmark
g++ -pthread -shared -B /home/wuyangxin/anaconda3/envs/work/compiler_compat -L/home/wuyangxin/anaconda3/envs/work/lib -Wl,-rpath=/home/wuyangxin/anaconda3/envs/work/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.7/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so
running develop
running egg_info
writing maskrcnn_benchmark.egg-info/PKG-INFO
writing dependency_links to maskrcnn_benchmark.egg-info/dependency_links.txt
writing top-level names to maskrcnn_benchmark.egg-info/top_level.txt
reading manifest file 'maskrcnn_benchmark.egg-info/SOURCES.txt'
writing manifest file 'maskrcnn_benchmark.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so -> maskrcnn_benchmark
Creating /data2/wuyangxin/anaconda3/envs/work/lib/python3.7/site-packages/maskrcnn-benchmark.egg-link (link to .)
maskrcnn-benchmark 0.1 is already the active version in easy-install.pth

Installed /home/wuyangxin/workload/maskrcnn-benchmark
Processing dependencies for maskrcnn-benchmark==0.1
Finished processing dependencies for maskrcnn-benchmark==0.1

This is my build log. BTW, I've created a new conda environment to build it.

**Comment by yiColddrink** [comment]
I have solved the problem by cloning a new project
