### ISSUE TITLE
Why evaluation result is map=36  before training

### ISSUE THREAD

**Issue by ljquality** [facebookresearch/maskrcnn-benchmark#949]
## ❓ Questions and Help
I set the max_iter = 100 (almost no training), and get the evaluation result: map=36.64. Map decreases with max_iter increasing. Why? I use the config file "configs/caffe2/e2e_faster_rcnn_R_50_FPN_1x_caffe2.yaml".

**Comment by Darshan2701** [comment]
@ljquality Could you please elaborate?

**Comment by fmassa** [comment]
`configs/caffe2/e2e_faster_rcnn_R_50_FPN_1x_caffe2.yaml` is the config file from a pre-trained caffe2 model, and doesn't have the right parameters for training.

You should use instead the ones in `configs`, like `configs/e2e_faster_rcnn_R_50_FPN_1x.yaml`
