### ISSUE TITLE
BatchCollator pads images, leaving targets unchanged

### ISSUE THREAD

**Issue by IvanBarabanau** [facebookresearch/maskrcnn-benchmark#951]
## 🐛 Bug

```
class BatchCollator(object):
    ...
    def __call__(self, batch):
        transposed_batch = list(zip(*batch))
        images = to_image_list(transposed_batch[0], self.size_divisible)
        targets = transposed_batch[1]
        img_ids = transposed_batch[2]
        return images, targets, img_ids
```
The BatchCollator call invokes ``` to_image_list(tensors, size_divisible)```. This function, in turn, pads the tensors if  the condition ``` isinstance(tensors, (tuple, list))``` is satisfied. The problem is, with the image padding its spatial sizes are changed, however it seems, that the ``` targets ``` remain unchanged, being anchored to the previous spatial sizes.

## Possible Fix

```
class BatchCollator(object):
    ...
    def __call__(self, batch):
        transposed_batch = list(zip(*batch))
        images = to_image_list(transposed_batch[0], self.size_divisible)
        targets = transposed_batch[1]
        targets = [target.resize(size[::-1]) for target, size in zip(targets, images.image_sizes)]
        img_ids = transposed_batch[2]
        return images, targets, img_ids
```

**Comment by fmassa** [comment]
The images are padded in the right-bottom sides.
The current representation that we have for the targets start from the top left corner, so that they are invariant to the padding of the images.
