### ISSUE TITLE
ModuleNotFoundError: No module named 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by satyamr1** [facebookresearch/maskrcnn-benchmark#953]
## ❓ Questions and Help

**ERROR command**

```
$ python webcam.py --min-image-size 300 MODEL.DEVICE cpu
Traceback (most recent call last):
    File "webcam.py", line 5, in <module>
    from maskrcnn_benchmark.config import cfg
    ModuleNotFoundError: No module named 'maskrcnn_benchmark'
```
**There is no GPU on the system, only CPU**

**Directory**
```
$ pwd
/home/emblab/satyam/maskrcnn/maskrcnn-benchmark/demo
```
**package versions**

```
$ python -V
Python 3.6.8 :: Anaconda custom (64-bit)
```

```
>>> import torch
>>> print(torch.__version__)
1.2.0.dev20190704
```

```
$ nvcc --version
The pinstarogram 'nvcc' is currently not installed. You can install it by typing:
sudo apt ll nvidia-cuda-toolkit
```

```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I've looked at all the related issues but none of them solved my problem.

**Comment by jakubLangr** [comment]
Hi @satyamr1 how did you resolve this issue?

**Comment by satyamr1** [comment]
Hi @jakubLangr. Yeah the issue was resolved.

https://github.com/facebookresearch/maskrcnn-benchmark/issues/742#issuecomment-513708135

**Comment by Jenifer-Anjali** [comment]
Hii,
I tried running a program and i get this error. There is no GPU on the system, only CPU and it's windows 10. Can someone please help me with this.
 from maskrcnn_benchmark.utils.env import setup_environment 
ModuleNotFoundError: No module named 'maskrcnn_benchmark'
