### ISSUE TITLE
COCO 2017 Issues 

### ISSUE THREAD

**Issue by BisratM** [facebookresearch/maskrcnn-benchmark#962]
## ❓ Questions and Help
Hello. I have been attempting to follow the readme on training on the COCO 2017 version. I am confused however as to what I'm supposed to do with the custom instances_minival2014.json and instances_valminusminival2014.json files. Currently I have those two files stored in my annotation folder but I get the following error in paths_catalog.py when I try to train: 

`FileNotFoundError: [Errno 2] No such file or directory: '/path/to/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco/val2017/COCO_val2014_000000413056.jpg'`

The naming convention of coco 2014 appears to be completely different than what is used for coco 2017. Has  anyone managed to successfully train on coco 2017? I don't understand how its possible without doing significantly more work than what is described in the readme.

**Comment by fmassa** [comment]
For COCO 2017, the training file is `train`, and the evaluation is `val`.
For COCO 2014, the training files are `train` and `valminusminival` and the evaluation is `minival`.

They have the same images internally. It's just that the original `val` set of COCO 2014 has been split in 2

**Comment by BisratM** [comment]
Thanks for the quick response. I understand the way the images have been portioned but I am having the same issues. Should I rename the images in the training file to be the same as COCO 2014? I don't see how the code as it it could possibly train on COCO 2017.
