### ISSUE TITLE
ValueErrror : bbox should have 2 dimensions ...

### ISSUE THREAD

**Issue by makeastir** [facebookresearch/maskrcnn-benchmark#963]
## ❓ Questions and Help
Hello. 
I'm training own my dataset.
BTW, i met the ValueError : bbox should have 2 dimensions ...

So i have simple questions. 
At this point, What is difference between 1 dimensions and 2 dimensions ?
Could you suggest examples ?

I used PASCAL format and detail of error is below :
![image](https://user-images.githubusercontent.com/37618036/61104366-17625e00-a4b1-11e9-882b-f6ac15f398f3.png)
**This one occurred Error.**

![image](https://user-images.githubusercontent.com/37618036/61104384-2b0dc480-a4b1-11e9-8877-68ffedf2fb15.png)
**This one non-error occurred.**

** The above two xml files are made for the roughly same images. **

I cannot detect to cause of an error.

Could you suggest solution or idea ??

**Comment by Darshan2701** [comment]
@makeastir What's the error exactly? Could you please post some more information?

**Comment by makeastir** [comment]
@Darshan2701 Could you tell me what is different between bbox.dimension = 1 and bbox.dimension =2 ?

**Comment by Darshan2701** [comment]
@makeastir Could you please post the xml files which are giving you errors?

**Comment by makeastir** [comment]
@Darshan2701 I already uploaded at original question. I uploaded again.
![image](https://user-images.githubusercontent.com/37618036/61279897-f1f78c00-a7f1-11e9-97fc-982d61078243.png)
Error occurred xml files....


![image](https://user-images.githubusercontent.com/37618036/61279918-fcb22100-a7f1-11e9-8fd0-f2358f8e74c0.png)
And non-error occurred file.

**Comment by Darshan2701** [comment]
@makeastir I tried locally here and it seems there is no problem with those values. Did you try debugging locally?

**Comment by Darshan2701** [comment]
@makeasti The boxes values are getting converted to tensors with dimension 2. Like, using the above values, bbox has the type tensor([[663.,  10., 856., 656.]]) which is a 2 dimension tensor.

**Comment by makeastir** [comment]
I caught error. My own datasets included error.
I explain my situation for someone who can suffering from same error.

Error detail like below :
> Some annotation files not included object tag.
> It means that no bndbox coordinates.
> When entering training my own dataset, I had no idea about this situation.
> So i debug, using print annotation file name and caught error.
>> Specially caution, If you met this problem, please should examine entire dataset.

I caught problem, so closed this issue.
Thank you for @Darshan2701 .
