### ISSUE TITLE
During the match matrix calculating, matches is a N tensor where N[i] is in [0,M-1], so how to distinguish GT_0 and background?

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/maskrcnn-benchmark#969]

**Comment by fmassa** [comment]
In those cases the matching value is zero, and they get filtered out in https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/modeling/matcher.py#L71

**Comment by shaofengzeng** [comment]
If anchors i matches target[0],  matches[i] = 0. 
in file loss.py, matches is simply clamp by 0, is there any problem ?  some negative anchors may corresponding to target[0]
